kubernetes-sigs/azurefile-csi-driver

OWNERS_ALIASES
RELEASE.md
SECURITY_CONTACTS

Kubernetes repo requirements can be reviewed [here](https://github.com/kubernetes/community/blob/master/github-management/kubernetes-repositories.md)
Add OWNERS_ALIASES
Add RELEASE.md
Add SECURITY_CONTACTS

Confirm to Kubernetes repo requirements

---

.github/ISSUE_TEMPLATE/enhancement.md
.github/ISSUE_TEMPLATE/feature-request.md
.github/PULL_REQUEST_TEMPLATE.md

change issue and PR templates
Fixes #21
cc @Masquerade0097

change issue and PR templates

---

CHANGELOG-v0.1.0-alpha.md

Add CHANGELOG-v0.1.0-alpha.md

---

deploy/azurefile-csi-driver.yaml
pkg/azurefile/identityserver.go

This commit adds liveness check for azurefile CSI drivers
/kind feature
Fixes # https://github.com/csi-driver/azurefile-csi-driver/issues/28
Need to come up with some health check algorithm for this.
```
```

enhance: add liveness check for azurefile csi drivers

---

charts/README.md
charts/azurefile-csi-driver/Chart.yaml
charts/azurefile-csi-driver/templates/NOTES.txt
charts/azurefile-csi-driver/templates/_helpers.tpl
charts/azurefile-csi-driver/templates/azurefile-csi-driver.yaml
charts/azurefile-csi-driver/templates/cluster-role-binding.yaml
charts/azurefile-csi-driver/templates/crd-csi-driver-registry.yaml
charts/azurefile-csi-driver/templates/crd-csi-node-info.yaml
charts/azurefile-csi-driver/templates/csi-azurefile-attacher.yaml
charts/azurefile-csi-driver/templates/csi-azurefile-provisioner.yaml
charts/azurefile-csi-driver/templates/service-account.yaml
charts/azurefile-csi-driver/values.yaml

/kind feature
Fixes #32 
```
[feature] Create Helm chart for driver
```

[feature] Create Helm chart for driver

---

deploy/azurefile-csi-driver.yaml
deploy/crd-csi-driver-registry.yaml
deploy/crd-csi-node-info.yaml
deploy/csi-azurefile-attacher.yaml
deploy/csi-azurefile-provisioner.yaml
deploy/rbac-csi-attacher.yaml
deploy/rbac-csi-provisioner.yaml
docs/install-azurefile-csi-driver.md

fix deploy yaml files

---

OWNERS
OWNERS_ALIASES

Fixes #
```
none
```
cc @feiskyer @khenidak @brendandburns

add owners

---

pkg/azurefileplugin/main.go

/kind bug
This commit fixes info values not getting printed with klog.
Fixes https://github.com/kubernetes-sigs/azuredisk-csi-driver/issues/68
```
fix(klog): fix info values not getting printed with klog
```

fix(klog): fix info values not getting printed with klog

---

Makefile
pkg/azurefile/azurefile.go
pkg/azurefile/version.go

/kind feature
This commit removes injection of driver name from makefile as driver name should not be mutable from external sources.
Fixes #
```
refactor(version): remove injection of drivername from makefile
```

refactor(version): remove injection of driver name from makefile

---

pkg/azurefile/controllerserver.go

/kind bug
Fixes #27 
```
fix sanity test DeleteVolume failure
```

fix sanity test DeleteVolume failure

---

hack/boilerplate/boilerplate.Dockerfile.txt
hack/boilerplate/boilerplate.Makefile.txt
hack/boilerplate/boilerplate.bzl.txt
hack/boilerplate/boilerplate.go.txt
hack/boilerplate/boilerplate.py
hack/boilerplate/boilerplate.py.txt
hack/boilerplate/boilerplate.sh.txt
hack/verify-all.sh
hack/verify-boilerplate.sh
test/e2e/driver/azurefile_csi_driver.go
test/e2e/driver/driver.go
test/e2e/dynamic_provisioning.go
test/e2e/suite_test.go
test/e2e/testsuites/dynamically_provisioned_cmd_volume_tester.go
test/e2e/testsuites/specs.go
test/e2e/testsuites/testsuites.go

Add boilerplate check.
Fixes #45  
```
None
```

add boilerplate check

---

pkg/azurefile/azure.go
pkg/azurefile/controllerserver.go
pkg/azurefile/nodeserver.go

/kind cleanup
Fixes #
```
none
```

use GetStorageAccesskey from azure lib

---

.travis.yml
Makefile

/kind cleanup
This commit renames test-update target to verify-modules as this seems to be more appropriate for this process and also renames `integration-test` and `e2e-test` target to `test-integration` and `test-e2e` respectively.
Fixes #
```
None
```

refactor(makefile): rename `test-update` target to `verify-modules`

---

pkg/csi-common/utils.go
pkg/csi-common/utils_test.go

/kind bug
Mask secrets in logs.
Fixes #60 
```
fix secret value exposed in logs issue
```

fix secret value exposed in logs issue

---

pkg/azurefile/controllerserver.go

/kind feature
Fixes #59
```
feat: add shareName param in driver storage class
```

feat: add shareName param in driver storage class

---

.travis.yml

/kind design
Fixes #
```
none
```
/hold
let's check whether travis CI supports ubuntu-18.04

chore: set CI to use ubuntu-18.04

---

.travis.yml
Makefile
test/integration/README.md
test/sanity/README.md

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```
none
```

chore: rename test names

---

pkg/azurefile/azurefile.go
pkg/azurefile/azurefile_test.go
pkg/azurefile/controllerserver.go
vendor/modules.txt

/kind bug
- set file share name correctly
- save the created volume so that we can know whether the volume exists or not
Fixes #27 
```
fix: create volume sanity test failures
```

fix: create volume sanity test failures

---

deploy/example/azure.json
test/integration/azure.json
test/integration/run-test.sh
test/sanity/run-tests-all-clouds.sh

chore: make sanity test run as root

---

test/sanity/run-tests-all-clouds.sh

chore: run sanity test in user mode

---

pkg/azurefile/azurefile.go
pkg/azurefile/controllerserver.go

When we do sanity test, "create a volume with already existing name and different capacity" can pass.
Signed-off-by: ZeroMagic <anthonyliu@zju.edu.cn>
>
> /kind bug
Fixes #27 
```
fix:  sanity test failures in create volume
```

fix:  sanity test failures in create volume

---

pkg/azurefile/azurefile.go
pkg/azurefile/controllerserver.go

When we do sanity test, "should fail when the requested volume does not exist" can pass.
Signed-off-by: ZeroMagic <anthonyliu@zju.edu.cn>
>
> /kind bug
Fixes #27 
```
```

fix: sanity test failures in validate volume capabilities

---

pkg/azurefile/controllerserver.go
test/sanity/run-tests-all-clouds.sh

/kind design
/hold
Fixes #
```
none
```

chore: enable sanity test in CI

---

deploy/example/logs/v0.3.0/csi-azurefile-controller.log
deploy/example/logs/v0.3.0/csi-azurefile-node.log
deploy/v0.2.0/crd-csi-driver-registry.yaml
deploy/v0.2.0/crd-csi-node-info.yaml
deploy/v0.2.0/csi-azurefile-controller.yaml
deploy/v0.2.0/csi-azurefile-node.yaml
deploy/v0.2.0/rbac-csi-azurefile-controller.yaml
docs/csi-debug.md
docs/install-csi-driver-v0.2.0.md

docs: update installation docs

---

.travis.yml

Separate the tests as several jobs in travis-ci. So that we can get clearer information from the travis-ci panel.
>
> /kind design
Fixes #
```
none
```

chore: separate the tests

---

.travis.yml

/kind design
Fixes #
```
none
```

test: speed up test

---

.travis.yml
Makefile
test/integration/run-test.sh
test/integration/run-tests-all-clouds.sh

test: change test config

---

go.mod
pkg/azurefileplugin/main.go
vendor/modules.txt

/kind feature
Fixes #
```
feat: collect Prometheus metrics from this driver
```

feat: export prometheus metrics

---

deploy/install-driver.sh

test: add install CSI driver script
Fixes #
```
none
```

test: add install CSI driver script

---

deploy/install-driver.sh
test/e2e/run-test.sh

test: fix e2e test config
Fixes #
```
none
```
cc @ZeroMagic

test: fix e2e test config

---

test/e2e/dynamic_provisioning.go
test/e2e/testsuites/dynamically_provisioned_collocated_pod_tester.go

>
> /kind bug
> /kind design
> /kind flake
add e2e test "dynamically_provisioned_collocated_pod_test"
Fixes #91 
```
add e2e test "dynamically_provisioned_collocated_pod_test"
```

test: add e2e test "dynamically_provisioned_collocated_pod_test"

---

test/e2e/dynamic_provisioning.go
test/e2e/testsuites/dynamically_provisioned_read_only_volume_tester.go

Signed-off-by: ZeroMagic <anthonyliu@zju.edu.cn>
/kind test
Fixes #91 
```
none
```

add e2e test "dynamically_provisioned_read_only_volume_test"

---

test/e2e/pre_provisioning.go
test/e2e/testsuites/pre_provisioned_read_only_volume_tester.go

/kind test
add e2e test "pre_provisioned_read_only_volume_test"
Fixes #91 
```
add e2e test "pre_provisioned_read_only_volume_test"
```

test: add e2e test "pre_provisioned_read_only_volume_test"

---

test/e2e/dynamic_provisioning.go
test/e2e/testsuites/dynamically_provisioned_reclaim_policy_tester.go
test/e2e/testsuites/testsuites.go

/kind test
add e2e test "dynamically_provisioned_reclaim_policy_test"
Fixes #91 
```
add e2e test "dynamically_provisioned_reclaim_policy_test"
```

test: add e2e test "dynamically_provisioned_reclaim_policy_test"

---

test/e2e/pre_provisioning.go
test/e2e/testsuites/pre_provisioned_reclaim_policy_tester.go

/kind test
add e2e test "pre_provisioned_reclaim_policy_test"
Fixes #91 
```
add e2e test "pre_provisioned_reclaim_policy_test"
```

test: add e2e test "pre_provisioned_reclaim_policy_test"

---

README.md
deploy/v0.3.0/crd-csi-driver-registry.yaml
deploy/v0.3.0/crd-csi-node-info.yaml
deploy/v0.3.0/csi-azurefile-controller.yaml
deploy/v0.3.0/csi-azurefile-node.yaml
deploy/v0.3.0/rbac-csi-azurefile-controller.yaml
docs/install-azurefile-csi-driver.md
docs/install-csi-driver-v0.3.0.md
test/e2e/README.md

cut off v0.3.0 beta release
Fixes #
```
none
```

doc: cut off v0.3.0 beta release

---

Makefile
deploy/csi-azurefile-controller.yaml
deploy/csi-azurefile-node.yaml

/kind design
Fixes #
```
none
```

chore: switch to v0.4.0 for master branch

---

deploy/csi-azurefile-controller.yaml
deploy/csi-azurefile-node.yaml
deploy/v0.2.0/csi-azurefile-controller.yaml
deploy/v0.2.0/csi-azurefile-node.yaml
deploy/v0.3.0/csi-azurefile-controller.yaml
deploy/v0.3.0/csi-azurefile-node.yaml

/kind feature
set priority class to system critical
Fixes #106 
```
set priority class to system critical
```

feat: set priority class to system critical

---

.travis.yml
Makefile
go.mod
go.sum
hack/verify-all.sh
hack/verify-golint.sh

>
> /kind bug
> /kind design
> /kind flake
/kind test
According to https://issues.apache.org/jira/browse/INFRA-16287, thrift repo from git.apache.org/thrift.git to a new location, without leaving a copy of the repository at the old location, which leads to the following error when I tried to build azurefile-csi-driver
```
fatal: «https://git.apache.org/thrift.git/» unavailable: Failed to connect to git.apache.org port 443: Operation timed out
```
This PR replaces git.apache.org/thrift.git with …

Fix and Improve CI

---

pkg/azurefile/azurefile.go
pkg/azurefile/controllerserver.go
test/sanity/run-test.sh

/kind bug
- check the snapshot if it exists
Since `ListSharesSegment` lists all file shares and snapshots, the process of checking existence is divided into two steps.
1. Judge if the specify snapshot name already exists.
2. If it exists, we should judge if its source file share name equals that we specify. As long as the snapshot already exists,  we will return true. But when the source is different, an error will be returned.
Fixes #
```
check the snapshot if it exists
```

fix: check the snapshot if it exists

---

charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
deploy/csi-azurefile-controller.yaml
deploy/example/snapshot/README.md
deploy/example/snapshot/volumesnapshot-azurefile.yaml
deploy/example/snapshot/volumesnapshotclass-azurefile.yaml

add volume snapshot example
Fixes #
```
add volume snapshot example
```

doc: add volume snapshot example

---

Makefile
README.md

add build-push make command and remove v0.1.0 version doc since it's not necessary
Fixes #
```
none
```

doc: add build-push make command

---

pkg/azurefileplugin/Dockerfile

/kind bug
fix: use secure ubuntu image
Fixes #
```
fix: use secure ubuntu image
```

fix: use secure ubuntu image

---

.travis.yml
Makefile
charts/README.md
go.mod
pkg/azurefile/azurefile.go
pkg/azurefile/controllerserver.go
pkg/azurefileplugin/main.go
test/e2e/driver/azurefile_csi_driver.go
test/e2e/dynamic_provisioning.go
test/e2e/pre_provisioning.go
test/e2e/suite_test.go
test/e2e/testsuites/dynamically_provisioned_cmd_volume_tester.go
test/e2e/testsuites/dynamically_provisioned_collocated_pod_tester.go
test/e2e/testsuites/dynamically_provisioned_delete_pod_tester.go
test/e2e/testsuites/dynamically_provisioned_read_only_volume_tester.go
test/e2e/testsuites/dynamically_provisioned_reclaim_policy_tester.go
test/e2e/testsuites/pre_provisioned_read_only_volume_tester.go
test/e2e/testsuites/pre_provisioned_reclaim_policy_tester.go
test/e2e/testsuites/specs.go
test/e2e/testsuites/testsuites.go
test/integration/integration_test.go
test/sanity/sanity_test.go
test/utils/credentials/credentials.go

>
> /kind bug
> /kind design
> /kind test
> /kind flake
Address https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/166#discussion_r339323340
```
None.
```

Change repo address name

---

test/utils/credentials/credentials.go

/kind cleanup
fix go lint failures

go lint failures

---

test/e2e/manifest/in-tree-vmss.json
test/e2e/manifest/in-tree.json
test/e2e/manifest/linux.json

>
> /kind bug
> /kind design
> /kind test
> /kind flake
For e2e tests, we should not depend on API models that reside in cloud-provider-azure repo.
Fixes #
```
None.
```

Add API models for e2e jobs

---

Makefile
test/utils/azure/azure_helpers.go

>
> /kind bug
> /kind design
> /kind flake
/kind test
`creationTimestamp` tag will be used to determine whether we should delete stale resource groups in upstream test subscription (https://github.com/chewong/rg-cleanup/blob/master/main.go#L112-L134).
Fixes #
```
None.
```

Add job info tags to Azure resource groups

---

Makefile
charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
charts/latest/azurefile-csi-driver/values.yaml
deploy/csi-azurefile-node.yaml
hack/verify-all.sh
hack/verify-helm-chart.sh

>
> /kind bug
> /kind design
> /kind test
> /kind flake
/kind test
Added a check in `pull-azuredisk-csi-driver-verify` that will compare image version in helm chart with manifests in the deploy folder, and return an exit code 1 if a mismatch is found.
```
```

Keep helm chart in sync with manifests in deploy folder

---

docs/dependency-management.md
hack/verify-all.sh
hack/verify-spelling.sh
pkg/azurefile/azurefile.go
test/utils/credentials/credentials.go

>
> /kind bug
> /kind design
> /kind test
> /kind flake
/kind cleanup
Enable spell checking and fix spelling issues.
Fixes #
```
NONE
```

Enable spell checking and fix spelling issues

---

.gitignore
charts/README.md
charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
charts/latest/azurefile-csi-driver/templates/rbac-csi-azurefile-controller.yaml
charts/latest/azurefile-csi-driver/values.yaml
deploy/csi-azurefile-controller.yaml
deploy/rbac-csi-azurefile-controller.yaml

- Settings are adapted from kubernetes-sigs/azuredisk-csi-driver#224
- Updated `csi-provisioner` to v1.4.0
- Updated `csi-attacher` to v1.2.0
related issue: https://github.com/kubernetes-sigs/azuredisk-csi-driver/issues/177
>
/kind feature
Fixes #
```
```

Enable leader election in csi components

---

docs/install-csi-driver-master.md
docs/install-csi-driver-v0.2.0.md
docs/install-csi-driver-v0.3.0.md
pkg/azurefileplugin/Dockerfile

>
> /kind bug
> /kind design
> /kind test
/kind flake
use base-ubuntu image from mcr and tiny docs change
Fixes #
```
```

chore: use base-ubuntu image from mcr and tiny docs change

---

Makefile
pkg/azurefileplugin/Windows.Dockerfile

>
> /kind bug
> /kind design
> /kind test
/kind feature
> /kind flake
Changes to build windows container image of azure file plugin.
Fixes # 
Part of fixing - #24 
```
NONE
```

Build windows container image for azurefile plugin

---

charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
deploy/csi-azurefile-controller.yaml
deploy/csi-azurefile-node.yaml

>
> /kind bug
> /kind design
> /kind test
> /kind flake
We need to set resource requests/limits for azure CSI file driver pods.
Fixes #
```
```

Setting cpu/memory requests/limits for csi file driver containers

---

charts/latest/azurefile-csi-driver/values.yaml
deploy/csi-azurefile-controller.yaml
deploy/csi-azurefile-node.yaml
pkg/azurefile/nodeserver.go
test/e2e/suite_test.go
test/utils/azurefile_log.sh

/kind cleanup
chore: switch to mcr
Fixes #
```
none
```

chore: switch to mcr

---

charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
deploy/csi-azurefile-controller.yaml
deploy/csi-azurefile-node.yaml

/kind cleanup
set larger CPU/Memory limit
Fixes #
```
none
```

chore: set larger CPU/Memory limit

---

.travis.yml

/kind flake
fix broken coverage
Fixes #
```
```

chore: fix broken coverage

---

test/e2e/dynamic_provisioning_test.go
test/e2e/pre_provisioning_test.go
test/e2e/suite_test.go
test/utils/check_driver_pods_restart.sh

/kind flake
add a pod restart check in the e2e test, to make sure there is no pod restart during e2e test, if there is pod restart, e2e test should fail
Fixes #
```
```

chore: add driver pods check

---

pkg/azurefile/azurefile.go
pkg/azurefile/nodeserver.go
test/integration/run-test.sh
test/integration/run-tests-all-clouds.sh

/kind feature
feat: use StageVolume for pv sharing on one node
Fixes #
```
feat: use StageVolume for pv sharing on one node
```

feat: use StageVolume for pv sharing on one node

---

deploy/example/pv-azurefile-csi.yaml
docs/driver-parameters.md

doc: use nodeStageSecretRef instead of nodePublishSecretRef
related to PR: https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/159
Fixes #
```
none
```

doc: use nodeStageSecretRef instead of nodePublishSecretRef

---

README.md
charts/latest/azurefile-csi-driver/Chart.yaml
charts/latest/azurefile-csi-driver/templates/rbac-csi-azurefile-controller.yaml
charts/v0.2.0/azurefile-csi-driver/Chart.yaml
charts/v0.3.0/azurefile-csi-driver/Chart.yaml
charts/v0.4.0/azurefile-csi-driver/Chart.yaml
charts/v0.4.0/azurefile-csi-driver/templates/NOTES.txt
charts/v0.4.0/azurefile-csi-driver/templates/_helpers.tpl
charts/v0.4.0/azurefile-csi-driver/templates/crd-csi-driver-registry.yaml
charts/v0.4.0/azurefile-csi-driver/templates/crd-csi-node-info.yaml
charts/v0.4.0/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
charts/v0.4.0/azurefile-csi-driver/templates/csi-azurefile-node.yaml
charts/v0.4.0/azurefile-csi-driver/templates/rbac-csi-azurefile-controller.yaml
charts/v0.4.0/azurefile-csi-driver/templates/serviceaccount-csi-azurefile-controller.yaml
charts/v0.4.0/azurefile-csi-driver/values.yaml
deploy/rbac-csi-azurefile-controller.yaml
deploy/v0.4.0/crd-csi-driver-registry.yaml
deploy/v0.4.0/crd-csi-node-info.yaml
deploy/v0.4.0/csi-azurefile-controller.yaml
deploy/v0.4.0/csi-azurefile-node.yaml
deploy/v0.4.0/rbac-csi-azurefile-controller.yaml
docs/install-azurefile-csi-driver.md
docs/install-csi-driver-v0.4.0.md

doc: cut off v0.4.0 release
Fixes #
```
doc: cut off v0.4.0 release
```

doc: cut off v0.4.0 release

---

charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
deploy/crd-csi-driver-registry.yaml
deploy/crd-csi-node-info.yaml
deploy/csi-azurefile-controller.yaml
deploy/csi-azurefile-node.yaml
deploy/rbac-csi-azurefile-controller.yaml
pkg/azurefileplugin/main.go

/kind feature
This PR enables MSI support
Fixes #
controller
health: 29612
metrics: 29614
node
health: 29613
```
feat: MSI support
```

feat: MSI support

---

deploy/crd-csi-driver-registry.yaml
deploy/crd-csi-node-info.yaml
deploy/csi-azurefile-controller.yaml
deploy/csi-azurefile-node.yaml
deploy/rbac-csi-azurefile-controller.yaml
hack/verify-all.sh
hack/verify-yamllint.sh

/kind test
test: add yaml lint check
Fixes #
```
none
```

test: add yaml lint check

---

test/e2e/dynamic_provisioning_test.go
test/e2e/pre_provisioning_test.go
test/e2e/testsuites/dynamically_provisioned_invalid_mount_options.go
test/e2e/testsuites/testsuites.go

>
> /kind bug
> /kind design
> /kind test
> /kind flake
Fixes https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/261#issuecomment-584160440
/hold
Waiting for #165 to be merged first so that we could test this PR on an MSI-enabled cluster.
```
```

test: Add negative mountOptions test case

---

deploy/example/nginx-pod-azurefile.yaml
deploy/example/pv-azurefile-csi.yaml
deploy/example/pvc-azurefile-csi-static.yaml
deploy/example/pvc-azurefile-csi.yaml
deploy/example/snapshot/volumesnapshot-azurefile.yaml
deploy/example/snapshot/volumesnapshotclass-azurefile.yaml
deploy/example/storageclass-azurefile-csi-mountoptions.yaml
deploy/example/storageclass-azurefile-csi.yaml
hack/verify-yamllint.sh

doc: fix yaml format
Fixes #
```
none
```

doc: fix yaml format

---

Makefile
test/utils/check_driver_pods_restart.sh

>
> /kind bug
> /kind design
> /kind test
> /kind flake
Fixes https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/169#issuecomment-590309487
Fixes #
```
```

test: increase wait duration while performing helm install

---

charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
charts/latest/azurefile-csi-driver/templates/rbac-csi-azurefile-controller.yaml
charts/latest/azurefile-csi-driver/values.yaml
deploy/csi-azurefile-controller.yaml
deploy/example/resize/README.md
deploy/example/storageclass-azurefile-csi.yaml
deploy/rbac-csi-azurefile-controller.yaml
deploy/v0.2.0/rbac-csi-azurefile-controller.yaml
deploy/v0.3.0/crd-csi-driver-registry.yaml
deploy/v0.3.0/crd-csi-node-info.yaml
deploy/v0.4.0/crd-csi-driver-registry.yaml
deploy/v0.4.0/crd-csi-node-info.yaml
deploy/v0.4.0/csi-azurefile-node.yaml
deploy/v0.4.0/rbac-csi-azurefile-controller.yaml
hack/verify-helm-chart.sh
pkg/azurefile/azurefile.go
pkg/azurefile/nodeserver.go

/kind flake
Fixes #134 
For auzrefile, we do not need to resize the filesystem on the local node. So set NodeExpandVolume to N/A.
```
```

Complete resize feature

---

pkg/azurefile/nodeserver.go

/kind bug
In CSI Spec, it requires that the SP MUST delete the file or directory it created at this path.
Ref: https://github.com/container-storage-interface/spec/blob/master/spec.md#nodeunpublishvolume
Fixes #
```
```

fix: correct the behavior of deleting the target direcotory

---

charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
deploy/csi-azurefile-controller.yaml
docs/csi-dev.md
pkg/azurefile/azurefile.go
pkg/azurefile/azurefile_test.go
pkg/azurefile/nodeserver.go
test/utils/azurefile_log.sh

/kind feature
This PR would 
- detect the broken mount path
- unmount broken mount path
- remount mount path
Fixes #
```
fix: support corrupted mount
```

fix: support corrupted mount

---

test/e2e/driver/driver.go
test/e2e/dynamic_provisioning_test.go
test/e2e/testsuites/dynamically_provisioned_resize_volume_tester.go

/kind test
add the e2e test "should create a volume on demand and resize it".
Fixes #134 
Here I set `allowVolumeExpansion` to true directly. Because we have support expansion now. If we want to use it, the field must be true.
```
add the e2e test "should create a volume on demand and resize it"
```

test: add the e2e test "should create a volume on demand and resize it"

---

pkg/azurefile/nodeserver.go

/kind bug
only mount dir when not mounted in NodeStage
Fixes #
```
none
```

fix: only mount dir when not mounted in NodeStage

---

go.mod
pkg/azurefile/azurefile.go
pkg/azurefile/controllerserver.go
pkg/azurefile/nodeserver.go

/kind feature
Ref: https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/176
provide dynamic provisioning
Fixes #
```
feat: add dynamic VHD disk support
```

feat: add dynamic VHD disk support

---

Makefile
hack/verify-all.sh
pkg/azurefile/azurefile.go
pkg/azurefile/controllerserver.go
test/e2e/dynamic_provisioning_test.go
test/e2e/testsuites/dynamically_provisioned_cmd_volume_tester.go
test/e2e/testsuites/dynamically_provisioned_collocated_pod_tester.go
test/e2e/testsuites/dynamically_provisioned_invalid_mount_options.go
test/e2e/testsuites/dynamically_provisioned_read_only_volume_tester.go
test/e2e/testsuites/dynamically_provisioned_reclaim_policy_tester.go
test/e2e/testsuites/dynamically_provisioned_resize_volume_tester.go
test/e2e/testsuites/specs.go

/kind test
test: add vhd disk e2e test
Fixes #
test: add vhd disk e2e test
```
none
```

test: add vhd disk e2e test

---

deploy/example/disk/README.md
deploy/example/disk/storageclass-azurefile-csi.yaml
deploy/example/disk/storageclass-azurefile-existing-disk.yaml
deploy/example/e2e_usage.md
deploy/example/storageclass-azurefile-existing-share.yaml
hack/verify-yamllint.sh
pkg/azurefile/nodeserver.go

VHD disk doc and also tuning vhd disk mount options
Fixes #
```
none
```

VHD disk doc

---

test/e2e/dynamic_provisioning_test.go

/kind test
test: add one negative e2e case for vhd disk feature
Fixes #
```
none
```

test: add one negative e2e case for vhd disk feature

---

pkg/azurefile/azurefile.go
pkg/azurefile/azurefile_test.go
pkg/azurefile/controllerserver.go
pkg/azurefile/nodeserver.go

/kind feature
chore: change volumeid format to include diskname
Fixes #
```
none
```

chore: change volumeid format to include diskname

---

deploy/example/disk/README.md
deploy/example/disk/pvc-azurefile-disk.yaml
test/e2e/dynamic_provisioning_test.go
test/e2e/testsuites/dynamically_provisioned_delete_pod_tester.go
test/e2e/testsuites/specs.go

/kind test
test: add deployment e2e test
Fixes #
```
none
```

test: add deployment e2e test

---

pkg/azurefile/controllerserver.go

/kind bug
fix: use PVC size for vhd disk
We will use file lease or file meta data to do the locking
Fixes #
```
none
```

fix: use PVC size for vhd disk

---

pkg/azurefile/azurefile.go
pkg/azurefile/controllerserver.go

/kind cleanup
chore: refactor createDisk func
Fixes #
```
none
```

chore: refactor createDisk func

---

README.md
deploy/example/disk/README.md
deploy/example/disk/statefulset-stress.yaml

Fast attach disk doc
Fixes #
```
none
```

Fast attach disk doc

---

deploy/example/disk/README.md
deploy/example/disk/statefulset-stress.yaml
deploy/install-driver-standalone.sh
deploy/uninstall-driver-standalone.sh
docs/install-csi-driver-master.md
pkg/azurefile/controllerserver.go

/kind bug
feat: add lock for create storage account, otherwise when create multiple PVCs, multiple storage accounts would be created.
Fixes #
```
feat: add lock for create storage account
```

feat: add lock for create storage account

---

README.md
charts/v0.5.0/azurefile-csi-driver/Chart.yaml
charts/v0.5.0/azurefile-csi-driver/templates/NOTES.txt
charts/v0.5.0/azurefile-csi-driver/templates/_helpers.tpl
charts/v0.5.0/azurefile-csi-driver/templates/crd-csi-driver-registry.yaml
charts/v0.5.0/azurefile-csi-driver/templates/crd-csi-node-info.yaml
charts/v0.5.0/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
charts/v0.5.0/azurefile-csi-driver/templates/csi-azurefile-node.yaml
charts/v0.5.0/azurefile-csi-driver/templates/rbac-csi-azurefile-controller.yaml
charts/v0.5.0/azurefile-csi-driver/templates/serviceaccount-csi-azurefile-controller.yaml
charts/v0.5.0/azurefile-csi-driver/values.yaml
deploy/install-driver-standalone.sh
deploy/uninstall-driver-standalone.sh
deploy/v0.5.0/crd-csi-driver-registry.yaml
deploy/v0.5.0/crd-csi-node-info.yaml
deploy/v0.5.0/csi-azurefile-controller.yaml
deploy/v0.5.0/csi-azurefile-node.yaml
deploy/v0.5.0/rbac-csi-azurefile-controller.yaml
docs/install-azurefile-csi-driver.md
docs/install-csi-driver-v0.5.0.md
test/e2e/dynamic_provisioning_test.go
test/integration/run-test.sh
test/integration/run-tests-all-clouds.sh

add more docs
/kind feature
chore: cut v0.5.0 release
Fixes #
```
chore: cut v0.5.0 release
```

chore: cut v0.5.0 release

---

pkg/azurefile/azurefile.go
pkg/azurefile/controllerserver.go
test/integration/run-test.sh
test/integration/run-tests-all-clouds.sh
test/sanity/run-test.sh
test/sanity/run-tests-all-clouds.sh

/kind test
Add a parameter yaml file to enable sanity test for vhd disk feature.
Fixes #182 
```
enable sanity test for vhd disk feature
```

test: enable sanity test for vhd disk feature

---

pkg/azurefile/controllerserver.go

/kind feature
support single-node writewrite, multi-node readonly for vhd disk feature
Fixes #203
Fixes #211
Fixes #202
```
feat: support multi-node readonly for vhd disk
```
/hold
hold for test pass and verification

feat: support multi-node readonly

---

pkg/azurefile/azurefile.go
pkg/azurefile/azurefile_test.go

/kind bug
PR(https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/189) introduced a volumeid compatibility issue, this PR is to fix that issue.
Fixes #
cc @aelmanaa
```
fix: volumeid compatibility issue
```

fix: volumeid compatibility issue

---

charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
deploy/csi-azurefile-node.yaml

/kind bug
fix: make node daemonset ignore taint
Fixes #
```
none
```

fix: make node daemonset ignore taint

---

Makefile
test/e2e/README.md
test/e2e/driver/azurefile_driver.go
test/e2e/driver/driver.go
test/e2e/dynamic_provisioning_test.go
test/e2e/manifest/in-tree-vmss.json
test/e2e/manifest/in-tree.json
test/e2e/manifest/linux-vmss.json
test/e2e/manifest/linux.json
test/e2e/pre_provisioning_test.go
test/e2e/suite_test.go
test/e2e/testsuites/dynamically_provisioned_read_only_volume_tester.go
test/e2e/testsuites/specs.go
test/e2e/testsuites/testsuites.go

>
> /kind bug
> /kind design
> /kind test
> /kind flake
Fixes #
```
```

Add e2e test support for Windows clusters

---

charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
charts/v0.2.0/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
charts/v0.2.0/azurefile-csi-driver/templates/csi-azurefile-node.yaml
charts/v0.3.0/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
charts/v0.3.0/azurefile-csi-driver/templates/csi-azurefile-node.yaml
charts/v0.4.0/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
charts/v0.4.0/azurefile-csi-driver/templates/csi-azurefile-node.yaml
charts/v0.5.0/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
charts/v0.5.0/azurefile-csi-driver/templates/csi-azurefile-node.yaml
deploy/csi-azurefile-controller.yaml
deploy/csi-azurefile-node.yaml
deploy/v0.2.0/csi-azurefile-controller.yaml
deploy/v0.2.0/csi-azurefile-node.yaml
deploy/v0.3.0/csi-azurefile-controller.yaml
deploy/v0.3.0/csi-azurefile-node.yaml
deploy/v0.4.0/csi-azurefile-controller.yaml
deploy/v0.4.0/csi-azurefile-node.yaml
deploy/v0.5.0/csi-azurefile-controller.yaml
deploy/v0.5.0/csi-azurefile-node.yaml
test/e2e/testsuites/testsuites.go

/kind cleanup
Ref: kubernetes/kubernetes#89477
Fixes #
```
```

chore: replace beta label to GA label for kubernetes.io/os

---

charts/latest/azurefile-csi-driver/values.yaml
deploy/csi-azurefile-node.yaml

/kind feature
upgrade node-driver-registrar version
Fixes #
```
none
```

chore: upgrade node-driver-registrar version

---

README.md
deploy/csi-azurefile-node-windows.yaml
deploy/example/windows/README.md
deploy/example/windows/deployment.yaml
deploy/example/windows/statefulset.yaml
deploy/install-driver-standalone.sh
docs/install-csi-driver-master.md
hack/verify-yamllint.sh

add windows feature doc
Ref: #24 
Fixes #
```
```

doc: add windows feature doc

---

README.md
deploy/install-driver-standalone.sh
deploy/uninstall-driver-standalone.sh
docs/install-csi-driver-master.md
docs/read-from-secret.md

doc: read cloud config from secret doc

---

Makefile
deploy/csi-azurefile-node-windows.yaml
deploy/example/windows/README.md
docs/install-csi-driver-master.md
pkg/azurefileplugin/README.md

doc: refine windows doc
Fixes #
```
none
```

doc: refine windows doc

---

deploy/example/windows/README.md
deploy/install-driver.sh
deploy/uninstall-driver.sh
docs/install-csi-driver-master.md
test/e2e/suite_test.go

/kind test
test: add install/uninstall deployment script test
Fixes #
```
none
```

test: add install/uninstall deployment script test

---

test/e2e/dynamic_provisioning_test.go
test/e2e/testsuites/dynamically_provisioned_delete_pod_tester.go

>
> /kind bug
> /kind design
> /kind test
> /kind flake
For `should create a deployment object, write and read to it, delete the pod and write and read to it again` test case, we should ensure the text file created by the deployment exists before deleting the pod.
Fixes https://github.com/kubernetes/kubernetes/pull/89768#issuecomment-607910662.
```
```

test: deflake deployment test case

---

charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
deploy/csi-azurefile-controller.yaml
deploy/csi-azurefile-node-windows.yaml
deploy/csi-azurefile-node.yaml

/kind bug
fix: set cpu,memory limit to a higher value to prevent restart when load is high
Fixes #
```
fix: set cpu,memory limit to a higher value
```

fix: set cpu,memory limit to a higher value

---

Makefile
charts/README.md
charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
charts/latest/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
charts/latest/azurefile-csi-driver/values.yaml
deploy/csi-azurefile-controller.yaml
docs/csi-debug.md
test/e2e/dynamic_provisioning_test.go
test/e2e/pre_provisioning_test.go
test/e2e/testsuites/dynamically_provisioned_read_only_volume_tester.go
test/e2e/testsuites/pre_provisioned_read_only_volume_tester.go

>
> /kind bug
> /kind design
> /kind test
> /kind flake
What this PR does / why we need it:
This PR allows future PRs to build, push and test Azure File CSI Driver Windows containers. 
/assign @andyzhangx
/cc @ZeroMagic
Fixes #
```
```

test: run CSI driver e2e tests on Windows clusters

---

README.md
charts/v0.6.0/azurefile-csi-driver/Chart.yaml
charts/v0.6.0/azurefile-csi-driver/templates/NOTES.txt
charts/v0.6.0/azurefile-csi-driver/templates/_helpers.tpl
charts/v0.6.0/azurefile-csi-driver/templates/crd-csi-node-info.yaml
charts/v0.6.0/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
charts/v0.6.0/azurefile-csi-driver/templates/csi-azurefile-driver.yaml
charts/v0.6.0/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
charts/v0.6.0/azurefile-csi-driver/templates/csi-azurefile-node.yaml
charts/v0.6.0/azurefile-csi-driver/templates/rbac-csi-azurefile-controller.yaml
charts/v0.6.0/azurefile-csi-driver/templates/serviceaccount-csi-azurefile-controller.yaml
charts/v0.6.0/azurefile-csi-driver/values.yaml
deploy/example/disk/README.md
deploy/v0.6.0/crd-csi-node-info.yaml
deploy/v0.6.0/csi-azurefile-controller.yaml
deploy/v0.6.0/csi-azurefile-driver.yaml
deploy/v0.6.0/csi-azurefile-node-windows.yaml
deploy/v0.6.0/csi-azurefile-node.yaml
deploy/v0.6.0/rbac-csi-azurefile-controller.yaml
docs/install-azurefile-csi-driver.md
docs/install-csi-driver-v0.6.0.md

doc: cut v0.6.0 release
Fixes #
```
doc: cut v0.6.0 release
```

doc: cut v0.6.0 release

---

pkg/azurefile/nodeserver.go

/kind feature
add `nostrictsync` option
Fixes #210
```
```

feat: add nostrictsync option

---

charts/latest/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
charts/latest/azurefile-csi-driver/templates/rbac-csi-azurefile-controller.yaml
charts/latest/azurefile-csi-driver/templates/rbac-csi-azurefile-secret.yaml
charts/latest/azurefile-csi-driver/templates/serviceaccount-csi-azurefile-node.yaml
deploy/install-driver.sh
deploy/rbac-csi-azurefile-controller.yaml
deploy/rbac-csi-azurefile-node.yaml
deploy/uninstall-driver.sh
hack/boilerplate/boilerplate.py
hack/update-gomod.sh
pkg/azurefile/azure.go
pkg/azurefile/azure_test.go
pkg/azurefile/azurefile.go
pkg/azurefileplugin/main.go
test/e2e/suite_test.go

/kind feature
/kind flake
- read cloud config from secret 
- update the related deployment
- add the related doc
Fixes #239 
```
read cloud config from secret 
```

feat: read cloud config from secret

---

pkg/azurefile/azurefile.go
pkg/azurefile/controllerserver.go
pkg/azurefile/nodeserver.go
test/e2e/driver/azurefile_driver.go
test/e2e/driver/driver.go
test/e2e/pre_provisioning_test.go
test/e2e/testsuites/pre_provisioned_existing_credentials_tester.go

/kind test
add the e2e test "use existing credentials in k8s cluster"
Fixes #143 
```
```

test: add the e2e test "use existing credentials in k8s cluster"

---

test/e2e/driver/azurefile_driver.go
test/e2e/driver/driver.go
test/e2e/pre_provisioning_test.go
test/e2e/testsuites/pre_provisioned_existing_credentials_tester.go
test/e2e/testsuites/pre_provisioned_provided_credentials_tester.go
test/e2e/testsuites/specs.go
test/e2e/testsuites/testsuites.go

/kind test
Ref: https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/deploy/example/e2e_usage.md#option3-static-provisioninguse-an-existing-azure-file-share
add the e2e test "should use provided credentials"
Fixes #143 
```
```

test: add the e2e test "should use provided credentials"

---

test/e2e/dynamic_provisioning_test.go
test/e2e/testsuites/testsuites.go

/kind test
test: switch to use busybox
Fixes #
```
none
```

test: switch to use busybox

---

test/e2e/manifest/linux-vmss.json

/kind test
test: run e2e tests on Ubuntu 18.04
Fixes #
```
none
```

test: run e2e tests on Ubuntu 18.04

---

Makefile
charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
deploy/csi-azurefile-controller.yaml
pkg/azurefile/azurefile.go
pkg/azurefileplugin/main.go

/kind bug
fix: disable IMDS in controller to support MSI
Fixes #
```
fix: disable IMDS in controller to support MSI
```

fix: disable IMDS in controller to support MSI

---

charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
deploy/csi-azurefile-controller.yaml
deploy/csi-azurefile-node.yaml

/kind feature
chore: lower the cpu/memory limits
Fixes #
```
none
```

chore: lower the cpu/memory limits

---

charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
charts/latest/azurefile-csi-driver/templates/rbac-csi-azurefile-controller.yaml
charts/latest/azurefile-csi-driver/values.yaml
deploy/csi-azurefile-controller.yaml
deploy/rbac-csi-azurefile-controller.yaml

/kind feature
chore: upgrade csi-attacher to v2.2.0
Fixes #
```
none
```

chore: upgrade csi-attacher to v2.2.0

---

test/e2e/manifest/in-tree-vmss.json
test/e2e/manifest/in-tree.json
test/e2e/manifest/linux-vmss.json
test/e2e/manifest/linux.json

/kind test
test: remove "storageProfile" field in test config
Fixes #
```
none
```

test: remove "storageProfile" field in test config

---

deploy/example/pv-azurefile-csi.yaml
hack/verify-spelling.sh

doc: add mountOptions
Fixes #
```
none
```

doc: add mountOptions

---

pkg/azurefile/controllerserver.go

/kind feature
fix: allow unknown parameters in CreateVolume
Fixes #
```
none
```

fix: allow unknown parameters in CreateVolume

---

pkg/csi-common/driver_test.go
pkg/csi-common/identityserver-default_test.go

>
> /kind bug
> /kind design
> /kind flake
/kind test
Fixes #
```
Add unit tests for driver and identity server
```

Tests:Improve Unit Tests for driver and identityserver

---

Makefile
test/e2e/dynamic_provisioning_test.go
test/e2e/suite_test.go

/kind test
test: change publish image script
Fixes #
```
cd $csi_file
export REGISTRY_NAME=
export REGISTRY=$REGISTRY_NAME.azurecr.io
export IMAGE_NAME=public/k8s/csi/azurefile-csi
export CI=1
export PUBLISH=1
make azurefile-container
make push
make push-latest
```
```
none
```

test: change publish image script

---

pkg/azurefile/azurefile_test.go
pkg/azurefile/identityserver_test.go
pkg/csi-common/controllerserver-default_test.go
pkg/csi-common/utils_test.go

>
> /kind bug
> /kind design
> /kind flake
/kind test
Adds unit tests to improve test coverage
Fixes #
```
Add unit tests for: azurefile, csi-common/utils, controllerserver-default, identityserver 
```

tests: Add unit tests

---

pkg/azurefile/azure.go

/kind bug
fix: empty azure cred file env var issue
Fixes #
```
fix: empty azure cred file env var issue
```

fix: empty azure cred file env var issue

---

go.mod
pkg/azurefile/azurefile_test.go

>
> /kind bug
> /kind design
> /kind flake
/kind test
Improve test coverage
Fixes #
Using `golang/mock` for unit-tests. The same has been added to `go.mod`
```
Tests: Add unit tests for azurefile
```

Test: Add tests for azurefile

---

deploy/example/storageclass-azurefile-csi-mountoptions.yaml
deploy/example/storageclass-azurefile-csi.yaml

doc: set Standard_LRS as default in example
Fixes #291
```
none
```

doc: set Standard_LRS as default in example

---

pkg/azurefile/version_test.go

>
> /kind bug
> /kind design
> /kind flake
/kind test
Fixes #
```
Tests: Add tests for Version
```

Tests: Add tests for Version

---

deploy/example/windows/README.md
deploy/example/windows/deployment.yaml
deploy/example/windows/statefulset.yaml

doc: update windows docs
Fixes #
```
none
```

doc: update windows docs

---

deploy/example/pv-azurefile-csi.yaml
deploy/example/storageclass-azurefile-csi-mountoptions.yaml
deploy/example/storageclass-azurefile-existing-share.yaml
docs/driver-parameters.md
pkg/azurefile/azurefile.go
pkg/azurefile/nodeserver.go

/kind feature
feat: add storage account private link support
With this PR, user could specify a self-defined account address in azure file storage class setting:
```yaml
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
name: file.csi.azure.com
provisioner: file.csi.azure.com
parameters:
resourceGroup: EXISTING_RESOURCE_GROUP_NAME
storageAccount: EXISTING_STORAGE_ACCOUNT_NAME
shareName: SHARE_NAME
server: SERVER_ADDRESS  # optional, provide a new address to replace default "accountname.blob.core.windows.net"
reclaimPolicy: Delete
```
Fixes #238
testing image: `andyzhangx/azurefile-csi:v0.8.0-plink`
```
feat: add storage …
```

feat: add storage account private link support

---

pkg/azurefile/controllerserver_test.go

>
> /kind bug
> /kind design
> /kind flake
/kind test
Improves test coverage
Fixes #
```
Tests: Add Controller server tests
```

Tests: Add Controller server tests

---

deploy/example/pv-azurefile-csi.yaml
docs/driver-parameters.md

doc: fix volumeid doc
Fixes #
```
none
```

doc: fix volumeid doc

---

.github/PULL_REQUEST_TEMPLATE.md
pkg/azurefile/nodeserver.go

/kind bug
fix: remove secret logging in NodeStageVolume
Fixes #
```
none
```

fix: remove secret logging in NodeStageVolume

---

deploy/example/deployment.yaml
deploy/example/disk/README.md
deploy/example/disk/pvc-azurefile-disk.yaml
deploy/example/disk/statefulset-stress.yaml
deploy/example/disk/storageclass-azurefile-csi.yaml
deploy/example/disk/storageclass-azurefile-existing-disk.yaml
deploy/example/pvc-azurefile-csi.yaml
deploy/example/resize/README.md
deploy/example/storageclass-azurefile-csi-mountoptions.yaml
deploy/example/storageclass-azurefile-csi.yaml
deploy/example/storageclass-azurefile-existing-share.yaml
deploy/example/windows/deployment.yaml

doc: rename storage class to azurefile-csi
Fixes #
```
none
```

doc: rename storage class to azurefile-csi

---

test/e2e/dynamic_provisioning_test.go
test/e2e/testsuites/dynamically_provisioned_pod_with_multiple_pv.go
test/e2e/testsuites/specs.go

/kind test
test: add multiple PVs e2e tests
Fixes #
```
none
```

test: add multiple PVs e2e tests

---

test/e2e/dynamic_provisioning_test.go

/kind test
test: fixed multiple PVs e2e test issue, in-tree driver e2e test would fail due to volume size issue(minimum size for `Premium_LRS` is 100GB)
Fixes #
```
none
```

test: fixed multiple PVs e2e test issue

---

test/e2e/dynamic_provisioning_test.go

/kind test
test: disable multiple PV test on in-tree driver
```
Jun 22 21:04:27.581: INFO: At 2020-06-22 21:03:00 +0000 UTC - event for pvc-m4s2v: {persistentvolume-controller } ProvisioningFailed: Failed to provision volume with StorageClass "azurefile-3015-kubernetes.io-azure-file-dynamic-sc-2hgnl": could not get storage key for storage account : Failed to create storage account fa2dbd76a9df2453ead36ff, error: &{false 400 0001-01-01 00:00:00 +0000 UTC Retriable: false, RetryAfter: 0s, HTTPStatusCode: 400, RawError: {"error":{"code":"LocationNotValid","message":"Supplied location southcentralus is not valid."}}}
```
https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/92330/pull-kubernetes-e2e-azure-file-window …

test: disable multiple PV test on in-tree driver

---

deploy/example/pv-azurefile-csi.yaml
deploy/example/storageclass-azurefile-existing-share.yaml
docs/driver-parameters.md
pkg/azurefile/nodeserver.go

fix private link docs
Fixes #
```
none
```

doc: fix private link docs

---

test/e2e/testsuites/testsuites.go

/kind test
tsst: fix in-tree e2e tests failure
Fixes #319
```
none
```

tsst: fix in-tree e2e tests failure

---

pkg/azurefile/azure_common_linux.go
pkg/azurefile/azure_common_windows.go
pkg/azurefile/nodeserver.go

/kind bug
Original `k8s.io/utils/mount` is insecure, when there is mount failure, it would log all mount options which may contain password, this PR would use `MountSensitive` func instead.
Fixes #
```
fix: use MountSensitive to prevent password logging leak
```

fix: use MountSensitive to prevent password logging leak

---

pkg/azurefile/azurefile_test.go
pkg/azurefile/controllerserver_test.go
pkg/csi-common/server.go
pkg/csi-common/server_test.go

This commit also add some nit suggestions to server
and server_test.
>
> /kind bug
> /kind design
> /kind flake
/kind test
Adds unit tests
Fixes #
```
test: Add tests for azurefile and controllerserver
```

test: Add tests for azurefile and controllerserver

---

pkg/azurefile/azurefile_test.go
pkg/azurefile/controllerserver_test.go
pkg/azurefile/nodeserver_test.go
pkg/azurefile/utils_test.go
pkg/csi-common/controllerserver-default_test.go

This commit adds unit tests for unimplemented methods.
The commit also adds minor unit tests for azurefile and
azurefile/utils.
The imported dependencies are also sorted.
>
> /kind bug
> /kind design
> /kind test
> /kind flake
Fixes #
```
none
```

test: Add unit tests

---

README.md
deploy/example/deployment.yaml
deploy/example/disk/README.md
deploy/example/nfs/README.md
deploy/example/statefulset.yaml
deploy/example/storageclass-azurefile-existing-share.yaml
deploy/example/storageclass-azurefile-nfs.yaml
docs/driver-parameters.md
pkg/azurefile/azurefile.go
pkg/azurefile/controllerserver.go
pkg/azurefile/controllerserver_test.go
pkg/azurefile/nodeserver.go
pkg/azurefile/nodeserver_test.go
pkg/azurefile/utils.go
pkg/azurefile/utils_test.go
pkg/azurefileplugin/Dockerfile
test/e2e/dynamic_provisioning_test.go

/kind feature
This PR adds NFS support, user needs to specify a pre-configured `storageAccount`(with network setting configured) and `fsType: nfs` in storage class to provision a NFS file share:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
name: azurefile-csi
provisioner: file.csi.azure.com
parameters:
storageAccount: EXISTING_STORAGE_ACCOUNT_NAME
fsType: nfs # available values: cifs, nfs
```
Fixes #261
```
none
```

feat: add NFS support

---

deploy/install-driver.sh

/kind bug
Fixes #330
```
none
```

fix: installation issue

---

go.mod
go.sum
pkg/azurefile/azure.go
pkg/azurefile/azure_common_windows.go
pkg/azurefile/azurefile.go
pkg/azurefile/controllerserver.go
pkg/azurefile/identityserver.go
pkg/azurefile/nodeserver.go
pkg/azurefile/utils.go
pkg/azurefileplugin/main.go
pkg/csi-common/controllerserver-default.go
pkg/csi-common/driver.go
pkg/csi-common/identityserver-default.go
pkg/csi-common/nodeserver-default.go
pkg/csi-common/server.go
pkg/csi-common/utils.go
pkg/csi-common/utils_test.go
pkg/mounter/safe_mounter_windows.go
vendor/github.com/go-logr/logr/README.md
vendor/github.com/go-logr/logr/go.mod
vendor/github.com/go-logr/logr/logr.go
vendor/k8s.io/klog/v2/go.mod
vendor/k8s.io/klog/v2/go.sum
vendor/k8s.io/klog/v2/klog.go
vendor/k8s.io/utils/exec/testing/fake_exec.go
vendor/modules.txt

/kind bug
fix: logging missing due to klog/v2 change
Now the azure cloud provider lib logs are missing
Fixes #
```
none
```

fix: logging missing due to klog/v2 change

---

go.mod
go.sum
pkg/azurefile/controllerserver.go
vendor/github.com/container-storage-interface/spec/lib/go/csi/csi.pb.go
vendor/modules.txt

/kind feature
chore: upgrade to csi v1.3.0
Fixes #
```
chore: upgrade to csi v1.3.0
```

chore: upgrade to csi v1.3.0

---

pkg/azurefile/azurefile.go
pkg/azurefile/nodeserver.go
pkg/azurefile/nodeserver_test.go

/kind feature
Fixes #334
```
fix: expose GET_VOLUME_STATS
```

fix: expose GET_VOLUME_STATS

---

hack/release-image.sh
pkg/azurefile/controllerserver_test.go

/kind test
chore: add hack/release-image.sh
Fixes #
```
none
```

chore: add hack/release-image.sh

---

.travis.yml
Makefile
deploy/uninstall-driver.sh
pkg/azurefileplugin/dev.Dockerfile

/kind test
This PR adds back dev.Dockerfile for testing purpose since original Dockerfile would only build master branch other than user's own branch.
Fixes #
```
none
```

test: add dev.Dockerfile

---

pkg/azurefile/controllerserver.go
pkg/azurefile/nodeserver.go

/kind bug
This PR uses `wait.PollImmediate` instead of `wait.Poll` function to initial delay(5s) when mounting azure file
https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/4302ea73f4ccb56c7d983d749324f21a05d68981/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go#L397-L429
Fixes #
```
fix: initial delay(5s) when mount azure file
```

fix: initial delay(5s) when mount azure file

---

hack/verify-gomod.sh

/kind test
Fixes #
```
none
```

test: add hack-verify-gomod

---

deploy/example/windows/statefulset.yaml
pkg/azurefile/azurefile.go
pkg/azurefile/controllerserver.go
pkg/azurefile/controllerserver_test.go
pkg/azurefile/utils.go
pkg/azurefile/utils_test.go
test/utils/credentials/credentials.go
test/utils/credentials/credentials_test.go

/kind bug
Retry on EnsureStorageAccount if it's throttled.
Fixes #323
```
retry on EnsureStorageAccount if it's throttled
```

fix: retry on EnsureStorageAccount if it is throttled

---

test/e2e/dynamic_provisioning_test.go

/kind test
test: add mount options e2e test
Fixes #138
```
none
```

test: add mount options e2e test

---

pkg/azurefile/controllerserver.go
pkg/azurefile/controllerserver_test.go
test/sanity/run-test.sh

/kind bug
fix: remove InstanceID check in ControllerPublishVolume, it's not a necessary check
Fixes #
```
fix: remove InstanceID check in ControllerPublishVolume
```

fix: remove InstanceID check in ControllerPublishVolume

---

deploy/csi-azurefile-controller.yaml
deploy/csi-azurefile-node-windows.yaml
deploy/csi-azurefile-node.yaml

/kind cleanup
chore: set default imagePullPolicy
Actually default value of `imagePullPolicy` is `IfNotPresent`, this PR does not change anything, only make user easier to change that value to `Always` if user wants update latest version
Fixes #
```
none
```

chore: set default imagePullPolicy

---

README.md
deploy/example/snapshot/README.md

doc: fix snapshot doc
Fixes #
```
none
```

doc: fix snapshot doc

---

pkg/azurefile/nodeserver.go

/kind bug
fix: add mountOptions support on NFS
Fixes #
```
fix: add mountOptions support on NFS
```

fix: add mountOptions support on NFS

---

deploy/example/nfs/README.md
deploy/example/storageclass-azurefile-nfs.yaml
pkg/azurefile/azurefile.go
pkg/azurefile/azurefile_test.go
pkg/azurefile/controllerserver.go
pkg/azurefile/nodeserver.go

/kind feature
feat: add "protocol: nfs" to replace "fsType: nfs"
use `protocol: nfs` (`smb` by default) is more reasonable, `fsType: nfs` is still valid, it's backward-compatable.
Fixes #
```
feat: add "protocol: nfs" to replace "fsType: nfs"
```

feat: add "protocol: nfs" to replace "fsType: nfs"

---

pkg/azurefile/controllerserver.go

/kind feature
fix: use naming prefix for nfs protocol container
Fixes #
```
feat: use naming prefix for nfs protocol container
```

fix: use naming prefix for nfs protocol container

---

pkg/azurefile/nodeserver.go

/kind bug
fix: password logging issue in Windows node driver logs
Fixes #
```
I0810 07:14:07.750526    6832 utils.go:111] GRPC call: /csi.v1.Node/NodeStageVolume
I0810 07:14:07.750526    6832 utils.go:112] GRPC request: volume_id:"andy-win1186#fca1c6d57af91439aa77889#pvc-56a534ae-8354-48eb-a3bb-9a29f3f00d20#" staging_target_path:"\\var\\lib\\kubelet\\plugins\\kubernetes.io\\csi\\pv\\pvc-56a534ae-8354-48eb-a3bb-9a29f3f00d20\\globalmount" volume_capability:<mount:<fs_type:"ext4" > access_mode:<mode:MULTI_NODE_MULTI_WRITER > > volume_context:<key:"skuName" value:"Standard_LRS" > …
```

fix: password logging issue in Windows node driver logs

---

Makefile
test/e2e/suite_test.go

>
> /kind bug
> /kind design
> /kind test
> /kind flake
- Revert #362
- Add E2E_HELM_OPTIONS to Makefile, which can be overridden by users.
Fixes #
```
none
```

ci: add E2E_HELM_OPTIONS to Makefile

---

Makefile

>
> /kind bug
> /kind design
> /kind test
> /kind flake
Follow-up PR for #367.
Fixes #
```
none
```

ci: add E2E_HELM_OPTIONS to linux e2e-bootstrap make target

---

charts/index.yaml

/kind bug
fix: add v0.8.0 chart index
cc @fredgate
- run following command could add the chart index:
```
helm repo index charts --url=https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts
```
Fixes #369
```
none
```

fix: add v0.8.0 chart index

---

deploy/example/deployment.yaml
deploy/example/nginx-pod-azurefile.yaml
deploy/example/statefulset.yaml
test/utils/azurefile_log.sh

/kind test
test: fix windows test logging issue
Fixes #
```
none
```

test: fix windows test logging issue

---

test/e2e/suite_test.go
test/utils/controller-manager-log.sh

/kind test
test: print kube-controller-manager logs for in-tree driver
Fixes #
```
none
```

test: print kube-controller-manager logs for in-tree driver

---

test/utils/azurefile_log.sh
test/utils/controller-manager-log.sh

>
> /kind bug
> /kind design
> /kind test
> /kind flake
kubectl logs --prefix is only available for kubectl v1.17+. This PR ensures no error will occur when using an older version of kubectl.
Fixes #
```
none
```

ci: remove --prefix when using kubectl to ensure backward compatibility

---

Makefile
pkg/azurefileplugin/Dockerfile
pkg/azurefileplugin/Windows.Dockerfile

>
> /kind bug
> /kind design
> /kind test
> /kind flake
/assign @andyzhangx
/cc @sozercan
Fixes #
```
none
```

build: build binary outside of builder container to allow binary signing

---

test/e2e/manifest/in-tree.json
test/e2e/manifest/linux.json
test/utils/azurefile_log.sh

test: run e2e tests on containerd
/kind cleanup
Fixes #
```
none
```

test: run e2e tests on containerd

---

.github/PULL_REQUEST_TEMPLATE.md
charts/README.md
charts/latest/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
charts/latest/azurefile-csi-driver/values.yaml
deploy/example/windows/README.md
deploy/install-driver.sh

/kind feature
feat: enable windows feature installation by default
Fixes #
```
feat: enable windows feature installation by default
```

feat: enable windows feature installation by default

---

Makefile
charts/README.md
charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
charts/latest/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
charts/latest/azurefile-csi-driver/values.yaml
deploy/csi-azurefile-controller.yaml
deploy/csi-azurefile-node.yaml
deploy/example/metrics/README.md
deploy/example/metrics/csi-azurefile-controller-svc.yaml
hack/verify-yamllint.sh
test/e2e/suite_test.go
test/utils/azurefile_log.sh

/kind test
test: add metrics logs in e2e test
Fixes #
```
none
```

test: add metrics logs in e2e test

---

deploy/example/daemonset.yaml

fix typo
add daemonset.yaml example
Fixes #
```
none
```

add daemonset.yaml example

---

pkg/azurefileplugin/Dockerfile

/kind cleanup
Update debian base image to v2.1.3 to address CVEs.
```
none
```

Update debian base image to v2.1.3

---

test/e2e/testsuites/dynamically_provisioned_resize_volume_tester.go
test/e2e/testsuites/testsuites.go
test/utils/azure/azure_helpers.go

test: add new judgment in resize e2e-test

---

pkg/azurefile/azurefile.go
pkg/azurefile/azurefile_test.go
pkg/azurefile/controllerserver.go

/kind bug
fix: don't create account if secret is provided
Should not create storage account in bring your own key scenario
Fixes #
```
fix: don't create account if secret is provided
```

fix: don't create account if secret is provided

---

deploy/example/storageclass-azurefile-nfs.yaml
deploy/example/storageclass-azurefile-secret.yaml

fix yamllint
doc: add allowVolumeExpansion in storage class
Fixes #
```
none
```

doc: add allowVolumeExpansion in storage class

---

charts/README.md
charts/latest/azurefile-csi-driver/values.yaml

Addressing [372](https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/372)
Fixes #
```
none
```

feat: Add value in Helm chart for secret used to pull Docker images

---

test/e2e/testsuites/dynamically_provisioned_resize_volume_tester.go

/kind test
test: fix in-tree resize e2e test failure
```
Sep  5 14:47:02.785: INFO: Pod "azurefile-volume-tester-w2nsr" satisfied condition "Succeeded or Failed"
STEP: resizing the pvc
STEP: sleep 30s waiting for resize complete
STEP: checking the resizing result
STEP: checking the resizing PV result
Sep  5 14:47:32.997: FAIL: newPVCSize(11Gi) is not equal to newPVSize(11GiGi)
```
Fixes #
```
none
```

test: fix in-tree resize e2e test failure

---

pkg/azurefile/azurefile.go
pkg/azurefile/azurefile_test.go
pkg/azurefile/controllerserver.go
pkg/azurefile/controllerserver_test.go
test/e2e/dynamic_provisioning_test.go

/kind cleanup
chore: refactor checkFileShare func
Fixes #
```
none
```

chore: refactor checkFileShare func

---

README.md
charts/README.md
charts/latest/azurefile-csi-driver/values.yaml
deploy/csi-azurefile-controller.yaml
deploy/csi-azurefile-node-windows.yaml
deploy/csi-azurefile-node.yaml

doc: change image repo address
Fixes #
```
doc: change image repo address
```

doc: change image repo address

---

test/e2e/testsuites/dynamically_provisioned_resize_volume_tester.go

test: enable resize e2e test for in-tree driver

---

pkg/azurefile/azurefile_client_test.go

test: add unit-test for azurefile_client

---

test/e2e/pre_provisioning_test.go
test/e2e/testsuites/pre_provisioned_multiple_pods.go

test: add one volume with multiple pods e2e test
Fixes #
```
none
```

test: add one volume with multiple pods e2e test

---

README.md
charts/README.md
charts/index.yaml
charts/latest/azurefile-csi-driver/values.yaml
deploy/csi-azurefile-controller.yaml
deploy/csi-azurefile-node-windows.yaml
deploy/csi-azurefile-node.yaml

chore: switch to use k8s/csi repo for master branch
Fixes #
```
chore: switch to use k8s/csi repo for master branch
```

chore: switch to use k8s/csi repo for master branch

---

README.md
deploy/example/daemonset.yaml
deploy/example/deployment.yaml
deploy/example/statefulset.yaml

doc: set ReadWriteMany accessMode
Fixes #
```
none
```

doc: set ReadWriteMany accessMode

---

pkg/azurefile/controllerserver.go

/kind bug
fix: add lock to prevent list account throttling:
```
W0915 14:20:54.496369    8811 controllerserver.go:177] EnsureStorageAccount() failed with error(could not list storage accounts for account type : Retriable: false, RetryAfter: 16s, HTTPStatusCode: 429, RawError: Retriable: false, RetryAfter: 16s, HTTPStatusCode: 429, RawError: {"error":{"code":"TooManyRequests","message":"The request is being throttled as the limit has been reached for operation type - List_PerHour. For more information, see - https://aka.ms/srpthrottlinglimits"}}), waiting for retring
```
Fixes #
```
fix: add lock to prevent list …
```

fix: add lock to prevent list account throttling

---

deploy/csi-azurefile-controller.yaml
deploy/csi-azurefile-node-windows.yaml
deploy/csi-azurefile-node.yaml

fix version to cut v0.9.0
Fixes #
```
none
```

fix version to cut v0.9.0

---

deploy/csi-azurefile-controller.yaml
deploy/csi-azurefile-node-windows.yaml
deploy/csi-azurefile-node.yaml

doc: use latest version for master branch
Fixes #
```
none
```

doc: use latest version for master branch

---

charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
charts/latest/azurefile-csi-driver/values.yaml
deploy/csi-azurefile-controller.yaml

/kind feature
feat: upgrade to csi-provisioner 2.0.1
Fixes #
```
feat: upgrade to csi-provisioner 2.0.1
```

feat: upgrade to csi-provisioner 2.0.1

---

test/e2e/suite_test.go

/kind test
test: add migration test
Fixes #
```
none
```

test: add migration test

---

pkg/azurefile/controllerserver.go

/kind bug
fix: optimize file creation speed using account key
don't use lock when using account key directly; lock is for list account key throttling issue
Fixes #
- cpu, memory usage under stress test:
```
root@andydev:~# k top po -n kube-system
NAME                                        CPU(cores)   MEMORY(bytes)
aks-link-f895cf9bd-4wr4q                    2m           16Mi
coredns-8bbb65c89-pwnx8                     3m           22Mi
coredns-8bbb65c89-wlzqt                     3m           22Mi
coredns-autoscaler-5585bf8c9f-rj4sg         1m           13Mi
csi-azuredisk-controller-559c4cb56c-l6zl8   10m          87Mi …
```

fix: optimize file creation speed using account key

---

pkg/azurefile/nodeserver.go

/kind cleanup
chore: leverage wait.ErrWaitTimeout
`mountComplete` indicator is actually not necessary, if timeout, there is `wait.ErrWaitTimeout` error returned
Fixes #
```
none
```

chore: leverage wait.ErrWaitTimeout

---

pkg/azurefile/azure.go
pkg/azurefile/azurefile.go

/kind cleanup
chore: set kubeclient refactor
Fixes #
```
none
```

chore: set kubeclient refactor

---

pkg/azurefile/controllerserver.go
pkg/azurefile/controllerserver_test.go

/kind bug
fix: only lock when account is not provided
Fixes #
```
none
```

fix: only lock when account is not provided

---

Makefile
deploy/example/daemonset.yaml
deploy/example/deployment.yaml
deploy/example/disk/statefulset-stress.yaml
deploy/example/nginx-pod-azurefile.yaml
deploy/example/statefulset.yaml
test/e2e/suite_test.go
test/utils/azurefile_log.sh

/kind test
test: switch to use mcr nginx image
Fixes #
```
test: switch to use mcr nginx image
```

test: switch to use mcr nginx image

---

.github/workflows/static.yaml

Signed-off-by: Mayank Shah <mayankshah1614@gmail.com>
Add golangci-linter to github actions
Fixes #
```
none
```

CI: Add golangci-linter to github actions

---

pkg/azurefile/controllerserver.go
test/e2e/dynamic_provisioning_test.go
test/e2e/suite_test.go
test/utils/get_storage_account_secret_name.sh

/kind test
test: add bring own key e2e test
Fixes #
```
none
```

test: add bring own key e2e test

---

charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
deploy/csi-azurefile-controller.yaml
deploy/csi-azurefile-node.yaml
pkg/azurefileplugin/Dockerfile
pkg/azurefileplugin/dev.Dockerfile

/kind bug
fix: create nonroot user in Dockerfile
related to issue: https://github.com/Azure/aad-pod-identity/issues/805
Fixes #
```
fix: create nonroot user in Dockerfile
```

fix: create nonroot user in Dockerfile

---

.github/workflows/ubuntu.yml
.github/workflows/windows.yml
test/e2e/suite_test.go
test/utils/azurefile_log.sh
test/utils/check_driver_pods_restart.sh

/kind test
test: only print restart pod logs once
Fixes #
```
none
```

test: only print restart pod logs once

---

charts/latest/azurefile-csi-driver/values.yaml
deploy/csi-azurefile-controller.yaml

/kind feature
chore: upgrade to csi-provisioner v2.0.2
Fixes #
```
chore: upgrade to csi-provisioner v2.0.2
```

chore: upgrade to csi-provisioner v2.0.2

---

charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
deploy/csi-azurefile-node.yaml

/kind bug
fix: use dnsPolicy ClusterFirstWithHostNet for hostNetwork
"ClusterFirstWithHostNet": For Pods running with hostNetwork, you should explicitly set its DNS policy "ClusterFirstWithHostNet".
https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-policy
Fixes #
```
fix: use dnsPolicy ClusterFirstWithHostNet for hostNetwork
```

fix: use dnsPolicy ClusterFirstWithHostNet for hostNetwork

---

.github/workflows/darwin.yaml
Makefile
pkg/azurefile/nodeserver_test.go

Signed-off-by: Mayank Shah <mayankshah1614@gmail.com>
/kind test
enable unit tests for macos in github actions
Fixes #
```
none
```

CI: enable unit tests for macos in github actions

---

deploy/example/nfs/README.md

Updating region list

---

charts/latest/azurefile-csi-driver/values.yaml
deploy/csi-azurefile-controller.yaml

/kind feature
chore: upgrade csi-provisioner to v2.0.4
related to csi migration work: https://github.com/kubernetes-sigs/azurefile-csi-driver/issues/115
Fixes #
```
none
```

chore: upgrade csi-provisioner to v2.0.4

---

deploy/example/pv-azurefile-nfs.yaml
docs/driver-parameters.md
pkg/azurefile/azurefile.go
pkg/azurefile/azurefile_test.go

/kind bug
fix: static NFS pv config issue
Fixes #
```
fix: static NFS pv config issue
```

fix: static NFS pv config issue

---

Makefile
docs/csi-dev.md
hack/release-image.sh
pkg/azurefileplugin/Windows.Dockerfile

image: support multi OS versions for Windows images

---

pkg/azurefile/azure.go
pkg/azurefile/azure_test.go
pkg/azurefile/azurefile.go
pkg/azurefile/controllerserver.go
test/e2e/dynamic_provisioning_test.go

/kind feature
This is the follow-up work of https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/431
Fixes #327
```
Support NFS dynamic scenario. Use vnet setting in azure.json for NFS driver
```

feat: support NFS dynamic scenario

---

pkg/azurefile/azurefile.go

/kind bug
A bug fixed in the `in-tree` was missing in `csi`.
Fixes https://github.com/kubernetes/kubernetes/issues/63326
```
none
```

fix: trim new line for azure storage account name

---

charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
charts/latest/azurefile-csi-driver/values.yaml
deploy/csi-azurefile-controller.yaml
deploy/csi-azurefile-node.yaml

/kind bug
Replace livenessprobe flag --connection-timeout with --probe-timeout.
Update the livenessprobe version from v1.1.0 to v2.0.0.
Update helm charts.
Fixes #
```
none
```

fix: update livenessprobe version from v1.1.0 to v2.0.0

---

pkg/azurefile/azure.go

/kind bug
fix: vnet resource group setting issue
Fixes #
```
fix: vnet resource group setting issue
```

fix: vnet resource group setting issue

---

charts/README.md
charts/latest/azurefile-csi-driver/values.yaml
deploy/csi-azurefile-node-windows.yaml
deploy/csi-azurefile-node.yaml

kind flake
upgrade node-driver-registrar version to v2.0.1
Fixes #
```
upgrade node-driver-registrar version to v2.0.1
```

chore: upgrade node-driver-registrar version to v2.0.1

---

pkg/azurefile/azurefile.go
pkg/azurefile/azurefile_test.go
pkg/azurefile/controllerserver.go
pkg/mounter/safe_mounter_windows.go

/kind bug
This PR fixed following issue:
- set `actimeo =30` by default
- default account type as `Premium_LRS` when using NFS protocol
- driver crash issue on Windows, details: https://github.com/kubernetes-csi/csi-driver-smb/issues/150
Fixes #
```
fix: add actimeo and fix NFS account type issue
```

fix: add actimeo and fix NFS account type issue

---

deploy/example/nfs/README.md
deploy/example/nfs/statefulset.yaml
deploy/example/storageclass-azurefile-nfs.yaml

doc: fix NFS doc naming issue
Fixes #
```
doc: fix NFS doc naming issue
```

doc: fix NFS doc naming issue

---

pkg/azurefileplugin/Windows.Dockerfile

Copy netapi32.dll from windows-servercore-cache (https://github.com/kubernetes/kubernetes/tree/master/test/images/windows-servercore-cache) instead of servercore, which would speed up the image building process by a lot.
Fixes #
```
none
```

fix: copy netapi32.dll from windows-servercore-cache instead of servercore

---

Makefile
charts/README.md
charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
charts/latest/azurefile-csi-driver/values.yaml
deploy/csi-azurefile-controller.yaml

/kind feature
feat: support run controller on master node
Fixes #
```
feat: support run controller on master node
```

feat: support run controller on master node

---

pkg/azurefile/controllerserver.go

/kind bug
fix: incorrect operation status
Fixes #
```
fix: incorrect operation status
```

fix: incorrect operation status

---

Makefile

/kind bug
fix: windows image build error
This is a workaround fix, wait for buildkit fix on v0.8.0: https://github.com/moby/buildkit/pull/1879
Fixes #
```
fix: build windows image error
```

fix: build windows image error

---

Makefile

/kind bug
fix: Windows image build temp failure
Fixes #
```
fix: Windows image build temp failure
```

fix: Windows image build temp failure

---

pkg/azurefile/azurefile.go
pkg/azurefile/azurefile_test.go

/kind cleanup
This PR refactors the `appendDefaultMountOptions` function to use maps and slices for easier extensibility.
Fixes #488
N/A
```
none
```

refactor: appendDefaultMountOptions to use map

---

go.mod
test/sanity/run-test.sh
test/sanity/run-tests-all-clouds.sh
vendor/modules.txt

/kind test
test: refine sanity test script
Fixes #
```
none
```

test: refine sanity test script

---

test/e2e/dynamic_provisioning_test.go
test/e2e/suite_test.go
test/e2e/testsuites/dynamically_provisioned_statefulset_tester.go
test/e2e/testsuites/specs.go
test/e2e/testsuites/testsuites.go

/kind test
Adds statefulset e2e test
Fixes #503
N/A
```
none
```

test: add statefulset e2e test

---

pkg/azurefile/controllerserver.go
pkg/azurefile/nodeserver.go
pkg/azurefile/nodeserver_test.go
test/sanity/run-tests-all-clouds.sh

/kind test
test: run v4.0.2 sanity test
fixed following 2 sanity test failure:
```
Summarizing 2 Failures:
[Fail] Controller Service [Controller Server] volume lifecycle [It] should be idempotent 
/home/prow/go/src/github.com/kubernetes-csi/csi-test/pkg/sanity/controller.go:1675
[Fail] Node Service [It] should be idempotent 
/home/prow/go/src/github.com/kubernetes-csi/csi-test/pkg/sanity/node.go:140
```
Fixes #
```
none
```

test: run v4.0.2 sanity test

---

hack/release-image.sh
pkg/azurefile/nodeserver.go

/kind cleanup
chore: improve NodeStageVolume logging
Fixes #
```
none
```

chore: improve NodeStageVolume logging

---

.github/workflows/darwin.yaml
.github/workflows/ubuntu.yml
.github/workflows/windows.yml

/kind cleanup
test: enable GH actions on all branches
Fixes #
```
none
```

test: enable GH actions on all branches

---

pkg/azurefile/fake_mounter.go
pkg/azurefile/nodeserver_test.go

/kind test
test: refine windows ut
Fixes #
```
none
```

test: refine windows ut

---

docs/driver-parameters.md
pkg/azurefile/azurefile.go
pkg/azurefile/controllerserver.go
pkg/azurefile/controllerserver_test.go
pkg/azurefile/utils.go
pkg/azurefile/utils_test.go
test/e2e/dynamic_provisioning_test.go

/kind feature
feat: add secretName parameter
This PR is mainly for fixing Azure File CSI driver migration issue(workaround node_authorizer error in csi migration scenario), another benefit is add parity feature(`secretName`) in storage class with in-tree driver.
Fixes #
```
feat: add secretName parameter
```

feat: add secretName parameter

---

test/e2e/dynamic_provisioning_test.go

/kind test
test: fix secretName e2e test
Fixes #
```
none
```

test: fix secretName e2e test

---

test/e2e/dynamic_provisioning_test.go

test: fix in-tree e2e test failure
failure:
```
E0109 14:01:12.238664       1 goroutinemap.go:150] Operation for "provision-azurefile-5194/pvc-qtg25[e4de725f-c88c-4add-bab6-10d93e7a26a8]" failed. No retries permitted until 2021-01-09 14:01:13.238648902 +0000 UTC m=+156.630377728 (durationBeforeRetry 1s). Error: "invalid option \"secretName\" for volume plugin kubernetes.io/azure-file"
I0109 14:01:12.238868       1 event.go:291] "Event occurred" object="azurefile-5194/pvc-qtg25" kind="PersistentVolumeClaim" apiVersion="v1" type="Warning" reason="ProvisioningFailed" message="Failed to provision volume with StorageClass \"azurefile-5194-kubernetes.io-azure-file-dynamic-sc-gdwnj\": invalid option …
```

test: fix in-tree e2e test failure

---

pkg/azurefile/controllerserver.go

/kind bug
fix: account creation lock issue
`d.volLockMap.LockEntry(lockKey)` is only for account creation lock, original lock is too big, takes too much time in code.
Fixes #
```
fix: account creation lock issue
```

fix: account creation lock issue

---

charts/README.md
charts/latest/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
charts/latest/azurefile-csi-driver/values.yaml

/kind feature
This PR adds kubeletPath support in Helm chart
Fixes #526 
none
```
feat: add kubeletPath support in Helm chart
```

feat: add kubeletPath support in Helm chart

---

test/e2e/dynamic_provisioning_test.go
test/e2e/testsuites/dynamically_provisioned_restart_driver_tester.go
test/utils/restart_driver_daemonset.sh

/kind test
This PR adds an e2e test to ensure that existing pods still have access to volume after restarting the driver daemonset.
Fixes #154
none
```
none
```

test: add restart driver e2e test

---

charts/latest/azurefile-csi-driver/values.yaml
deploy/csi-azurefile-controller.yaml
deploy/csi-snapshot-controller.yaml

/kind feature
feat: upgrade to snapshotter v3.0.3
Fixes #
```
feat: upgrade to snapshotter v3.0.3
```

feat: upgrade to snapshotter v3.0.3

---

Makefile
deploy/example/daemonset.yaml
deploy/example/statefulset-nonroot.yaml
deploy/example/windows/deployment.yaml
deploy/example/windows/statefulset.yaml
hack/verify-examples.sh
test/e2e/suite_test.go

/kind test
test: add verify example test
Fixes #
```
none
```

test: add verify example test

---

charts/latest/azurefile-csi-driver/values.yaml
deploy/csi-azurefile-controller.yaml
deploy/csi-azurefile-node-windows.yaml
deploy/csi-azurefile-node.yaml

/kind feature
chore: upgrade livenessprobe to v2.2.0
Fixes #
```
chore: upgrade livenessprobe to v2.2.0
```

chore: upgrade livenessprobe to v2.2.0

---

pkg/azurefile/controllerserver.go

/kind feature
feat: add more controller metrics
Fixes #
```
feat: add more controller metrics
```

feat: add more controller metrics

---

deploy/example/windows/README.md
pkg/azurefile/controllerserver.go

/kind feature
feat: add lock in controller
Fixes #
```
feat: add lock in controller
```

feat: add lock in controller

---

go.mod
pkg/azurefileplugin/main.go
vendor/modules.txt

/kind bug
fix: missing cloud_provider_azure metrics
Fixes #
```
fix: missing cloud_provider_azure metrics
```

fix: missing cloud_provider_azure metrics

---

pkg/azurefile/controllerserver.go

/kind feature
feat: skip matching account if exceeding limit
Fixes #
```
feat: skip matching account if exceeding limit
```

feat: skip matching account if exceeding limit

---

charts/latest/azurefile-csi-driver/values.yaml
deploy/csi-azurefile-controller.yaml
pkg/azurefile/identityserver.go

/kind feature
chore: upgrade csi-provisioner to v2.1.0
Fixes #
```
chore: upgrade csi-provisioner to v2.1.0
```

chore: upgrade csi-provisioner to v2.1.0

---

charts/latest/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
deploy/csi-azurefile-node-windows.yaml

/kind bug
DaemonSet in Windows node is not allowed to perform privileged actions so privileged field in security context shouldn't be true
Fixes #
```
fix: remove securityContext on Windows
```

fix: remove securityContext on Windows

---

deploy/example/statefulset-nonroot.yaml
deploy/example/statefulset.yaml

doc: refine examples
Fixes #
```
none
```

doc: refine examples

---

hack/verify-helm-chart.sh

/kind test
test: add helm chart tgz file verification
Fixes #
```
none
```

test: add helm chart tgz file verification

---

test/integration/run-test.sh

/kind test
test: add expand volume integration test
Fixes #
```
none
```

test: add expand volume integration test

---

charts/index.yaml

doc: update charts index
Fixes #
```
none
```

doc: update charts index

---

hack/verify-all.sh
hack/verify-helm-chart-files.sh
hack/verify-helm-chart.sh

/kind test
test: verify helm chart files
Fixes #
```
none
```

test: verify helm chart files

---

Makefile
pkg/csi-common/utils.go
pkg/csi-common/utils_test.go

/kind test
test: only set low level logs in windows tests
Fixes #
```
none
```

test: only set low level logs in windows tests

---

pkg/azurefile/controllerserver_test.go

/kind test
Fixes #
```
none
```

improve the unit test coverage for controllerserver

---

hack/verify-helm-chart-files.sh
pkg/azurefile/controllerserver.go
pkg/azurefile/controllerserver_test.go

/kind bug
fix: incorrect protocol and fsType combination
Fixes #562
```
none
```

fix: incorrect protocol and fsType combination

---

pkg/azurefile/azurefile.go
pkg/azurefile/controllerserver.go

/kind bug
fix: account throttling issue
should sleep more time when hit throttling issue
Fixes #
```
fix: account throttling issue
```

fix: account throttling issue

---

pkg/azurefile/azurefile.go
pkg/azurefile/controllerserver.go

/kind bug
fix: create volume not idempotent when `accountName` is not provided, this would lead to create orphan file shares in creating lots of file share PV in same time
This PR adds a cache map to make sure `CreateVolume` is idemponent
Fixes #
```
fix: create volume not idempotent when `accountName` is not provided
```

fix: create volume not idempotent when accountName is not provided

---

docs/driver-parameters.md
pkg/azurefile/azurefile.go
pkg/azurefile/azurefile_client.go
pkg/azurefile/azurefile_client_test.go
pkg/azurefile/azurefile_test.go
pkg/azurefile/controllerserver.go
pkg/azurefile/utils.go
pkg/azurefile/utils_test.go
test/e2e/dynamic_provisioning_test.go

/kind feature
feat: optimize file share creation in parallel
This PR adds a timed cache to prevent DDos account list operation in parallel, original file share creation in parallel depends on account list limit(100 per 5 minutes per subs): https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/azure-subscription-service-limits#storage-resource-provider-limits
Fixes #200
```
feat: optimize file share creation in parallel
```
/hold

feat: optimize file share creation in parallel

---

pkg/azurefile/azurefile.go

/kind feature
feat: increate remove tag cache as 1 Min
Fixes #
```
none
```

feat: increate remove tag cache as 1 Min

---

pkg/azurefile/azurefile.go

/kind bug
fix: delete should return success when hit not found
Fixes #
```
fix: delete should return success when hit not found
```

fix: delete should return success when hit not found

---

test/e2e/dynamic_provisioning_test.go

Looks like this test case isn't supposed to be run against in-tree storage driver.
Fixes test failure in https://testgrid.k8s.io/provider-azure-upstream#k8s-e2e-azure-file-1-20.
Fixes #
```
none
```

test: disable 'should create a volume on demand with useDataPlaneAPI' test case for in-tree driver

---

test/utils/azure/azure_helpers.go

Changes taken from : https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/744
Fixes #591 
```
none
```

fix: generate key pair for ssh configuration used for vm creation

---

deploy/example/nfs/README.md

Fixing a minor bug in the example and adding the MSI pre-requisite

---

test/e2e/driver/azurefile_driver.go

/kind bug
All letters in share names must be lower case, which was causing some tests to fail when they were generated with capital letters.
Fixes #600  
```
none
```

test: Normalize share name to not include capital letters

---

test/e2e/dynamic_provisioning_test.go
test/e2e/testsuites/dynamically_provisioned_volume_subpath_tester.go
test/e2e/testsuites/specs.go
test/e2e/testsuites/testsuites.go

/kind test
Fixes #565
```
none
```

test: Add e2e test for volume subpath mount

---

docs/driver-parameters.md
pkg/azurefile/controllerserver.go
pkg/azurefile/controllerserver_test.go

/kind feature
fix: disable invalid storage class parameters
Fixes #
```
fix: disable invalid storage class parameters
```

fix: disable invalid storage class parameters

---

pkg/azurefile/controllerserver.go

/kind bug
fix: support create snapshot in parallel
Fixes #
```
fix: support create snapshot in parallel
```

fix: support create snapshot in parallel

---

pkg/azurefile/azurefile.go
pkg/azurefile/controllerserver.go
pkg/azurefile/controllerserver_test.go

/kind bug
fix: honor useDataPlaneAPI in resize
Fixes #
```
fix: honor useDataPlaneAPI in resize
```
/hold

fix: honor useDataPlaneAPI in resize

---

docs/driver-parameters.md
pkg/azurefile/azurefile.go

/kind bug
fix: secret name fetch
Fixes #
```
fix: secret name fetch
```

fix: secret name fetch

---

test/e2e/dynamic_provisioning_test.go
test/e2e/testsuites/dynamically_provisioned_pod_with_multiple_pv.go
test/e2e/testsuites/specs.go

/kind test
test: add multiple NFS volume mount test
Fixes #
```
none
```

test: add multiple NFS volume mount test

---

Makefile

/kind feature
feat: add ARM64 support
Fixes #
```
feat: add ARM64 support
```

feat: add ARM64 support

---

Makefile

/kind bug
fix: ARM64 build
Fixes #
```yaml
{
"schemaVersion": 2,
"mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
"manifests": [
{
"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
"size": 1165,
"digest": "sha256:e1151eb4cebd2348d4d33f3f4cc5822178c3c9ab492f87e0add399fd5028a2c6",
"platform": {
"architecture": "amd64",
"os": "linux"
}
},
{
"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
"size": 1164,
"digest": "sha256:830a113226a06c18e6e9fada45d8b7d2a78cf4c68276e13d17f8735f8db9efe5",
"platform": {
"architecture": "arm64",
"os": "linux"
}
},
{
"mediaType": …
```

fix: ARM64 build

---

deploy/example/windows/deployment.yaml
deploy/example/windows/statefulset.yaml
hack/verify-examples.sh
test/e2e/dynamic_provisioning_test.go
test/e2e/testsuites/dynamically_provisioned_delete_pod_tester.go
test/e2e/testsuites/testsuites.go

/kind test
test: switch to use MCR image in Windows testing
Fixes #
/hold
```
none
```

test: switch to use MCR image in Windows testing

---

pkg/azurefile/azurefile.go
pkg/azurefile/azurefile_test.go
test/e2e/dynamic_provisioning_test.go
test/utils/controller-manager-log.sh

/kind test
test: add SMB 3.1.1 tests
Fixes #
```
none
```

test: add SMB 3.1.1 tests

---

Makefile
docs/csi-dev.md
pkg/azurefileplugin/Dockerfile
pkg/azurefileplugin/Windows.Dockerfile
pkg/azurefileplugin/dev.Dockerfile
test/integration/run-test.sh
test/sanity/run-test.sh

/kind bug
fix: arm64 container build
Fixes the Makefile `container-all` target to build the correct architecture binary and splits outputs into architecture-specific directories to ensure the correct binary is used when building the container image.
Fixes #
```
fix: arm64 container build
```

fix: arm64 container build

---

Makefile
test/external-e2e/run.sh
test/external-e2e/testdriver.yaml

/kind feature
Fixes #
```
none
```

add external k8s e2e tests

---

Makefile

/kind bug
fix: random arm64 build failure
Fixes #
```
none
```

fix: random arm64 build failure

---

.github/workflows/linux.yaml

add sanity test step in github actions. This will help find the problems in advance rather than depending on prow
/kind cleanup
Fixes #
```
none
```

add sanity test step in github actions

---

test/e2e/dynamic_provisioning_test.go

test: disable enableLargeFileshares in-tree test
Fixes #
```
none
```

test: disable enableLargeFileshares in-tree test

---

pkg/azurefile/azurefile.go
pkg/azurefile/azurefile_test.go
pkg/azurefile/controllerserver.go

/kind bug
fix: add volume name as suffix in volumeID for static provisioning
This PR fixed the second pod mount error for static provisioning(sharename specified), this issue only exists from k8s 1.20
Fixes #620
```
fix: second pod mount error for static provisioning(sharename specified)
```

fix: second pod mount error for static provisioning(sharename specified)

---

test/e2e/pre_provisioning_test.go

/kind test
test: add test for volumeID collision fix
Fixes #
```
none
```

test: add test for volumeID collision fix

---

hack/verify-examples.sh
test/e2e/testsuites/dynamically_provisioned_delete_pod_tester.go
test/e2e/testsuites/dynamically_provisioned_statefulset_tester.go

test: fix containerd Windows e2e test failure
Fixes #
```
none
```

test: fix containerd Windows e2e test failure

---

pkg/azurefileplugin/Dockerfile

/kind cleanup
chore: upgrade base image to fix CVE issue
Fixes #651
```
chore: upgrade base image to fix CVE issue
```

chore: upgrade base image to fix CVE issue

---

test/e2e/pre_provisioning_test.go
test/e2e/suite_test.go

/kind test
test: run test on install_driver.sh script
also fixed random test failure in `should use a pre-provisioned volume and mount it by multiple pods` test
Fixes #659
```
none
```

test: run test on install_driver.sh script

---

pkg/azurefile/nodeserver.go
pkg/azurefile/nodeserver_test.go

/kind bug
fix: remove unnecessary lock in NodePublish
Fixes #
```
fix: remove unnecessary lock in NodePublish
```

fix: remove unnecessary lock in NodePublish

---

test/e2e/dynamic_provisioning_test.go

/kind test
test: add inline volume test
Fixes #557
```
none
```

test: add inline volume test

---

test/external-e2e/run.sh
test/external-e2e/testdriver.yaml

/kind test
test: run more external storage tests
Fixes #
```
none
```

test: run more external storage tests

---

test/external-e2e/run.sh

/kind test
test: run external storage test with 1.21 suites
Fixes #
/hold
```
none
```

test: run external storage test with 1.21 suites

---

test/external-e2e/run.sh

/kind test
test: run external tests on NFS
Fixes #
```
none
```

test: run external tests on NFS

---

pkg/azurefile/azure_common_linux.go
pkg/azurefile/nodeserver.go

/kind bug
fix: unmount stuck issue when azure file is not found
Fixes #
/hold
```
fix: unmount stuck issue when azure file is not found
```

fix: unmount stuck issue when azure file is not found

---

pkg/azurefile/azurefile.go

/kind bug
fix: sercretNamesapce empty issue in old driver PV
Fixes #
```
none
```

fix: sercretNamesapce empty issue in old driver PV

---

deploy/example/largeFileShares/README.md
deploy/example/largeFileShares/pvc-azurefile-largefileshares.yaml
deploy/example/largeFileShares/storageclass-azurefile-largefileshares.yaml

doc: Add example enable large file shares

---

pkg/azurefile/nodeserver.go

/kind bug
fix: only use pod.Namespace in inline volume support
Fixes #
```
fix: only use pod.Namespace in inline volume support
```

fix: only use pod.Namespace in inline volume support

---

deploy/example/largeFileShares/pvc-azurefile-largefileshares.yaml
deploy/example/largeFileShares/storageclass-azurefile-largefileshares.yaml
deploy/example/nginx-pod-azurefile-inline-volume.yaml
hack/verify-yamllint.sh

doc: update yaml configs
Fixes #
```
none
```

doc: update yaml configs

---

pkg/azurefile/azurefile.go
pkg/azurefile/controllerserver.go
pkg/azurefile/nodeserver.go

/kind bug
fix: only read secret for inline volume
Fixes #
```
none
```

fix: only read secret for inline volume

---

pkg/azurefile/nodeserver.go
pkg/azurefile/nodeserver_test.go

/kind feature
feat: support customized smb server
This PR would make this driver supports customized smb server leveraging `server` parameter
```console
kubectl create secret generic azure-secret --from-literal=azurestorageaccountname="xxx" --from-literal azurestorageaccountkey="xxx" --type=Opaque
```
```
---
kind: Pod
apiVersion: v1
metadata:
name: nginx-azurefile-inline-volume
spec:
nodeSelector:
"kubernetes.io/os": linux
containers:
- image: mcr.microsoft.com/oss/nginx/nginx:1.19.5
name: nginx-azurefile
command:
- "/bin/bash"
- "-c"
- set -euo pipefail; while true; do echo $(date) >> /mnt/azurefile/outfile; sleep 1; done
volumeMounts:
- name: persistent-storage
mountPath: "/mnt/azurefile"
volumes:
- name: …
```

feat: support customized smb server

---

pkg/azurefile/azure.go
pkg/azurefile/azure_test.go
pkg/azurefile/azurefile.go

/kind feature
fix: controller could run well without cloud provider
Fixes #
```
fix: controller could run well without cloud provider
```

fix: controller could run well without cloud provider

---

pkg/mounter/safe_mounter_windows.go

/kind bug
fix: convert source path on Windows
Fixes #
/hold
```
fix: convert source path on Windows
```

fix: convert source path on Windows

---

Makefile
deploy/example/smb-provisioner/smb-server-lb.yaml
deploy/example/smb-provisioner/smb-server.yaml
pkg/azurefile/azurefile.go
test/e2e/dynamic_provisioning_test.go
test/e2e/suite_test.go
test/e2e/testsuites/dynamically_provisioned_inline_volume.go
test/e2e/testsuites/specs.go
test/e2e/testsuites/testsuites.go

/kind test
test: add on-prem support e2e test
Fixes #
```
none
```

test: add on-prem support e2e test

---

README.md
deploy/example/smb-provisioner/README.md
deploy/example/smb-provisioner/nginx-on-prem-volume.yaml
hack/verify-yamllint.sh

doc: add on-prem server support doc
Fixes #
```
none
```

doc: add on-prem server support doc

---

test/e2e/dynamic_provisioning_test.go
test/utils/get_smb_svc_public_ip.sh

/kind test
test: add e2e test for on-prem server support on Windows
Fixes #
```
none
```

test: add e2e test for on-prem server support on Windows

---

pkg/azurefile/azure.go

/kind bug
fix: read cloud config from secret regression
Fixes #700
```
fix: read cloud config from secret regression
```

fix: read cloud config from secret regression

---

deploy/example/nginx-pod-azurefile-inline-volume.yaml
deploy/example/pv-azurefile-csi.yaml
deploy/example/pv-azurefile-nfs.yaml
pkg/azurefile/azurefile.go
pkg/azurefile/controllerserver.go
pkg/azurefile/nodeserver.go
test/e2e/testsuites/testsuites.go

/kind feature
feat: add mountOptions for inline volume
Fixes #
/hold
```
feat: add mountOptions for inline volume
```

feat: add mountOptions for inline volume

---

deploy/csi-snapshot-controller.yaml

/kind bug
fix: deploy/csi-snapshot-controller.yaml tolerations
Fixes #
```
none
```

fix: deploy/csi-snapshot-controller.yaml tolerations

---

test/e2e/dynamic_provisioning_test.go

add comments
/kind test
test: add storeAccountKey test
Fixes #
```
none
```

test: add storeAccountKey test

---

docs/driver-parameters.md
pkg/azurefile/azurefile.go
pkg/azurefile/azurefile_client.go
pkg/azurefile/controllerserver.go
pkg/azurefile/nodeserver.go

/kind feature
feat: remove cloud config dependency
Fixes #710
/hold
```
feat: remove cloud config dependency
```

feat: remove cloud config dependency

---

pkg/azurefile/controllerserver.go

/kind bug
fix: disable subnet set if account is provided
Fixes #714
```
fix: disable subnet set if account is provided
```

fix: disable subnet set if account is provided

---

hack/verify-examples.sh

chore: Wait for examples to complete and return error on failed rollout

---

pkg/azurefile/version.go
pkg/azurefile/version_test.go

/kind cleanup
chore: show current driver name
Fixes #
```
none
```

chore: show current driver name

---

.github/workflows/windows.yaml

/kind test
test: switch to csi-proxy v1.0.0-rc.1 in unit test
Fixes #
```
none
```

test: switch to csi-proxy v1.0.0-rc.1 in unit test

---

pkg/azurefile/nodeserver.go

/kind bug
fix: conflict inline volume mount options with default
Fixes #733
```
fix: conflict inline volume mount options with default
```

fix: conflict inline volume mount options with default

---

pkg/azurefile/nodeserver.go

/kind bug
fix: unmount failure due to incorrect mount path check
Fixes #
```
fix: unmount failure due to incorrect mount path check
```

fix: unmount failure due to incorrect mount path check

---

pkg/azurefile/azurefile.go
pkg/azurefile/azurefile_test.go
pkg/azurefileplugin/main.go
test/e2e/suite_test.go

/kind cleanup
chore: refine driver parameter setting
Fixes #
```
chore: refine driver parameter setting
```

chore: refine driver parameter setting

---

.github/workflows/windows.yaml
test/e2e/manifest/containerd-windows.json
test/e2e/manifest/migration-windows.json
test/e2e/manifest/windows.json

/kind test
test: switch to csi-proxy-v1.0.0 config
Fixes #
```
none
```

test: switch to csi-proxy-v1.0.0 config

---

pkg/mounter/safe_mounter_v1beta_windows.go

/kind cleanup
cleanup: refine csi-proxy v1beta interface
Fixes #
```
none
```

cleanup: refine csi-proxy v1beta interface

---

deploy/example/e2e_usage.md

Signed-off-by: Cyril Corbon <corboncyril@gmail.com>
/kind bug
fix link in [e2e_usage.md](https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/deploy/example/e2e_usage.md#azure-file-dynamic-provisioning)
kubectl apply was not working    
```shell
kubectl create -f https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/deploy/example/storageclass-azurefile-csi-large-scale.yaml
```
Fixes #
```
none
```

fix(doc): link in kubectl apply is not working

---

README.md

credentials typo on Readme

---

pkg/azurefile/azure.go
pkg/azurefile/azure_test.go

/kind test
test: refine getCloudProvider unit tests
Fixes #
```
none
```

test: refine getCloudProvider unit test

---

pkg/azurefile/version.go
pkg/azurefile/version_test.go

/kind cleanup
fix: remove commit id & build date in userAgent
Fixes #
```
fix: remove commit id & build date in userAgent
```

chore: remove commit id & build date in userAgent

---

pkg/azurefileplugin/dev.Dockerfile

/kind cleanup
chore: upgrade dev base image to bullseye
Fixes #
```
chore: upgrade dev base image to bullseye
```

chore: upgrade dev base image to bullseye

---

test/e2e/dynamic_provisioning_test.go

/kind test
test: fix intree test failures
Fixes #
```
none
```

test: fix intree test failures

---

test/e2e/manifest/in-tree-vmss.json
test/e2e/manifest/in-tree.json
test/e2e/manifest/linux-vmss.json
test/e2e/manifest/migration-windows.json
test/e2e/manifest/migration.json

/kind test
test: remove deprecated test configs
Fixes #
```
none
```

test: remove deprecated test configs

---

pkg/azurefile/azurefile.go
pkg/azurefile/controllerserver.go
pkg/csi-common/utils_test.go
test/sanity/run-test.sh
test/sanity/run-tests-all-clouds.sh

/kind feature
feat: ReadWriteOncePod support
Fixes #
```
feat: ReadWriteOncePod support
```

feat: ReadWriteOncePod support

---

pkg/azurefile/nodeserver.go
pkg/azurefile/utils.go
pkg/azurefile/utils_test.go
vendor/k8s.io/client-go/util/testing/fake_handler.go
vendor/k8s.io/client-go/util/testing/tmpdir.go
vendor/modules.txt

/kind feature
feat: enable fsGroup for nfs
Fixes #
```
feat: enable fsGroup for nfs
```

feat: enable fsGroup for nfs

---

pkg/azurefile/azurefile.go
test/sanity/run-test.sh

/kind feature
feat: add ReadWriteOncePod cap
Fixes #
```
none
```

feat: add ReadWriteOncePod cap

---

Makefile
docs/csi-dev.md

/kind feature
Enables existing functionality for new OS Windows Server 2022
Fixes #
ltsc2022 is the MCR tag for Windows Server 2022
https://hub.docker.com/_/microsoft-windows-nanoserver
There is another identical PR here: https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/1030
```
none
```

feat: adds 'Windows Server 2022' to build process

---

docs/driver-parameters.md
pkg/azurefile/controllerserver.go

/kind feature
feat: set allowBlobPublicAccess as false by default
Fixes https://github.com/Azure/AKS/issues/2552
```
feat: set allowBlobPublicAccess as false by default
```

feat: set allowBlobPublicAccess as false by default

---

Makefile
docs/csi-dev.md

/kind feature
feat: add 20H2 Windows image support
Fixes #
```
feat: add 20H2 Windows image support
```

feat: add 20H2 Windows image support

---

pkg/azurefile/azurefile.go
pkg/azurefile/controllerserver.go
test/e2e/dynamic_provisioning_test.go
test/e2e/suite_test.go

/kind feature
feat: support nfs Premium_ZRS account
Fixes #
/hold
```
feat: support nfs Premium_ZRS account
```

feat: support nfs Premium_ZRS account

---

Makefile
pkg/azurefile/azurefile.go
pkg/azurefile/controllerserver.go
pkg/azurefile/controllerserver_test.go

/kind cleanup
cleanup: remove arm64 image build workaround
Fixes #
```
none
```

cleanup: remove arm64 image build workaround

---

Makefile

/kind cleanup
cleanup: remove 1903 1909 2004 Windows image which is end of life
Fixes #
```
none
```

cleanup: remove 1903 1909 2004 Windows image which is end of life

---

test/external-e2e/run.sh

/kind test
test: run external 1.23 tests
Fixes #
```
none
```

test: run external 1.23 tests

---

.github/workflows/pluto.yaml
Makefile
pkg/azurefileplugin/Dockerfile

/kind bug
fix: CVE-2021-43618 in Ubuntu image
Fixes #
```
test/azuredisk-csi:latest (debian 11.0)
=======================================
Total: 1 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 1, CRITICAL: 0)
+----------+------------------+----------+-------------------+------------------------+---------------------------------------+
| LIBRARY  | VULNERABILITY ID | SEVERITY | INSTALLED VERSION |     FIXED VERSION      |                 TITLE                 |
+----------+------------------+----------+-------------------+------------------------+---------------------------------------+
| libgmp10 | CVE-2021-43618   | HIGH     | …
```

fix: CVE-2021-43618 in Ubuntu image

---

pkg/azurefile/azure.go

/kind bug
fix: return error earlier when subnetName is empty before invoking Azure API
Fixes #856
```
fix: return error earlier when subnetName is empty
```

fix: return error earlier when subnetName is empty

---

docs/driver-parameters.md
pkg/azurefile/azure.go
pkg/azurefile/azurefile.go
pkg/azurefile/controllerserver.go
pkg/azurefile/nodeserver.go

/kind feature
feat: add folderName support
Fixes #
```console
Filesystem                                     Size  Used Avail Use% Mounted on
overlay                                        124G   22G  103G  18% /
tmpfs                                           64M     0   64M   0% /dev
tmpfs                                          3.4G     0  3.4G   0% /sys/fs/cgroup
//account.file.core.windows.net/share/test  100G   64K  100G   1% /mnt/azurefile
```
```
feat: add folderName support
```

feat: add folderName support

---

.github/workflows/static.yaml
deploy/example/snapshot/README.md
deploy/example/snapshot/volumesnapshot-azurefile.yaml
deploy/example/snapshot/volumesnapshotclass-azurefile.yaml

doc: change snapshot v1beta1 to v1
Fixes #
```
none
```

doc: change snapshot v1beta1 to v1

---

Makefile
hack/parse-prow-creds.sh
test/utils/controller-manager-log.sh

test: fix get kcm logs error in e2e test
Fixes #
```
none
```

test: fix get kcm logs error in e2e test

---

pkg/azurefileplugin/Dockerfile

/kind bug
fix: CVE-2021-3996 in image build
Fixes #
```
fix: CVE-2021-3996 in image build
```

fix: CVE-2021-3996 in image build

---

pkg/azurefileplugin/Dockerfile

/kind feature
feat: supports NFSv3 protocol
Fixes #
```
feat: supports NFSv3 protocol
```

feat: supports NFSv3 protocol

---

pkg/azurefileplugin/Dockerfile

/kind cleanup
cleanup: remove unnecessary CVE packages
Fixes #
```
none
```

cleanup: remove unnecessary CVE packages

---

test/external-e2e/run.sh

/kind test
test: enable one subpath external test
Fixes #
```
none
```

test: enable one subpath on smb external test

---

pkg/azurefile/azurefile.go

/kind bug
fix: remove special chars when parsing account name from secret
The space char could be:
```
'\t', '\n', '\v', '\f', '\r', ' ', 0x85, 0xA0
```
Fixes #
```
fix: remove space when parsing account name from secret
```

fix: remove special chars when parsing account name from secret

---

.github/workflows/codespell.yml
.github/workflows/shellcheck.yaml
README.md
deploy/example/largeFileShares/README.md
docs/csi-debug.md
hack/parse-prow-creds.sh
pkg/azurefile/azurefile.go
pkg/azurefile/controllerserver.go
pkg/util/util.go
test/e2e/testsuites/dynamically_provisioned_resize_volume_tester.go
test/e2e/testsuites/testsuites.go
test/integration/run-test.sh
test/sanity/run-tests-all-clouds.sh
test/utils/azurefile_log.sh
test/utils/check_driver_pods_restart.sh
test/utils/get_smb_svc_public_ip.sh
test/utils/get_storage_account_secret_name.sh

test: add codespell shellcheck github actions
Fixes #
```
none
```

test: add codespell shellcheck github actions

---

charts/README.md
pkg/azurefile/azurefile.go

/kind bug
fix: delete file share failure when account is deleted
error msg is like following:
```
{"log":"E0218 01:31:29.351029       1 utils.go:123] GRPC error: rpc error: code = Internal desc = DeleteFileShare pvc-97763941-4ae4-44dd-b8bd-9a2f7541966b under account(xxx) rg(xxx) failed with error: storage.FileSharesClient#Delete: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code=\"ParentResourceNotFound\" Message=\"Can not perform requested operation on nested resource. Parent resource 'xxx' not found.\"\n","stream":"stderr","pod":"csi-azurefile-controller-85bfdcd67b-zffjr","containerID":"d1eea8d4278f9a238b33b778693c885a15d97690a97c871a3c8e179d6593c …
```

fix: delete file share failure when account is deleted

---

docs/driver-parameters.md
pkg/azurefile/azurefile.go
pkg/azurefile/controllerserver.go
pkg/azurefile/controllerserver_test.go
pkg/azurefile/nodeserver.go
pkg/azurefile/nodeserver_test.go
test/e2e/dynamic_provisioning_test.go

/kind feature
feat: add mountPermissions parameter in storage class
Fixes #
```
feat: add mountPermissions parameter in storage class
```

feat: add mountPermissions parameter in storage class

---

test/utils/check_driver_pods_restart.sh

/kind test
The `test/utils/check_driver_pods_restart.sh` currently fails with the following syntax error:
```log
2022/03/04 13:45:00 Check driver pods if restarts ...
check the driver pods if restarts ...
test/utils/check_driver_pods_restart.sh: line 38: [: 0 0 0 0 0: integer expression expected
======================================================================================
```
This PR fixes the script using a more straightforward way of getting the pods with non-zero restart counts.
Fixes #
```
none
```

test: fix driver pod restarts script

---

pkg/azurefile/azurefile.go

/kind bug
fix: reduce account api throttling in removing tags
Fixes #
```
fix: reduce account api throttling in removing tags
```

fix: reduce account api throttling in removing tags

---

test/e2e/suite_test.go

test: fix in-tree driver test failure in k/k
Fixes #
```
none
```

test: fix in-tree driver test failure in k/k

---

pkg/azurefileplugin/Dockerfile

/kind bug
fix: CVE-2022-0778 in image build
Fixes #
```
fix: CVE-2022-0778 in image build
```

fix: CVE-2022-0778 in image build

---

deploy/example/pv-azurefile-nfs.yaml
deploy/example/storageclass-azurefile-nfs.yaml
test/e2e/dynamic_provisioning_test.go

doc: add nconnect mount option in nfs example
Fixes #
```
none
```

doc: add nconnect mount option in nfs example

---

test/e2e/suite_test.go

/kind test
test: add ENV setting info in e2e tests
Fixes #
```
none
```

test: add ENV setting info in e2e tests

---

test/e2e/suite_test.go

/kind test
test: add more debugging info in e2e test
Fixes #
```
none
```

test: add more debugging info in e2e test

---

pkg/azurefileplugin/Dockerfile
pkg/azurefileplugin/Windows.Dockerfile

/kind bug
fix: CVE issues in image build
Fixes #
```
fix: CVE issues in image build
```

fix: CVE issues in image build

---

docs/driver-parameters.md
pkg/azurefile/azurefile.go
pkg/azurefile/controllerserver.go

/kind bug
fix: default secretNamespace should be pvc namespace which is consistent to in-tree driver
Fixes #
```
fix: default secretNamespace should be pvc namespace which is consistent to in-tree driver
```

fix: default secretNamespace should be pvc namespace

---

pkg/azurefileplugin/Dockerfile

/kind bug
fix: CVE-2018-25032
Fixes #
```
Total: 1 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 1, CRITICAL: 0)
+---------+------------------+----------+-------------------+-------------------------+---------------------------------------+
| LIBRARY | VULNERABILITY ID | SEVERITY | INSTALLED VERSION |      FIXED VERSION      |                 TITLE                 |
+---------+------------------+----------+-------------------+-------------------------+---------------------------------------+
| zlib1g  | CVE-2018-25032   | HIGH     | 1:1.2.11.dfsg-2   | 1:1.2.11.dfsg-2+deb11u1 | zlib: A flaw in zlib-1.2.11           |
|         | …
```

fix: CVE-2018-25032 in image build

---

docs/driver-parameters.md
pkg/azurefile/azurefile.go
pkg/azurefile/controllerserver.go
pkg/azurefile/utils.go
pkg/azurefile/utils_test.go
test/e2e/dynamic_provisioning_test.go

/kind feature
feat: add shareNamePrefix parameter in storage class
Fixes #
```
feat: add shareNamePrefix parameter in storage class
```

feat: add shareNamePrefix parameter in storage class

---

pkg/mounter/safe_mounter_v1beta_windows.go
pkg/mounter/safe_mounter_windows.go

/kind cleanup
chore: refine mount on Windows logs
Fixes #
```
none
```

chore: refine mount on Windows logs

---

.github/workflows/windows.yaml

/kind test
test: adjust csi-proxy loglevel in test
Fixes #
```
none
```

test: adjust csi-proxy loglevel in test

---

test/external-e2e/run.sh

test: enable external slow tests
Fixes #
```
none
```

test: enable external slow tests

---

test/external-e2e/testdriver-nfs.yaml
test/external-e2e/testdriver-smb.yaml

/kind test
test: enable volumeMountGroup external tests
Fixes #
```
none
```

test: enable volumeMountGroup external tests

---

docs/driver-parameters.md
test/e2e/suite_test.go
test/e2e/testsuites/dynamically_provisioned_tags_tester.go
test/utils/azure/azure_helpers.go

/kind test
test: add account creation leak test
This test would check whether there are account creation leak issue in e2e test.
Fixes #
```
none
```

test: add account creation leak test

---

pkg/azurefile/controllerserver.go

/kind bug
fix: expand volume failure in csi migration scenario
csi migration scenario, the resource group name is not provided in volumeid
<details>
```
I0416 04:49:09.846131       1 utils.go:76] GRPC call: /csi.v1.Controller/ControllerExpandVolume
I0416 04:49:09.846196       1 utils.go:77] GRPC request: {"capacity_range":{"required_bytes":107374182400},"volume_capability":{"AccessType":{"Mount":{}},"access_mode":{"mode":1}},"volume_id":"#fafcecd3a337c449da7d79f#kubernetes-dynamic-pvc-d101d706-7d66-4479-9b3c-9e7821409b0a#"}
E0416 04:49:09.846455       1 utils.go:81] GRPC error: rpc error: code = Internal desc = expand volume error: failed to get file share (kubernetes-dynamic-pvc-d101d706-7d66-4479-9b3c-9e7821409b0a): …
```

fix: expand volume failure in csi migration scenario

---

test/e2e/dynamic_provisioning_test.go

test: enable disableDeleteRetentionPolicy test
Fixes #
```
none
```

test: enable disableDeleteRetentionPolicy test

---

pkg/azurefileplugin/Dockerfile

/kind cleanup
chore: refine package patching in image build
Fixes #
```
none
```

chore: refine package patching in image build

---

test/e2e/dynamic_provisioning_test.go

test: fix in-tree test failure due to matchTags parameter issue
Fixes #
```
none
```

test: fix in-tree test failure due to matchTags parameter issue

---

pkg/azurefile/azurefile.go
pkg/azurefile/azurefile_test.go
pkg/azurefile/controllerserver.go
test/e2e/testsuites/dynamically_provisioned_resize_volume_tester.go
test/e2e/testsuites/dynamically_provisioned_tags_tester.go

/kind feature
chore: add secretNamespace to volumeid
Fixes #
```
none
```

chore: add secretNamespace to volumeid

---

pkg/azurefileplugin/Dockerfile

/kind cleanup
chore: switch base image registry
Fixes #
```
none
```

chore: switch base image registry

---

pkg/azurefile/controllerserver.go

/kind cleanup
cleanup: refine secretNamespace assignment in Expand, DeleteVolume
Fixes #
```
none
```

cleanup: refine secretNamespace assignment in Expand, DeleteVolume

---

pkg/azurefile/controllerserver.go
pkg/azurefile/controllerserver_test.go

/kind test
fix: disallow disableDeleteRetentionPolicy on Standard account type
Fixes #
```
fix: disallow disableDeleteRetentionPolicy on Standard account type
```

fix: disallow disableDeleteRetentionPolicy on Standard account type

---

test/e2e/dynamic_provisioning_test.go
test/e2e/suite_test.go

test: skip on-prem test on capz windows
Fixes #
```
none
```

test: skip on-prem test on capz windows

---

pkg/azurefile/azurefile.go
pkg/azurefile/controllerserver.go

/kind cleanup
chore: rename metrics columns
Fixes #
<details>
```
"Observed Request Latency" latency_seconds=0.970935113 request="azurefile_csi_driver_controller_create_snapshot" resource_group="kubetest-saz6ew7n" subscription_id="0e46bd28-a80f-4d3a-8200-d9eb8d80cb2e" source="file.csi.azure.com" source_resource_id="kubetest-saz6ew7n#f4708185ceb4945fda7b7c6#pvc-c89c01b1-1c2a-446f-97a6-bc3eeb2cf2cd###azurefile-3086" snapshot_name="snapshot-4821d56e-cf10-42af-82bd-b1b7a1c86081" result_code="succeeded"
"Observed Request Latency" latency_seconds=0.010343372 request="azurefile_csi_driver_controller_delete_snapshot" …
```

chore: rename metrics columns

---

hack/verify-examples.sh
test/e2e/dynamic_provisioning_test.go
test/e2e/pre_provisioning_test.go
test/e2e/suite_test.go
test/e2e/testsuites/dynamically_provisioned_cmd_volume_tester.go
test/e2e/testsuites/dynamically_provisioned_volume_snapshot_tester.go
test/e2e/testsuites/pre_provisioned_existing_credentials_tester.go
test/e2e/testsuites/specs.go
test/e2e/testsuites/testsuites.go

/kind test
test: support Win2022 test on capz
Fixes #
```
none
```

test: support Win2022 test on capz

---

pkg/azurefile/azurefile.go

/kind cleanup
chore: add cloud config logging in driver init
Fixes #
```
none
```

chore: add cloud config logging in driver init

---

pkg/azurefile/nodeserver.go
pkg/azurefile/utils.go
pkg/azurefile/utils_test.go
test/e2e/dynamic_provisioning_test.go

/kind bug
fix: bypass chmod if mounting point permissions are correct
Fixes #
```
none
```

fix: bypass chmod if mounting point permissions are correct

---

docs/driver-parameters.md
pkg/azurefile/azurefile.go
pkg/azurefile/controllerserver.go
pkg/azurefile/nodeserver.go
pkg/azurefile/nodeserver_test.go
pkg/azurefile/utils.go
pkg/azurefile/utils_test.go
test/e2e/dynamic_provisioning_test.go
test/external-e2e/run.sh
test/external-e2e/testdriver-nfs.yaml
vendor/k8s.io/client-go/util/testing/fake_handler.go
vendor/k8s.io/client-go/util/testing/tmpdir.go
vendor/modules.txt

/kind bug
/kind feature
fix: fsgroup setting on vhd disk
feat: add fsGroupChangePolicy for nfs protocol
Fixes #
```
fix: fsgroup setting on vhd disk
feat: add fsGroupChangePolicy for nfs protocol
```

feat: add fsGroupChangePolicy for nfs protocol

---

test/e2e/testsuites/dynamically_provisioned_delete_pod_tester.go
test/e2e/testsuites/dynamically_provisioned_restart_driver_tester.go
test/e2e/testsuites/dynamically_provisioned_statefulset_tester.go
test/e2e/testsuites/testsuites.go

fix
/kind test
test: fix unstable issue for e2e test which checks file content
Fixes #
```
none
```

test: fix unstable e2e tests which check file content

---

docs/driver-parameters.md
pkg/azurefile/utils.go
test/e2e/dynamic_provisioning_test.go
test/external-e2e/run.sh

/kind feature
feat: set fsGroupChangePolicy as OnRootMismatch for nfs by default
This could solve the issue when set group id on a directory recursively costing lots of time
Fixes #
```
feat: set fsGroupChangePolicy as OnRootMismatch for nfs by default
```

feat: set fsGroupChangePolicy as OnRootMismatch for nfs by default

---

deploy/example/storageclass-azurefile-nfs.yaml
docs/driver-parameters.md
pkg/azurefile/azurefile.go
pkg/azurefile/nodeserver.go
pkg/azurefile/utils_test.go
pkg/azurefileplugin/main.go
test/external-e2e/run.sh

/kind feature
feat: add fsGroupChangePolicy None parameter
`fsGroupChangePolicy: None` in storage class could solve nfs volume mount failure issue when there are large num of files inside the volume
Fixes #
```
feat: add fsGroupChangePolicy None parameter
```

feat: add fsGroupChangePolicy None parameter

---

pkg/azurefile/nodeserver.go
test/e2e/dynamic_provisioning_test.go
test/e2e/testsuites/testsuites.go

/kind bug
fix: inline volume mount options passing issue
`file_mode`, `dir_mode` could not be passed with inline volume mountOptions now, this PR would fix this issue.
Fixes #
```
fix: inline volume mount options passing issue
```

fix: inline volume mount options passing issue

---

OWNERS

I would like to help out review azurefile with reviews and new features. 
cc @jsafrane @msau42 @andyzhangx

Add myself as reviewer for azurefile CSI driver

---

docs/driver-parameters.md

doc: mark VHD disk feature as experimental feature
Fixes #
```
none
```
/assign @jsafrane

doc: mark VHD disk feature as experimental feature

---

pkg/azurefile/controllerserver.go
pkg/azurefile/controllerserver_test.go

/kind cleanup
chore: add more logging in ExpandVolume
Fixes #
```
none
```

chore: add more logging in ExpandVolume

---

pkg/azurefile/version.go
pkg/azurefile/version_test.go

/kind cleanup
chore: shorten userAgent
Fixes #
```
none
```

chore: shorten userAgent

---

pkg/azurefileplugin/Dockerfile
test/sanity/run-tests-all-clouds.sh

/kind test
chore: upgrade base image to debian-base:bullseye-v1.4.0
Fixes #
```
none
```

chore: upgrade base image to debian-base:bullseye-v1.4.0

---

Makefile

chore: switch master branch to use v1.21.0
Fixes #
<details>
```
git checkout -b switch-master-1.21.0
sed -i 's/1.20.0/1.21.0/g' Makefile
$git_commit
git push origin switch-master-1.21.0
```
</details>
```
none
```

chore: switch master branch to use v1.21.0

---

pkg/azurefile/controllerserver.go
pkg/azurefile/controllerserver_test.go

/kind bug
fix: don't return error if request size is smaller than existing quota
Fixes #1057
```
fix: don't return error if request size is smaller than existing quota
```

fix: don't return error if request size is smaller than existing quota

---

.github/workflows/codespell.yml
pkg/azurefile/utils_test.go

/kind cleanup
Fixing codespell test errors
Fixes #
```
none
```

fix: fixing codespell errors

---

pkg/azurefile/controllerserver_test.go

/kind test
add controllerserver.go unit test
Fixes #1059
```
none
```

test: add controllerserver.go unit test

---

pkg/azurefile/azurefile_client_test.go
pkg/azurefile/azurefile_test.go
pkg/azurefile/nodeserver_test.go

/kind test
add nodeserver.go, azurefile.go and azurefile_client.go unit test
Fixes #1059
```
none
```

test: add nodeserver.go, azurefile.go and azurefile_client.go unit test

---

deploy/example/nfs/README.md
deploy/example/pv-azurefile-nfs.yaml
deploy/example/storageclass-azurefile-nfs.yaml

doc: remove nconnect mount option, `nconnect=8` mount option would lead to blob nfs list directory failure
Fixes #
```
none
```

doc: remove nconnect mount option

---

Makefile

chore: switch master branch version
Fixes #
```
none
```

chore: switch master branch version

---

pkg/azurefile/azurefile.go

/kind cleanup
This PR also refines the log printing in getAccountKeyFromSecret process](chore: refine the log printing in getAccountKeyFromSecret process)
Fixes #
```
none
```

chore: refine the log printing in getAccountKeyFromSecret process

---

charts/index.yaml

/kind bug
fix: chart index file
Fixes #1080
```
fix: chart index file
```

fix: chart index file

---

go.mod
go.sum
vendor/golang.org/x/net/html/render.go
vendor/golang.org/x/net/html/token.go
vendor/golang.org/x/net/http2/frame.go
vendor/golang.org/x/net/http2/hpack/encode.go
vendor/golang.org/x/net/http2/hpack/hpack.go
vendor/golang.org/x/net/http2/http2.go
vendor/golang.org/x/net/http2/server.go
vendor/golang.org/x/net/http2/transport.go
vendor/golang.org/x/sys/unix/syscall_aix.go
vendor/modules.txt

/kind bug
fix: CVE-2022-27664
```
test/azurefile-csi:latest (debian 11.5)
=======================================
Total: 0 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 0)
azurefileplugin (gobinary)
==========================
Total: 1 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 1, CRITICAL: 0)
┌──────────────────┬────────────────┬──────────┬────────────────────────────────────┬───────────────────────────────────┬─────────────────────────────────────────────────────────────┐
│     Library      │ Vulnerability  │ Severity │         Installed Version          │           Fixed Version           │                            Title                            │
├──────────────────┼────────────────┼──────────┼───────────────────── …
```

fix: CVE-2022-27664

---

test/sanity/run-test.sh
test/sanity/run-tests-all-clouds.sh

/kind test
test: run sanity test on csi-test v5.0.0
Fixes #
```
test: run sanity test on csi-test v5.0.0
```

test: run sanity test on csi-test v5.0.0

---

CONTRIBUTING.md

Signed-off-by: amolmote <amolmote201@gmail.com>
Fixes #1088

Updated CONTRIBUTION.md file

---

hack/verify-all.sh
hack/verify-helm-chart-index.sh

/kind feature
feat: add helm repo install check
Fixes #
```
none
```

feat: add helm repo install check

---

pkg/azurefileplugin/Dockerfile

/kind feature
chore: upgrade base image debian-base:bullseye-v1.4.2
Fixes #
```
none
```

chore: upgrade base image debian-base:bullseye-v1.4.2

---

pkg/azurefile/azurefile.go
pkg/azurefile/controllerserver.go
pkg/azurefile/controllerserver_test.go

/kind feature
chore: refine data plane API cache of https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/1082
Fixes #
```
chore: refine data plane API cache
```

chore: refine data plane API cache

---

pkg/azurefile/controllerserver.go

/kind cleanup
cleanup: remove unnecessary tp nil check
Fixes #
```
cleanup: remove unnecessary tp nil check
```

cleanup: remove unnecessary tp nil check

---

pkg/azurefile/azure.go
pkg/azurefile/azure_test.go
pkg/azurefile/azurefile.go
pkg/azurefileplugin/main.go

/kind bug
fix: increase api qps for azurefile kubeclient
- original default values
```
--kube-api-qps <num>: The number of requests per second sent by a Kubernetes client to the Kubernetes API server. Defaults to 5.0.
--kube-api-burst <num>: The number of requests to the Kubernetes API server, exceeding the QPS, that can be sent at any given time. Defaults to 10.
```
Fixes #
```
fix: increase api qps for azurefile kubeclient
```

fix: increase api qps for azurefile kubeclient

---

pkg/azurefile/controllerserver.go
pkg/azurefile/controllerserver_test.go

/kind feature
feat: add useDataPlaneAPI in snapshot storage class
Fixes #
```
feat: add useDataPlaneAPI in snapshot storage class
```

feat: add useDataPlaneAPI in snapshot storage class

---

go.mod
go.sum
vendor/golang.org/x/net/http2/hpack/encode.go
vendor/golang.org/x/net/http2/server.go
vendor/golang.org/x/net/http2/transport.go
vendor/golang.org/x/sys/windows/syscall_windows.go
vendor/golang.org/x/sys/windows/zsyscall_windows.go
vendor/modules.txt

/kind bug
fix: CVE-2022-41717
```
──────────────────┬────────────────┬──────────┬───────────────────┬───────────────┬──────────────────────────────────────────────────────────────┐
│     Library      │ Vulnerability  │ Severity │ Installed Version │ Fixed Version │                            Title                             │
├──────────────────┼────────────────┼──────────┼───────────────────┼───────────────┼──────────────────────────────────────────────────────────────┤
│ golang.org/x/net │ CVE-2022-[41](https://github.com/kubernetes-sigs/azurefile-csi-driver/actions/runs/3658032645/jobs/6182309696#step:6:42)717 │ UNKNOWN  │ v0.2.0            │ 0.4.0         │ An attacker can cause excessive memory growth in a Go …
```

fix: CVE-2022-41717

---

go.mod
pkg/azurefile/controllerserver.go
pkg/azurefile/controllerserver_test.go
test/e2e/testsuites/testsuites.go
test/utils/azure/azure_helpers.go

/kind cleanup
Use k8s utils pointer instead of Azure autorest/to
- to.FooPtr becomes pointer.Foo
- to.Foo becomes pointer.FooDeref with an appropriate default
- to.StringSlicePtr becomes &
This is related to https://github.com/kubernetes/kubernetes/issues/112431 (but doesn’t fix it).
```
none
```

cleanup: Use k8s utils pointer instead of Azure autorest/to

---

pkg/azurefile/azure_common_linux.go
pkg/azurefile/controllerserver.go

/kind cleanup
chore: refine logging
Fixes #
```
none
```

chore: refine logging

---

deploy/example/nginx-pod-azurefile-inline-volume.yaml
deploy/example/pv-azurefile-csi.yaml
deploy/example/pv-azurefile-nfs.yaml
docs/intree-static-example.md

Improves a comment for volumeHandle and adds the `nosharesock` mount option for all `PersistentVolume` examples.
This is done to better support the situation where the creator of a PersistentVolume wants to use the same Azure Files share multiple times.
Fixes #1137
```
none
```

docs: recommend the use of the nosharesock mount option, and clearify how volumeHandle should be used.

---

test/e2e/dynamic_provisioning_test.go
test/e2e/testsuites/dynamically_provisioned_restart_driver_tester.go
test/e2e/testsuites/dynamically_provisioned_volume_unmount_tester.go
test/e2e/testsuites/specs.go
test/e2e/testsuites/testsuites.go

/kind test
test: add unmount volume test
Fixes #
```
test: add unmount volume test
```

test: add unmount volume test

---

pkg/azurefile/azure_common_darwin.go
pkg/azurefile/azure_common_linux.go
pkg/azurefile/azure_common_windows.go
pkg/azurefile/nodeserver.go
pkg/mounter/safe_mounter_windows.go

/kind cleanup
cleanup: remove useless functions
Fixes #
```
none
```

cleanup: remove useless functions

---

README.md
docs/install-azurefile-csi-driver.md

doc: update install doc
Fixes #
```
none
```

doc: update install doc

---

pkg/azurefile/azure_common_linux.go

/kind bug
fix: target is busy unmount failure
This PR would try to do lazy unmount when common unmount failed with `target is busy` error, we have received lots of such issues, in the before, only workaround is do lazy umount manually on the node, this PR tries to mitigate such issue automatically.
Fixes #1149
```
fix: target is busy unmount failure
```

fix: target is busy unmount failure

---

pkg/azurefile/azure_common_linux.go

/kind cleanup
cleanup: fix umount failure logging
Fixes #
```
none
```

cleanup: fix umount failure logging

---

deploy/example/pv-azurefile-csi.yaml
deploy/example/pv-azurefile-nfs.yaml
docs/driver-parameters.md

doc: refine doc
Fixes #
```
none
```

doc: refine doc

---

README.md

Fixes URL to azure-files-csi driver documentation
Fixes #
```
none
```
```
none
```

doc: Fix URL to azure-files-csi driver doc in README.md

---

deploy/csi-azurefile-driver.yaml
deploy/v1.21.0/csi-azurefile-driver.yaml
deploy/v1.22.0/csi-azurefile-driver.yaml
deploy/v1.23.0/csi-azurefile-driver.yaml
deploy/v1.24.0/csi-azurefile-driver.yaml
deploy/v1.25.0/csi-azurefile-driver.yaml
deploy/v1.25.1/csi-azurefile-driver.yaml

/kind bug
fix: incorrect driver version in CSIDriver
Fixes #
```
fix: incorrect driver version in CSIDriver
```

fix: incorrect driver version in CSIDriver

---

docs/driver-parameters.md
pkg/azurefile/azurefile.go
pkg/azurefile/controllerserver.go
test/e2e/dynamic_provisioning_test.go

/kind feature
feat: add support for SMB Multi-channels in premium account creation
Fixes #1103
```
feat: add support for SMB Multi-channels in premium account creation
```

feat: add support for SMB Multi-channels in premium account creation

---

pkg/azurefileplugin/Dockerfile

fix: switch base image to fix CVEs

---

pkg/azurefile/azure_common_linux.go
pkg/mounter/safe_mounter_unix.go

/kind bug
fix: remove forceUmount and lazyUmount
This PR is reverting https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/1146 and https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/1158 since “umount -f -l” (linux force umount & lazy umount) would make the smb mount dir broken(pointing to an invalid device) when there is heavy read write on the smb mount dir to be unmounted.
Fixes #
```
fix: remove forceUmount and lazyUmount
```

fix: remove forceUmount and lazyUmount

---

hack/verify-gomod.sh

/kind test
test: add "go list" check
Fixes #
```
none
```

test: add "go list" check

---

.github/workflows/static.yaml

/kind test
test: enable dupl golint
Fixes #
```
none
```

test: enable dupl golint

---

Makefile

/kind cleanup
Windows SAC releases (2004, 20H2) have been out-of-support for a while now so we shouldn't build contianer images for those platforms
Also, Microsoft has started publishing a `ltsc2019` tag for mcr.microsoft.com/windows/nanoserver in addition to `1809` so I switched to using that for consistency.
similar change as https://github.com/kubernetes-sigs/cloud-provider-azure/pull/3555
Fixes #
```
none
```

cleanup: remove windows 20H2 image build

---

test/external-e2e/testdriver-nfs.yaml
test/external-e2e/testdriver-smb.yaml

/kind test
test: add external stress test
Fixes #
```
none
```

test: add external stress test

---

docs/driver-parameters.md

doc: refine subcriptionID parameter doc
Fixes #1208
```
none
```

doc: refine subcriptionID parameter doc

---

.github/workflows/static.yaml
pkg/azurefile/nodeserver.go

tes: fix golint action failure
Fixes #
```
none
```

tes: fix golint action failure

---

test/utils/restart_driver_daemonset.sh

test: fix restart_driver_daemonset script
Fixes #
```
none
```

test: fix restart_driver_daemonset script

---

deploy/example/nfs/README.md
deploy/example/pv-azurefile-nfs.yaml
deploy/example/storageclass-azurefile-nfs.yaml
test/e2e/dynamic_provisioning_test.go

doc: add nconnect mount options in NFSv4.1 example
nconnect mount option is GA on Azure File NFSv4.1 now
Fixes #
```
none
```

doc: add nconnect mount options in NFSv4.1 example

---

pkg/azurefile/azure_test.go
pkg/azurefile/azurefile_test.go
pkg/azurefile/nodeserver.go
test/utils/credentials/credentials.go
test/utils/credentials/credentials_test.go

/kind cleanup
Replace the deprecated ioutil method, Because they are no longer recommended in go version 1.16 or 1.17
Fixes #
```
none
```

cleanup: replace deprecated ioutil method

---

.github/dependabot.yaml

/kind test
test: add dependabot
Fixes #
```
none
```

test: add dependabot

---

docs/workload-identity.md

chore: refine workload identity docs.

---

pkg/azurefile/azurefile.go
pkg/azurefile/azurefile_test.go
pkg/azurefile/nodeserver.go
pkg/azurefileplugin/main.go

/kind bug
fix: add closetimeo=0 option to fix data sync issue on Ubuntu 22.04
Fixes #
```
fix: add closetimeo=0 option to fix data sync issue on Ubuntu 22.04
```

fix: add closetimeo=0 option to fix data sync issue on Ubuntu 22.04

---

pkg/azurefile/azurefile.go
pkg/azurefile/azurefile_test.go

/kind bug
fix: default actimeo option should respect acregmax and acdirmax, if acregmax or acdirmax is set, actimeo should not be appended by default
Fixes #
```
fix: default actimeo option should respect acregmax and acdirmax
```

fix: default actimeo option should respect acregmax and acdirmax

---

Makefile
hack/release-image.sh

/kind cleanup
chore: refine windows host process container image build
Fixes #
```
none
```

chore: refine windows host process container image build

---

.github/dependabot.yaml

/kind test
Build: add dependabot job for dockerfile updates.
Fixes #
```
none
```

Build: add dependabot job for dockerfile updates.

---

pkg/os/filesystem/filesystem.go
pkg/os/smb/smb.go
pkg/util/util.go

/kind feature
chore: update windows host process lib
copied from https://github.com/kubernetes-csi/csi-proxy/blob/master/pkg/os/filesystem/api.go
Fixes #
```
none
```

chore: update windows host process lib

---

pkg/os/filesystem/filesystem.go

/kind cleanup
cleanup: remove unnecessary path validation on hpc deployment
Fixes #
```
none
```

cleanup: remove unnecessary path validation on hpc deployment

---

deploy/example/pv-azurefile-csi.yaml

doc: remove unused resourceGroup field when secret is specified
Fixes #1266
```
none
```

doc: remove unused resourceGroup field when secret is specified

---

Makefile
hack/release-image.sh

/kind bug
fix: hpc image build on AKS
Fixes #
```
none
```

fix: hpc image build on AKS

---

docs/driver-parameters.md

Doc: fix typo for storeAccountKey
Fixes #
```
none
```

Doc: fix typo for storeAccountKey

---

charts/README.md
deploy/csi-azurefile-node-windows-hostprocess.yaml
deploy/csi-azurefile-node-windows.yaml

/kind bug
fix: use InClusterConfig by default on Windows node
Fixes #
```
fix: use InClusterConfig by default on Windows node
```

fix: use InClusterConfig by default on Windows node

---

pkg/azurefile/azurefile.go
pkg/azurefile/controllerserver.go

/kind bug
fix: stop resize file share when account limit is exceeded
cherrypick of https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/1345
Fixes #
```
fix: stop resize file share when account limit is exceeded
```

[release-1.24] fix: stop resize file share when account limit is exceeded

---

pkg/azurefile/azurefile.go
pkg/azurefile/controllerserver.go

/kind bug
fix: stop resize file share when account limit is exceeded
cherrypick of https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/1345
Fixes #
```
fix: stop resize file share when account limit is exceeded
```

[release-1.26] fix: stop resize file share when account limit is exceeded

---

pkg/azurefile/azurefile.go
pkg/azurefile/controllerserver.go

/kind bug
fix: stop resize file share when account limit is exceeded
cherrypick of https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/1345
Fixes #
```
fix: stop resize file share when account limit is exceeded
```

[release-1.27] fix: stop resize file share when account limit is exceeded

---

test/e2e/dynamic_provisioning_test.go

test: run one e2e test using smb protocol
Fixes #
```
none
```

test: run one e2e test using smb protocol

---

docs/driver-parameters.md
go.mod
pkg/azurefile/azurefile.go
pkg/azurefile/azurefile_test.go
pkg/azurefile/controllerserver.go
pkg/azurefile/controllerserver_test.go
test/e2e/dynamic_provisioning_test.go

/kind feature
feat: add accountQuota parameter
cherrypick of https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/1362
Fixes #
```
feat: add accountQuota parameter
```

[release-1.28] feat: add accountQuota parameter

---

docs/driver-parameters.md
go.mod
pkg/azurefile/azurefile.go
pkg/azurefile/azurefile_test.go
pkg/azurefile/controllerserver.go
pkg/azurefile/controllerserver_test.go
test/e2e/dynamic_provisioning_test.go

/kind feature
feat: add accountQuota parameter
cherrypick of https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/1362
Fixes #
```
feat: add accountQuota parameter
```

 [release-1.27] feat: add accountQuota parameter

---

go.mod
pkg/azurefile/azure_common_darwin.go
pkg/azurefile/azure_common_linux.go
pkg/azurefile/azure_common_windows.go
pkg/azurefile/nodeserver.go
pkg/azurefile/nodeserver_test.go

/kind bug
fix: incorrect volume usage on Windows node with host process deployment
cherrypick of https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/1337
Fixes #
```
fix: incorrect volume usage on Windows node with host process deployment
```

[release-1.28] fix: incorrect volume usage on Windows node with host process deployment

---

pkg/azurefile/azurefile_test.go
pkg/azurefile/controllerserver_test.go

test: fix test failure on MacOS
Fixes #
```
none
```

test: fix test failure on MacOS

---

pkg/azurefile/azurefile.go
pkg/azurefile/controllerserver.go
pkg/azurefileplugin/main.go

/kind bug
fix: delay removing skipMatchingTag when account is full
cherrypick of https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/1409
Fixes #
```
none
```

[release-1.24] fix: delay removing skipMatchingTag when account is full

---

pkg/azurefile/azurefile.go
pkg/azurefile/controllerserver.go
pkg/azurefileplugin/main.go

/kind bug
fix: delay removing skipMatchingTag when account is full
cherrypick of https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/1409
Fixes #
```
none
```

[release-1.27] fix: delay removing skipMatchingTag when account is full

---

pkg/azurefile/azurefile.go
pkg/azurefile/controllerserver.go
pkg/azurefileplugin/main.go

/kind bug
fix: delay removing skipMatchingTag when account is full
cherrypick of https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/1409
Fixes #
```
none
```

[release-1.26] fix: delay removing skipMatchingTag when account is full

---

pkg/azurefile/azurefile.go
pkg/azurefile/nodeserver.go
pkg/azurefileplugin/main.go

/kind cleanup
chore: provide a driver flag to print volume stats call with log level 2
cherrypick of https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/1449
Fixes #
```
none
```

[release-1.27] chore: provide a driver flag to print volume stats call with log level 2

---

pkg/azurefile/azurefile.go
pkg/azurefile/nodeserver.go
pkg/azurefileplugin/main.go

/kind cleanup
chore: provide a driver flag to print volume stats call with log level 2
cherrypick of https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/1449
Fixes #
```
none
```

[releaes-1.26] chore: provide a driver flag to print volume stats call with log level 2

---

pkg/azurefile/azurefile.go

/kind cleanup
cleanup: remove ControllerPublishVolume capability since this CSI driver does not need it
Fixes #1467
```
none
```

cleanup: remove ControllerPublishVolume capability

---

pkg/azurefile/controllerserver.go

/kind bug
fix: refine create volume metrics
cherrypick of https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/1464
Fixes #
```
fix: refine create volume metrics
```

[release-1.29] fix: refine create volume metrics

---

deploy/example/azure.json
docs/csi-debug.md
pkg/azurefile/controllerserver.go
test/e2e/driver/azurefile_driver.go

doc: fix typos
Fixes #
```
none
```

[release-1.28] doc: fix typos

---

test/e2e/dynamic_provisioning_test.go
test/e2e/suite_test.go
test/e2e/testsuites/dynamically_provisioned_volume_snapshot_tester.go

/kind test
test: add nfs snapshot e2e test
Fixes #
```
none
```

test: add nfs snapshot e2e test

---

go.mod
hack/verify-gomod.sh
vendor/modules.txt

cleanup: fix k8s.io/endpointslice dependency
Fixes #
```
none
```

cleanup: fix k8s.io/endpointslice dependency

---

pkg/azurefile/controllerserver.go

/kind bug
fix volumesnapshot restoresize bug
Fixes #
volumesnapshot always get 100Gi in RESTORESIZE before, it is because set `defaultAzureFileQuota` in using management api `CreateSnapshot` func, fix this bug using volumesource size.
test:
NAME                          READYTOUSE   SOURCEPVC       SOURCESNAPSHOTCONTENT   RESTORESIZE   SNAPSHOTCLASS       SNAPSHOTCONTENT                                    CREATIONTIME   AGE
azurefile-volume-snapshot     true         pvc-azurefile                           200Gi         csi-azurefile-vsc   snapcontent-379d8f28-6aab-4946-96d3-c88e496d95e0   2m1s           2m1s
``` …
```

fix: incorrect volumesnapshot size

---

pkg/azurefileplugin/Dockerfile

/kind feature
feat: switch to bookworm debian base image
bookworm debian base image has fewer CVEs compared to bulleye debian base image
```
andyzhangx/azurefile-csi:v1.30.0 (debian 12.2)  # bookworm 
==============================================
Total: 97 (UNKNOWN: 0, LOW: 72, MEDIUM: 14, HIGH: 10, CRITICAL: 1)
andyzhangx/azurefile-csi:v1.30.0 (debian 11.8) # bulleye
==============================================
Total: 210 (UNKNOWN: 0, LOW: 104, MEDIUM: 47, HIGH: 50, CRITICAL: 9)
```
Fixes #
```
feat: switch to bookworm debian base image
```

feat: switch to bookworm debian base image

---

test/e2e/dynamic_provisioning_test.go

/kind test
test: improve large size volume cloning e2e test
Fixes #
large size volume cloning e2e test is not stable because of `dd` command to create a 99G size file, use `head` command to improve it
```
none
```

test: improve large size volume cloning e2e test

---

deploy/example/nfs/README.md
deploy/example/storageclass-azurefile-nfs.yaml
test/e2e/dynamic_provisioning_test.go

doc: add actimeo, noresvport mount options in the doc
Fixes #
```
none
```

doc: add actimeo, noresvport mount options in the doc

---

.github/workflows/static.yaml
.golangci.yml
pkg/azurefile/azure_common_linux.go
pkg/azurefile/controllerserver.go
pkg/azurefile/fake_mounter.go
pkg/azurefile/identityserver.go
pkg/azurefile/nodeserver.go
pkg/azurefile/utils.go
pkg/azurefile/utils_test.go
pkg/azurefileplugin/main.go
pkg/csi-common/server_test.go
test/e2e/driver/azurefile_driver.go
test/e2e/testsuites/dynamically_provisioned_inline_volume.go
test/e2e/testsuites/specs.go
test/utils/azure/azure_helpers.go

/kind test
[release1.26] test: upgrade golangci/golangci-lint-action to v1.54
Fixes #
```
none
```

[release1.26] test: upgrade golangci/golangci-lint-action to v1.54

---

.github/workflows/static.yaml
.golangci.yml
pkg/azurefile/azure_common_linux.go
pkg/azurefile/controllerserver.go
pkg/azurefile/fake_mounter.go
pkg/azurefile/identityserver.go
pkg/azurefile/nodeserver.go
pkg/azurefile/utils.go
pkg/azurefile/utils_test.go
pkg/azurefileplugin/main.go
pkg/csi-common/server_test.go
pkg/mounter/safe_mounter_unix.go
pkg/os/filesystem/filesystem.go
test/e2e/driver/azurefile_driver.go
test/e2e/testsuites/dynamically_provisioned_inline_volume.go
test/e2e/testsuites/specs.go
test/utils/azure/azure_helpers.go

/kind test
[release1.27] test: upgrade golangci/golangci-lint-action to v1.54
Fixes #
```
none
```

[release1.27] test: upgrade golangci/golangci-lint-action to v1.54

---

.github/workflows/static.yaml
.golangci.yml
pkg/azurefile/azure_common_linux.go
pkg/azurefile/azurefile.go
pkg/azurefile/controllerserver.go
pkg/azurefile/controllerserver_test.go
pkg/azurefile/fake_mounter.go
pkg/azurefile/identityserver.go
pkg/azurefile/nodeserver.go
pkg/azurefile/utils.go
pkg/azurefile/utils_test.go
pkg/azurefileplugin/main.go
pkg/csi-common/server_test.go
pkg/mounter/safe_mounter_unix.go
pkg/os/filesystem/filesystem.go
test/e2e/driver/azurefile_driver.go
test/e2e/testsuites/dynamically_provisioned_inline_volume.go
test/e2e/testsuites/specs.go
test/utils/azure/azure_helpers.go

/kind test
[release1.28] test: upgrade golangci/golangci-lint-action to v1.54
Fixes #
```
none
```

[release1.28] test: upgrade golangci/golangci-lint-action to v1.54

---

README.md
deploy/example/cloning/README.md
deploy/example/cloning/nginx-pod-restored-cloning.yaml
deploy/example/cloning/pvc-azurefile-cloning.yaml
hack/verify-yamllint.sh

/kind doc
doc: add volume cloning doc
Fixes #
```
none
```

doc: add volume cloning doc

---

README.md
deploy/example/cloning/README.md
deploy/example/cloning/nginx-pod-restored-cloning.yaml
deploy/example/cloning/pvc-azurefile-cloning.yaml
hack/verify-yamllint.sh

[release-1.29] doc: add volume cloning doc
Fixes #
```
none
```

[release-1.29] doc: add volume cloning doc

---

deploy/example/pv-azurefile-nfs.yaml

doc: add noresvport, actimeo=30 mount option in static nfs pv
Fixes #
```
none
```

doc: add noresvport, actimeo=30 mount option in static nfs pv

---

deploy/example/cloning/nginx-pod-restored-cloning.yaml
deploy/example/nfs/statefulset.yaml
deploy/example/nginx-pod-azurefile-inline-volume.yaml
deploy/example/nginx-pod-azurefile.yaml
deploy/example/pv-azurefile-csi.yaml
deploy/example/pv-azurefile-nfs.yaml
deploy/example/statefulset-nonroot.yaml
deploy/example/statefulset.yaml

doc: fix readOnly setting doc
- following csi.readOnly is not supported in CSI driver
```
csi:
driver: file.csi.azure.com
readOnly: false
```
Fixes #1607
```
none
```

doc: fix readOnly setting doc

---

pkg/mounter/safe_mounter_host_process_windows.go

/kind cleanup
chore: increase windows host deployment driver log level
Fixes #
```
none
```

chore: increase windows host deployment driver log level

---

test/external-e2e/run.sh

/kind test
test: upgrade to ginko/v2 in external e2e tests
Fixes #
```
none
```

test: upgrade to ginko/v2 in external e2e tests

---

deploy/example/cloning/README.md

doc: fix volume cloning doc
Fixes #
```
none
```

doc: fix volume cloning doc

---

pkg/azurefile/azurefile.go
pkg/azurefile/azurefile_options.go
pkg/azurefile/azurefile_options_test.go
pkg/azurefile/azurefile_test.go
pkg/azurefileplugin/main.go
test/e2e/suite_test.go

/kind cleanup
Fixes #
```
none
```

Refactor: move flag option to azurefile package

---

test/sanity/run-test.sh

/kind test
test: always use latest azcopy version in sanity test
Fixes #
```
none
```

test: always use latest azcopy version in sanity test

---

pkg/azurefile/nodeserver.go
pkg/azurefile/utils.go
pkg/azurefile/utils_test.go

/kind bug
fix: mountPermission settting issue due to case insensitive parameter
cherrypick of https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/1648
Fixes #
```
fix: mountPermission settting issue due to case insensitive parameter
```

[release-1.29] fix: mountPermission settting issue due to case insensitive parameter

---

pkg/azurefile/nodeserver.go
pkg/azurefile/utils.go
pkg/azurefile/utils_test.go

/kind bug
fix: mountPermission settting issue due to case insensitive parameter
cherrypick of https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/1648
Fixes #
```
fix: mountPermission settting issue due to case insensitive parameter
```

[release-1.28] fix: mountPermission settting issue due to case insensitive parameter 

---

test/external-e2e/testdriver-nfs.yaml

/kind test
test: enable volumeMountGroup external tests on nfs protocol
Fixes #
```
none
```

test: enable volumeMountGroup external tests on nfs protocol

---

docs/workload-identity-static-pv-mount.md

chore: fix docs for workload identity

---

test/sanity/run-test.sh

/kind test
test: use same azcopy version in sanity test
Fixes #
```
none
```

test: use same azcopy version in sanity test

---

pkg/azurefileplugin/Dockerfile
test/sanity/run-test.sh

/kind feature
feat: upgrade azcopy version to 10.22.2
Fixes #
```
none
```

feat: upgrade azcopy version to 10.22.2 for volume clone feature

---

pkg/azurefileplugin/Dockerfile
test/sanity/run-test.sh

/kind feature
feat: upgrade azcopy version to 10.22.2 for volume clone feature
cherrypick of https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/1669
Fixes #
```
none
```

[release-1.28] feat: upgrade azcopy version to 10.22.2 for volume clone feature

---

pkg/azurefileplugin/Dockerfile
test/sanity/run-test.sh

/kind feature
feat: upgrade azcopy version to 10.22.2 for volume clone feature
cherrypick of https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/1669
Fixes #
```
none
```

[release-1.29] feat: upgrade azcopy version to 10.22.2 for volume clone feature

---

pkg/azurefile/nodeserver_test.go
test/sanity/run-test.sh

/kind test
test: fix sanity test failure
Fixes #
```
none
```

test: fix sanity test failure

---

pkg/azurefile/azurefile.go
pkg/azurefile/azurefile_test.go
pkg/azurefile/nodeserver_test.go
pkg/azurefileplugin/main.go

/kind bug
fix: increase volume cloning timeout
cherrypick of https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/1677
Fixes #
```
none
```

[release-1.29] fix: increase volume cloning timeout

---

pkg/azurefile/nodeserver_test.go

test: fix windows ut failure
Fixes #
```
none
```

[release-1.28] test: fix windows ut failure

---

pkg/azurefile/azurefile.go
pkg/azurefile/controllerserver.go
pkg/azurefile/utils.go
pkg/azurefile/utils_test.go

/kind feature
chore: respect RetryAfter in throttling condition
Fixes #
```
none
```

chore: respect RetryAfter in throttling condition

---

pkg/azurefile/azurefile.go
pkg/azurefile/azurefile_dataplane_client.go
pkg/azurefile/azurefile_dataplane_client_test.go
pkg/azurefile/azurefile_test.go
pkg/azurefile/controllerserver.go
pkg/azurefile/nodeserver.go

/kind bug
fix: panic when controller does not have cloud config
Fixes #1707
```
fix: panic when controller does not have cloud config
```

fix: panic when controller does not have cloud config

---

pkg/azurefile/azurefile.go
pkg/azurefile/azurefile_test.go
pkg/azurefile/controllerserver.go
pkg/azurefile/nodeserver.go

fix: panic when controller does not have cloud config
cherrypick of https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/1710
Fixes #
```
fix: panic when controller does not have cloud config
```

[release-1.29] fix: panic when controller does not have cloud config

---

deploy/csi-azurefile-driver.yaml

chore: Update csi-azurefile-driver.yaml

---

docs/driver-parameters.md
pkg/azurefile/controllerserver.go
pkg/azurefile/controllerserver_test.go

/kind feature
feat: allow multiple subnets in updating service endpoints
Fixes #1606
```
feat: allow multiple subnets in updating service endpoints
```

feat: allow multiple subnets in updating service endpoints

---

test/e2e/dynamic_provisioning_test.go

test: remove vhd disk test
Fixes #
```
none
```

[release-1.29] test: remove vhd disk test

---

test/e2e/dynamic_provisioning_test.go

test: remove vhd disk test
Fixes #
```
none
```

[release-1.30] test: remove vhd disk test

---

pkg/azurefile/azurefile.go
pkg/azurefile/controllerserver.go
pkg/azurefile/controllerserver_test.go

/kind bug
fix: nfs protocol does not support standard account, this PR returns error with such combination
Fixes #1480
```
fix: nfs protocol does not support standard account
```

fix: nfs protocol does not support standard account

---

pkg/azurefileplugin/Dockerfile
test/sanity/run-test.sh

/kind feature
feat: upgrade azcopy version to 10.23.0 for volume clone feature
```
HTTP/1.1 301 Moved Permanently
Content-Length: 0
Server: Kestrel
Location: https://azcopyvnext.azureedge.net/releases/release-10.23.0-20240129/azcopy_linux_amd64_10.23.0.tar.gz
```
Fixes #
```
feat: upgrade azcopy version to 10.23.0 for volume clone feature
```

feat: upgrade azcopy version to 10.23.0 for volume clone feature

---

pkg/azurefileplugin/Dockerfile
test/sanity/run-test.sh

/kind feature
feat: upgrade azcopy version to 10.23.0 for volume clone feature
cherrypick of https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/1756
Fixes #
```
none
```

[release-1.28] feat: upgrade azcopy version to 10.23.0 for volume clone feature

---

pkg/azurefile/azurefile.go
pkg/azurefile/nodeserver.go
pkg/util/util.go
pkg/util/util_test.go

/kind bug
fix: mount stuck issue
Fixes #
```
fix: mount stuck issue
```

fix: mount stuck issue

---

pkg/azurefile/azurefile.go
pkg/azurefile/controllerserver.go
pkg/azurefile/controllerserver_test.go

/kind cleanup
chore: refine sastoken cache
Fixes #
```
none
```

chore: refine sastoken cache

---

pkg/csi-common/utils.go
pkg/csi-common/utils_test.go

/kind cleanup
fix: strip service account token to reduce security risk
Fixes #
```
fix: strip service account token to reduce security risk
```

fix: strip service account token

---

pkg/azurefile/azurefile.go

/kind bug
fix: panic when cloud config is not set
Fixes #1790
```
fix: panic when cloud config is not set
```

fix: panic when cloud config is not set

---

go.mod
go.sum
pkg/azurefile/controllerserver.go
vendor/github.com/Azure/azure-sdk-for-go/sdk/storage/azfile/directory/client.go
vendor/github.com/Azure/azure-sdk-for-go/sdk/storage/azfile/file/client.go
vendor/github.com/Azure/azure-sdk-for-go/sdk/storage/azfile/internal/exported/version.go
vendor/github.com/Azure/azure-sdk-for-go/sdk/storage/azfile/sas/query_params.go
vendor/github.com/Azure/azure-sdk-for-go/sdk/storage/azfile/service/client.go
vendor/github.com/Azure/azure-sdk-for-go/sdk/storage/azfile/share/client.go
vendor/modules.txt

/kind bug
fix: allow http auth in volume clone
Fixes #
```
fix: allow http auth in volume clone
```

fix: allow http auth in volume clone

---

pkg/azurefile/azure_common_darwin.go
pkg/azurefile/azure_common_linux.go
pkg/azurefile/azure_common_windows.go
pkg/azurefile/azurefile.go
pkg/azurefile/azurefile_options.go
pkg/azurefile/nodeserver.go
pkg/mounter/safe_mounter_host_process_windows.go
pkg/mounter/safe_mounter_v1beta_windows.go
pkg/os/smb/smb.go
pkg/os/smb/smb_test.go

/kind bug
fix: remove SMBGlobalMapping on Windows node during volume unmount
Fixes #1830
```
fix: remove SMBGlobalMapping on Windows node
```

fix: remove SMBGlobalMapping on Windows node

---

deploy/example/snapshot/README.md
deploy/example/snapshot/nginx-pod-restored-snapshot.yaml

add smb restore snapshot doc
Fixes #
```
none
```

doc: add smb restore snapshot doc

---

deploy/example/pv-azurefile-csi.yaml
deploy/example/pv-azurefile-nfs.yaml

doc: refine volumeHandle doc
Fixes #1928
```
none
```

doc: refine volumeHandle doc

---

pkg/mounter/safe_mounter_host_process_windows.go
pkg/mounter/safe_mounter_windows.go
pkg/os/smb/smb.go
pkg/os/smb/smb_test.go

/kind bug
fix: refine GetRemoteServerFromTarget on Windows with cache optimization
Fixes #1925
```
fix: refine GetRemoteServerFromTarget on Windows with cache optimization
```

fix: refine GetRemoteServerFromTarget on Windows with cache optimization

---

pkg/os/smb/smb.go
pkg/util/util.go

/kind bug
cherrypick of https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/1934
Fixes #
```
fix: refine GetRemoteServerFromTarget on Windows with cache optimization
```

[release-1.28] fix: refine GetRemoteServerFromTarget on Windows with cache optimization

---

pkg/azurefile/nodeserver.go

/kind cleanup
cleanup: logs refine
Fixes #
```
none
```

cleanup: logs refine

---

pkg/azurefile/nodeserver.go

/kind cleanup
cleanup: logs refine
Fixes #
```
none
```

cleanup: refine logs

---

test/e2e/dynamic_provisioning_test.go

/kind test
test: add allowSharedKeyAccess e2e test
Fixes #
```
none
```

test: add allowSharedKeyAccess e2e test

---

pkg/azurefile/controllerserver.go
pkg/azurefile/controllerserver_test.go

/kind feature
feat: add metadata tag on the storage account created by the driver
Fixes #
test result:
```
none
```

feat: add metadata tag on the storage account created by the driver

---

deploy/example/e2e_usage.md
deploy/example/largeFileShares/storageclass-azurefile-largefileshares.yaml
deploy/example/pv-azurefile-csi.yaml
deploy/example/resize/README.md
deploy/example/storageclass-azurefile-csi.yaml
deploy/example/storageclass-azurefile-existing-share.yaml
deploy/example/storageclass-azurefile-large-scale.yaml
deploy/example/storageclass-azurefile-secret.yaml

doc: add nobrl mount option
Fixes #
```
none
```

doc: add nobrl mount option

---

docs/driver-parameters.md
pkg/azurefile/azurefile.go
pkg/azurefile/controllerserver.go
pkg/azurefile/controllerserver_test.go

/kind feature
[release-1.28] feat: add allowSharedKeyAccess parameter
cherry-pick for https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/1972
Fixes #
```
none
```

[release-1.28] feat: add allowSharedKeyAccess parameter

---

pkg/azurefile/azurefile.go
pkg/azurefile/controllerserver.go
pkg/azurefile/controllerserver_test.go
test/e2e/dynamic_provisioning_test.go
test/e2e/testsuites/dynamically_provisioned_volume_cloning_tester.go

/kind bug
fix: set the correct destination account name for copy volume if storageAccount is specified in storage class
Fixes #
```
none
```

fix: set the correct destination account name for copy volume if storageAccount is specified in storage class

---

pkg/azurefile/controllerserver.go

/kind bug
fix: only last subnet is set in account ACL created by driver
Fixes #
```
fix: only last subnet is set in account ACL created by driver
```

fix: only last subnet is set in account ACL created by driver

---

pkg/azurefile/azurefile.go
pkg/azurefile/controllerserver.go
pkg/azurefile/controllerserver_test.go
pkg/util/util.go
pkg/util/util_test.go
test/e2e/dynamic_provisioning_test.go
test/e2e/testsuites/dynamically_provisioned_volume_cloning_tester.go

/kind bug
[release-1.29] fix: set the correct destination account name for copy volume if storageAccount is specified in storage class
cherry-pick for https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/2003
Fixes #
```
none
```

[release-1.29] fix: set the correct destination account name for copy volume if storageAccount is specified in storage class

---

go.mod
go.sum
vendor/modules.txt
vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_storageaccount.go

/kind bug
fix: VirtualNetworkRule match issue during account search
cherrypick of https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/2036
Fixes #
```
fix: VirtualNetworkRule match issue during account search
```

[release-1.30] fix: VirtualNetworkRule match issue during account search

---

pkg/azurefile/controllerserver.go

/kind bug
[release-1.28] fix: incorrect snapshot size with default 100Gi
cherry-pick for https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/2040
Fixes #
```
none
```

[release-1.28] fix: incorrect snapshot size with default 100Gi

---

pkg/util/util.go
test/sanity/sanity_test.go
test/utils/azure/azure_helpers.go

test: don't return error when deleting rg failed in sanity test
Fixes #
```
none
```

test: don't return error when deleting rg failed in sanity test

---

test/sanity/sanity_test.go
test/utils/azure/azure_helpers.go

test: don't return error when deleting rg failed in sanity test
cherrypick of https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/2071
Fixes #
```
none
```

[release-1.28] test: don't return error when deleting rg failed in sanity test

---

pkg/util/util.go
test/sanity/sanity_test.go
test/utils/azure/azure_helpers.go

test: don't return error when deleting rg failed in sanity test
cherrypick of https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/2071
Fixes #
```
none
```

[release-1.29] test: don't return error when deleting rg failed in sanity test

---

Makefile

test: increase sanity test timeout as 30min
Fixes #
```
none
```

test: increase sanity test timeout as 30min

---

pkg/azurefile/controllerserver.go

/kind bug
fix: azcopy copy command fallback log
Fixes #
```
none
```

fix: azcopy copy command fallback log

---

pkg/azurefile/azure.go
pkg/azurefile/azure_test.go
pkg/azurefile/controllerserver.go
pkg/azurefile/controllerserver_test.go
test/e2e/testsuites/testsuites.go
test/utils/azure/azure_helpers.go

chore: Replace deprecated k8s.io/utils/pointer with k8s.io/utils/ptr

---

pkg/azurefileplugin/Dockerfile

/kind feature
chore: upgrade to debian-base:bookworm-v1.0.4 base image
Fixes #
```
none
```

chore: upgrade to debian-base:bookworm-v1.0.4 base image

---

deploy/example/e2e_usage.md

doc: update inline volume doc
Fixes #2098
```
none
```

doc: update inline volume doc

---

pkg/azurefile/azurefile.go
pkg/azurefile/controllerserver.go
pkg/azurefile/controllerserver_test.go

/kind cleanup
cleanup: refactor fallback to sas token on azcopy copy command
Fixes #
```
none
```

cleanup: refactor fallback to sas token on azcopy copy command

---

pkg/azurefile/azurefile.go
pkg/azurefile/controllerserver.go
pkg/azurefile/controllerserver_test.go

/kind cleanup
[release-1.29] cleanup: refactor fallback to sas token on azcopy copy command
cherry-pick for https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/2099
Fixes #
```
none
```

[release-1.29] cleanup: refactor fallback to sas token on azcopy copy command

---

.github/workflows/static.yaml
pkg/azurefile/azurefile.go
pkg/azurefile/controllerserver.go
pkg/azurefile/controllerserver_test.go
pkg/azurefile/nodeserver.go
pkg/azurefile/nodeserver_test.go
pkg/csi-common/utils_test.go
test/e2e/dynamic_provisioning_test.go
test/e2e/pre_provisioning_test.go

[release-1.28] cleanup: upgrade golint version and fix golint errors

---

pkg/azurefile/azurefile_suite_test.go
pkg/azurefile/controllerserver_test.go

/kind cleanup
Chores:adopt ginkgo in controllerserver_test.go
Fixes #
```
none
```

Chores:adopt ginkgo in controllerserver_test.go

---

pkg/azurefile/fake_mounter.go

/kind test
test: run windows ut with host process enabled
Fixes #
```
none
```

test: run windows ut with host process enabled

---

docs/driver-parameters.md
docs/workload-identity-static-pv-mount.md

doc: remove obsolete doc about volumeID format
Fixes #
```
none
```

doc: remove obsolete doc about volumeID format

---

deploy/example/cloning/nginx-pod-restored-cloning.yaml
deploy/example/daemonset.yaml
deploy/example/deployment.yaml
deploy/example/disk/statefulset-stress.yaml
deploy/example/kata-cc/statefulset.yaml
deploy/example/nfs/statefulset.yaml
deploy/example/nginx-pod-azurefile-inline-volume.yaml
deploy/example/nginx-pod-azurefile.yaml
deploy/example/smb-provisioner/nginx-on-prem-volume.yaml
deploy/example/snapshot/nginx-pod-restored-snapshot.yaml
deploy/example/statefulset.yaml
docs/workload-identity-static-pv-mount.md

doc: support example pod running on arm64 node
Fixes #
```
none
```

doc: support example pod running on arm64 node

---

test/utils/azure/azure_helpers.go

/kind test
Add UA for e2e client
Fixes #
```
none
```

test: add UserAgent for e2e client

---

pkg/azurefile/controllerserver.go
test/sanity/run-test.sh

/kind bug
fix: reduce get file share throttling when CreateSnapshot, this PR uses the filter as fileShareName to only get snapshots under the specified file share
Fixes #2152
```
fix: reduce get file share throttling when CreateSnapshot
```

fix: reduce get file share throttling when CreateSnapshot

---

test/sanity/run-test.sh

/kind test
test: enable more sanity tests
Fixes #
```
none
```

test: enable more sanity tests

---

go.mod
go.sum
vendor/github.com/golang-jwt/jwt/v4/parser.go
vendor/modules.txt

/kind bug
fix: CVE-2024-51744
Fixes #
```
fix: CVE-2024-51744
```

fix: CVE-2024-51744

---

pkg/mounter/safe_mounter_host_process_windows.go
pkg/os/smb/smb.go

/kind feature
feat: replace Get-Item powershell cmd with golang api on Windows HostProcess mode
Fixes #
```
none
```

feat: replace Get-Item powershell cmd with golang api on Windows HostProcess mode

---

pkg/azurefile/azurefile.go

/kind bug
fix: tagValueDelimiter parameter mismatch
Fixes #
```
fix: tagValueDelimiter parameter mismatch
```

fix: tagValueDelimiter parameter mismatch

---

go.mod
pkg/azurefile/azure.go
pkg/filewatcher/filewatcher.go

/kind bug
Add a file watcher, utilizing fsnotify, to monitor the Azure client certificate authentication. If the file changes, the pod will need to be restarted since Azure SDK doesn't support hotloading a new certificate yet.
Fixes #
```
none
```

feat: add a file watcher for Azure client cert auth

---

pkg/azurefile/controllerserver.go
test/sanity/run-test.sh

/kind bug
fix: reduce get file share throttling when CreateSnapshot, this PR uses the filter as fileShareName to only get snapshots under the specified file share
cherrypick of https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/2153
Fixes #
```
fix: reduce get file share throttling when CreateSnapshot
```

[release-1.29] fix: reduce get file share throttling when CreateSnapshot

---

.github/dependabot.yaml

/kind test
Group all deps update into one pr.
Fixes #
```
none
```

Group all deps update into one pr.

---

pkg/azurefile/azurefile_options.go

/kind feature
chore: increase wait-for-azcopy-timeout-minutes as 19min
Fixes #
```
none
```

chore: increase wait-for-azcopy-timeout-minutes as 19min

---

pkg/azurefile/controllerserver.go

/kind bug
fix: ignore ShareAlreadyExists error in snapshot restore and clone
Fixes #
```
fix: ignore ShareAlreadyExists error in snapshot restore and clone
```

fix: ignore ShareAlreadyExists error in snapshot restore and clone

---

pkg/azurefile/azurefile.go
pkg/azurefile/controllerserver.go

/kind bug
fix: GetFileShare throttling in CreateSnapshot
This PR addes a 10min GetFileShareSize cache in CreateSnapshot for management API calls
Fixes #
```
fix: GetFileShare throttling in CreateSnapshot
```

fix: GetFileShare throttling in CreateSnapshot

---

pkg/azurefile/azurefile.go
pkg/azurefile/controllerserver.go

/kind bug
fix: GetFileShare throttling in CreateSnapshot
This PR addes a 10min GetFileShareSize cache in CreateSnapshot for management API calls
cherrypick of https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/2234
Fixes #
```
fix: GetFileShare throttling in CreateSnapshot
```

[release-1.29] fix: GetFileShare throttling in CreateSnapshot

---

pkg/azurefile/azurefile.go
pkg/azurefile/controllerserver.go

/kind bug
fix: GetFileShare throttling in CreateSnapshot
This PR addes a 10min GetFileShareSize cache in CreateSnapshot for management API calls
cherrypick of https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/2234
Fixes #
```
fix: GetFileShare throttling in CreateSnapshot
```

[release-1.30] fix: GetFileShare throttling in CreateSnapshot

---

pkg/azurefile/controllerserver.go

/kind feature
feat: match source account as first priority in snapshot restore and volume clone scenarios, this could speed up the snapshot restore and volume clone performance in azure file and blob csi drivers
Fixes #
```release-note
feat: match source account as first priority in snapshot restore and volume clone scenarios
```
```docs
feat: match source account as first priority in snapshot restore and volume clone scenarios
```

feat: match source account as first priority in snapshot restore and volume clone scenarios

---

Makefile

/kind test
test: fix building latest-windows-hp tag
Fixes #
```
none
```

test: fix building latest-windows-hp tag

---

go.mod

/kind cleanup
chore: remove godebug winreadlinkvolume=0 on Windows build
Fixes #
```
none
```

chore: remove godebug winreadlinkvolume=0 on Windows build

---

deploy/example/windows/statefulset.yaml
pkg/mounter/safe_mounter_host_process_windows.go
pkg/os/filesystem/filesystem.go

/kind cleanup
cleanup: windows functions
Fixes #
```
none
```

cleanup: windows functions

---

test/e2e/suite_test.go

test: fix test failure when uninstall driver
Fixes #
```
none
```

test: fix test failure when uninstall driver

---

test/e2e/suite_test.go

test: fix test failure when uninstall driver
cherrypick of https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/2262
Fixes #
```
none
```

[release-1.29] test: fix test failure when uninstall driver

---

test/sanity/run-tests-all-clouds.sh

/kind cleanup
test: upgrade csi-test to v5.3.1 in sanity test
Fixes #
```
none
```

test: upgrade csi-test to v5.3.1 in sanity test

---

test/e2e/suite_test.go

/kind test
test: support runInTreeVolumeTestsOnly env var in e2e tets
Fixes #
```
none
```

test: support runInTreeVolumeTestsOnly env var in e2e tets

---

.github/dependabot.yaml

Reverts kubernetes-sigs/azurefile-csi-driver#2208

Revert "Group all deps update into one pr."

---

pkg/azurefile/controllerserver_test.go

/kind test
test: add copyvolume unit test
Fixes #
```
none
```

test: add copyvolume unit test

---

go.mod
go.sum
vendor/github.com/Azure/azure-sdk-for-go/sdk/storage/azfile/directory/constants.go
vendor/github.com/Azure/azure-sdk-for-go/sdk/storage/azfile/directory/models.go
vendor/github.com/Azure/azure-sdk-for-go/sdk/storage/azfile/file/constants.go
vendor/github.com/Azure/azure-sdk-for-go/sdk/storage/azfile/file/models.go
vendor/github.com/Azure/azure-sdk-for-go/sdk/storage/azfile/internal/exported/shared_key_credential.go
vendor/github.com/Azure/azure-sdk-for-go/sdk/storage/azfile/internal/exported/version.go
vendor/github.com/Azure/azure-sdk-for-go/sdk/storage/azfile/internal/generated/autorest.md
vendor/github.com/Azure/azure-sdk-for-go/sdk/storage/azfile/internal/generated/constants.go
vendor/github.com/Azure/azure-sdk-for-go/sdk/storage/azfile/internal/generated/zz_constants.go
vendor/github.com/Azure/azure-sdk-for-go/sdk/storage/azfile/internal/generated/zz_directory_client.go
vendor/github.com/Azure/azure-sdk-for-go/sdk/storage/azfile/internal/generated/zz_file_client.go
vendor/github.com/Azure/azure-sdk-for-go/sdk/storage/azfile/internal/generated/zz_models.go
vendor/github.com/Azure/azure-sdk-for-go/sdk/storage/azfile/internal/generated/zz_models_serde.go
vendor/github.com/Azure/azure-sdk-for-go/sdk/storage/azfile/internal/generated/zz_options.go
vendor/github.com/Azure/azure-sdk-for-go/sdk/storage/azfile/internal/generated/zz_response_types.go
vendor/github.com/Azure/azure-sdk-for-go/sdk/storage/azfile/internal/generated/zz_service_client.go
vendor/github.com/Azure/azure-sdk-for-go/sdk/storage/azfile/internal/generated/zz_share_client.go
vendor/github.com/Azure/azure-sdk-for-go/sdk/storage/azfile/internal/shared/shared.go
vendor/github.com/Azure/azure-sdk-for-go/sdk/storage/azfile/share/constants.go
vendor/github.com/Azure/azure-sdk-for-go/sdk/storage/azfile/share/models.go
vendor/modules.txt

/kind feature
feat: upgrade to azfile:1.4.0 to include STG95 go sdk change
Fixes #
```
none
```

feat: upgrade to azfile:1.4.0 to include STG95 go sdk change

---

pkg/azurefileplugin/main.go
pkg/azurefileplugin/main_test.go

/kind test
test: add unit test for main function
Fixes #
```
none
```

test: add unit test for main function

---

pkg/os/filesystem/filesystem.go
pkg/os/smb/smb.go

/kind cleanup
cleanup: only build on Windows for  pkg/os/ dir
Fixes #
```
none
```

cleanup: only build on Windows for  pkg/os/ dir

---

.github/workflows/linux.yaml

/kind test
test: exclude some go fake files in ut coverage
Fixes #
```
none
```

test: exclude some go fake files in ut coverage

---

pkg/azurefile/azurefile_options.go
pkg/azurefileplugin/main.go

/kind feature
chore: set GoMaxProcs as 2
Fixes #
```
none
```

chore: set GoMaxProcs as 2

---

pkg/azurefile/azurefile.go
pkg/azurefile/controllerserver.go
pkg/azurefile/utils.go
pkg/azurefile/utils_test.go

/kind bug
fix: switch to data plane API call when create snapshot is throttled
Fixes #
```
fix: switch to data plane API call when create snapshot is throttled
```

fix: switch to data plane API call when create snapshot is throttled

---

pkg/azurefileplugin/Dockerfile
test/sanity/run-test.sh

/kind cleanup
chore: fix azcopy download error
```
--2025-01-10 02:32:03--  https://aka.ms/downloadazcopy-v10-linux
Resolving aka.ms (aka.ms)... 23.210.242.211
Connecting to aka.ms (aka.ms)|23.210.242.211|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://azcopyvnext-awgzd8g7aagqhzhe.b02.azurefd.net/releases/release-10.27.1-20241113/azcopy_linux_amd64_10.27.1.tar.gz [following]
--2025-01-10 02:32:03--  https://azcopyvnext-awgzd8g7aagqhzhe.b02.azurefd.net/releases/release-10.27.1-20241113/azcopy_linux_amd64_10.27.1.tar.gz
Resolving azcopyvnext-awgzd8g7aagqhzhe.b02.azurefd.net (azcopyvnext-awgzd8g7aagqhzhe.b02.azurefd.net)... 13.107.246.41, 2620:1ec:bdf::41
Connecting to …
```

[release-1.29] chore: fix azcopy download error

---

pkg/csi-common/utils.go
pkg/csi-common/utils_test.go

This pull request includes changes to the `pkg/csi-common/utils.go` and `pkg/csi-common/utils_test.go` files to improve error handling and add new tests for the `ListenEndpoint` function. The most important changes include refactoring the logging mechanism and adding a comprehensive test for the `ListenEndpoint` function.
Improvements to error handling:
* [`pkg/csi-common/utils.go`](diffhunk://#diff-0d556f293c81880b06d6591091b951a2114fa383010513710c843f1d1b6a3e7aR44-R69): Introduced a new `klogFatalf` function to replace direct calls to `klog.Fatalf`, allowing for better control and testing of fatal log messages.
Enhancements to testing:
* [`pkg/csi-common/utils_test.go`](diffhunk://#diff-ea2bc4fd189dd43f448b1da4dc719a1c8287f8850cafed8c4fd6f0595a1d28c1R307-R368): Added a new …

test: add UT for ListenEndpoint in utils.go

---

pkg/azurefile/azurefile.go
pkg/azurefile/utils.go
pkg/azurefile/utils_test.go

/kind cleanup
chore: use original Cloud backoff for Delete and Resize file share on master branch
Fixes #
```
none
```

chore: use original Cloud backoff for Delete and Resize file share

---

.github/workflows/linux.yaml
pkg/azurefile/utils_test.go
pkg/util/util.go
pkg/util/util_test.go
pkg/util/util_windows.go

/kind test
test: add unit test
Fixes #
```
none
```

test: add unit test

---

pkg/azurefile/azurefile_dataplane_client_test.go

This pull request adds new test cases to the `pkg/azurefile/azurefile_dataplane_client_test.go` file to improve test coverage for Azure file client operations. The most important changes include the addition of test cases for deleting, resizing, and retrieving the quota of a file share.
New test cases:
* Added `TestDeleteFileShare` to verify the error handling when attempting to delete a nonexistent file share.
* Added `TestResizeFileShare` to verify the error handling when attempting to resize a nonexistent file share.
* Added `TestGetFileShareQuotaDataPlane` to verify the error handling when attempting to retrieve the quota of a nonexistent file share.
Fixes # …

test: add UT for azurefile_dataplane_client.go

---

pkg/azurefile/controllerserver.go

/kind feature
feat: support Provisioned v2 Azure File share sku
https://learn.microsoft.com/en-us/azure/storage/files/understanding-billing#provisioned-v2-model
v2 is not supported on all regions
<details>
```
RESPONSE 400: 400 Bad Request
ERROR CODE: RedundancyConfigurationNotAvailableInRegion
--------------------------------------------------------------------------------
{
"error": {
"code": "RedundancyConfigurationNotAvailableInRegion",
"message": "The storage account failed to create due to redundancy configuration - Sku: StandardV2_LRS, Kind: FileStorage - not available in selected Region - switzerlandnorth. Please make sure the redundancy configuration selected is available in your region. For more information …
```

feat: support Provisioned v2 Azure File share sku

---

go.mod
go.sum
vendor/modules.txt
vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/cloud.go

/kind bug
fix: only reset cloud config when cloud name is AzureStackCloud
related to fix: https://github.com/kubernetes-sigs/cloud-provider-azure/pull/8146
Fixes #
```
fix: only reset cloud config when cloud name is AzureStackCloud
```

fix: only reset cloud config when cloud name is AzureStackCloud

---

deploy/example/pv-azurefile-csi.yaml
deploy/example/pv-azurefile-nfs.yaml
docs/workload-identity-static-pv-mount.md

doc: fix volumeHandle doc
Fixes #
```
none
```

doc: fix volumeHandle doc

---

pkg/azurefile/azurefile.go

/kind cleanup
cleanup: print info error for volumeID parsing error
Fixes #
```
none
```

cleanup: print info error for volumeID parsing

---

pkg/azurefile/azurefile.go
pkg/azurefile/azurefile_dataplane_client_test.go
pkg/azurefile/azurefile_mgmt_client.go
pkg/azurefile/azurefile_mgmt_client_test.go
pkg/azurefile/azurefile_test.go
pkg/azurefile/controllerserver.go

/kind cleanup
chore: refine GetStorageAccesskey and GetFileShareClientForSub function
Fixes #
```
none
```

chore: refine GetStorageAccesskey and GetFileShareClientForSub function

---

pkg/azurefile/azurefile.go

/kind bug
chore: fix ShareQuota nil issue
Fixes #
```
none
```

chore: fix ShareQuota nil issue

---

test/e2e/suite_test.go

test: fix GetAccountNumByResourceGroup timeout
```
2025/03/19 08:04:06 ===================================================
I0319 08:04:06.856879 56556 suite_test.go:280] Unexpected error: failed to GetAccountNumByResourceGroup(capz-ngn283): context canceled: 
<*errors.errorString | 0x5640270>: 
context canceled
{
s: "context canceled",
}
```
Fixes #
```
none
```

test: fix GetAccountNumByResourceGroup timeout

---

pkg/azurefile/azurefile_dataplane_client.go
pkg/azurefile/azurefile_dataplane_client_test.go

/kind cleanup
cleanup: refine DataplaneClient
Fixes #
```
none
```

cleanup: refine DataplaneClient

---

Makefile
test/e2e/testsuites/dynamically_provisioned_cmd_volume_tester.go
test/e2e/testsuites/testsuites.go

test: increase e2e test timeout
Fixes #
```
none
```

test: increase e2e test timeout

---

pkg/azurefile/azurefile.go
pkg/azurefile/azurefile_test.go

Feature update
This patch adds one more node label check to determine whether the k8s node supports kata/kata-cc runtimes.
Node labels:-
vanilla kata: kubernetes.azure.com/kata-mshv-vm-isolation
kata-cc: kubernetes.azure.com/kata-cc-isolation
pre-release (vanilla or cc): katacontainers.io/kata-runtime
Here are the labels present on a prod AKS cluster:
Here are the labels on dev AKS cluster:
Fixes #
```
none
```

azurefile: add kata-cc-isolation node label check

---

Makefile

/kind test
Fixes #
```
none
```

test: set ginkgo timeout as 180m

---

pkg/azurefile/nodeserver.go
pkg/azurefile/utils.go

/kind cleanup
cleanup: kata mount logs
Fixes #
```
none
```

cleanup: kata mount logs

---

pkg/azurefile/azurefile.go

/kind bug
fix: storageEndPointSuffix setting in on-prem cluster
if only `storageEndpointSuffix` is specified in sc in on-prem cluster, create blob container should work with this PR.
Fixes #
```
none
```

fix: storageEndPointSuffix in on-prem cluster

---

pkg/azurefile/azurefile.go
pkg/azurefile/controllerserver.go
pkg/azurefile/controllerserver_test.go
test/e2e/testsuites/testsuites.go

fix
/kind cleanup
cleanup: remove deprecated wait.PollImediate function
Fixes #
```
none
```

cleanup: remove deprecated wait.PollImediate function

---

pkg/azurefile/azurefile.go
pkg/azurefile/azurefile_test.go

/kind test
test: add more ut
Fixes #
```
none
```

test: add more ut

---

docs/driver-parameters.md

doc: add missing permission using PrivateEndpoint
Fixes #2512
```
none
```

doc: add missing permission using PrivateEndpoint

---

go.mod
pkg/util/util.go
pkg/util/util_test.go
vendor/go.uber.org/goleak/.gitignore
vendor/go.uber.org/goleak/.golangci.yml
vendor/go.uber.org/goleak/CHANGELOG.md
vendor/go.uber.org/goleak/LICENSE
vendor/go.uber.org/goleak/Makefile
vendor/go.uber.org/goleak/README.md
vendor/go.uber.org/goleak/doc.go
vendor/go.uber.org/goleak/internal/stack/doc.go
vendor/go.uber.org/goleak/internal/stack/scan.go
vendor/go.uber.org/goleak/internal/stack/stacks.go
vendor/go.uber.org/goleak/leaks.go
vendor/go.uber.org/goleak/options.go
vendor/go.uber.org/goleak/testmain.go
vendor/go.uber.org/goleak/tracestack_new.go
vendor/modules.txt

/kind bug
fix: goroutine leak
Fixes #
```
fix: goroutine leak
```

fix: goroutine leak

---

go.mod
pkg/util/util.go
pkg/util/util_test.go
vendor/go.uber.org/goleak/.gitignore
vendor/go.uber.org/goleak/.golangci.yml
vendor/go.uber.org/goleak/CHANGELOG.md
vendor/go.uber.org/goleak/LICENSE
vendor/go.uber.org/goleak/Makefile
vendor/go.uber.org/goleak/README.md
vendor/go.uber.org/goleak/doc.go
vendor/go.uber.org/goleak/internal/stack/doc.go
vendor/go.uber.org/goleak/internal/stack/scan.go
vendor/go.uber.org/goleak/internal/stack/stacks.go
vendor/go.uber.org/goleak/leaks.go
vendor/go.uber.org/goleak/options.go
vendor/go.uber.org/goleak/testmain.go
vendor/go.uber.org/goleak/tracestack_new.go
vendor/modules.txt

/kind bug
fix: goroutine leak when timeout
cherrypick of https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/2516
Fixes #
```
fix: goroutine leak when timeout
```

[release-1.29] fix: goroutine leak when timeout

---

go.mod
pkg/util/util.go
pkg/util/util_test.go
vendor/go.uber.org/goleak/.gitignore
vendor/go.uber.org/goleak/.golangci.yml
vendor/go.uber.org/goleak/CHANGELOG.md
vendor/go.uber.org/goleak/LICENSE
vendor/go.uber.org/goleak/Makefile
vendor/go.uber.org/goleak/README.md
vendor/go.uber.org/goleak/doc.go
vendor/go.uber.org/goleak/internal/stack/doc.go
vendor/go.uber.org/goleak/internal/stack/scan.go
vendor/go.uber.org/goleak/internal/stack/stacks.go
vendor/go.uber.org/goleak/leaks.go
vendor/go.uber.org/goleak/options.go
vendor/go.uber.org/goleak/testmain.go
vendor/go.uber.org/goleak/tracestack_new.go
vendor/modules.txt

/kind bug
fix: goroutine leak when timeout
cherrypick of https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/2516
Fixes #
```
fix: goroutine leak when timeout
```

[release-1.30] fix: goroutine leak when timeout

---

go.mod
pkg/util/util.go
pkg/util/util_test.go
vendor/go.uber.org/goleak/.gitignore
vendor/go.uber.org/goleak/.golangci.yml
vendor/go.uber.org/goleak/CHANGELOG.md
vendor/go.uber.org/goleak/LICENSE
vendor/go.uber.org/goleak/Makefile
vendor/go.uber.org/goleak/README.md
vendor/go.uber.org/goleak/doc.go
vendor/go.uber.org/goleak/internal/stack/doc.go
vendor/go.uber.org/goleak/internal/stack/scan.go
vendor/go.uber.org/goleak/internal/stack/stacks.go
vendor/go.uber.org/goleak/leaks.go
vendor/go.uber.org/goleak/options.go
vendor/go.uber.org/goleak/testmain.go
vendor/go.uber.org/goleak/tracestack_new.go
vendor/modules.txt

/kind bug
fix: goroutine leak when timeout
cherrypick of https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/2516
Fixes #
```
fix: goroutine leak when timeout
```

[release-1.31] fix: goroutine leak when timeout

---

pkg/azurefile/controllerserver.go
pkg/azurefile/controllerserver_test.go

/kind test
Fixes #
```
none
```

test: ut for encryptInTransit

---

Makefile
pkg/azurefile/controllerserver.go
test/e2e/dynamic_provisioning_test.go
test/e2e/suite_test.go

/kind test
Fixes #
```
none
```

test: e2e test for encrypt In Transit

---

deploy/example/vpa/README.md
deploy/example/vpa/install-components/admission-controller-deployment.yaml
deploy/example/vpa/install-components/delete-webhook.sh
deploy/example/vpa/install-components/gencerts.sh
deploy/example/vpa/install-components/recommender-deployment.yaml
deploy/example/vpa/install-components/rmcerts.sh
deploy/example/vpa/install-components/updater-deployment.yaml
deploy/example/vpa/install-components/vpa-rbac.yaml
deploy/example/vpa/install-components/vpa-v1-crd-gen.yaml
deploy/example/vpa/install-components/warn-obsolete-vpa-objects.sh
deploy/example/vpa/install-vpa.sh
deploy/example/vpa/uninstall-vpa.sh
deploy/example/vpa/vertical-pod-autoscaler.yaml
hack/verify-yamllint.sh

/kind feature
feat: add VerticalPodAutoscaler to azurefile csi controller pod
Fixes #
```
none
```

feat: add VerticalPodAutoscaler to azurefile csi controller pod

---

docs/driver-parameters.md

doc: add missing permission using PrivateEndpoint
Fixes #
```
none
```

doc: add missing permission using PrivateEndpoint#2

---

docs/driver-parameters.md
go.mod
go.sum
pkg/azurefile/azurefile.go
pkg/azurefile/azurefile_test.go
pkg/azurefile/controllerserver.go
pkg/azurefile/controllerserver_test.go
test/e2e/dynamic_provisioning_test.go
vendor/modules.txt
vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/utils/poller.go
vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/virtualmachinescalesetvmclient/custom.go
vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/virtualmachinescalesetvmclient/interface.go
vendor/sigs.k8s.io/cloud-provider-azure/pkg/azclient/virtualmachinescalesetvmclient/mock_virtualmachinescalesetvmclient/interface.go
vendor/sigs.k8s.io/cloud-provider-azure/pkg/consts/consts.go
vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_standard.go
vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_vmss.go
vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_vmssflex.go
vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_loadbalancer.go
vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_local_services.go
vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/storage/azure_storageaccount.go

/kind feature
feat: add VNetLinkName and PublicNetworkAccess in account creation
Fixes #
```
feat: add VNetLinkName and PublicNetworkAccess in account creation
```

feat: add VNetLinkName and PublicNetworkAccess in account creation

---

docs/driver-parameters.md

-  Actually the RBAC does not support `*` actions,  `Microsoft.Network/virtualNetworks/subnets/*/read` is duplicated with `Microsoft.Network/virtualNetworks/subnets/read`.
```console
$ az provider operation show --namespace Microsoft.Network -o json | jq '.resourceTypes[].operations[]?.name'|grep 'subnets'
"Microsoft.Network/virtualNetworks/subnets/read"
"Microsoft.Network/virtualNetworks/subnets/write"
"Microsoft.Network/virtualNetworks/subnets/delete"
"Microsoft.Network/virtualNetworks/subnets/joinLoadBalancer/action"
"Microsoft.Network/virtualNetworks/subnets/join/action"
"Microsoft.Network/virtualNetworks/subnets/joinViaServiceEndpoint/action" …
```

doc: correct permissions for PrivateEndpoint

---

pkg/azurefile/azurefile.go
pkg/azurefile/azurefile_test.go
pkg/azurefile/utils.go

feature (revert)
This patch reverts a change made in commit 1bae6a7422958bf0e4b2e027c8af9ef5beccd5f6 which added support for using cifs mount in kata pods (lightweight VMs). The change was made to address disablement of virtio-fs in kata pods wrt kata GA. However, it has been found that virtio-fs will be kept functional in kata pods.
Fixes #
```
none
```

azurefile: revert to use virtio-fs for kata pods

---

pkg/azurefile/azurefile_options.go

/kind bug
fix: disable WMI call method on Windows node
Fixes #
```
fix: disable WMI call method on Windows node
```

fix: disable WMI call method on Windows node

---

deploy/example/largeFileShares/storageclass-azurefile-largefileshares.yaml
deploy/example/storageclass-azurefile-csi.yaml

doc: add StandardV2_LRS in doc examples
Fixes #
```
none
```

doc: add StandardV2_LRS in doc examples

---

.github/workflows/static.yaml
pkg/azurefile/controllerserver.go
pkg/csi-common/driver.go
pkg/csi-common/utils.go
pkg/csi-common/utils_test.go

test: fix golint errors
Fixes #
```
none
```

[release-1.31] test: fix golint errors

---

pkg/azurefile/nodeserver.go
pkg/azurefile/utils.go
pkg/azurefile/utils_test.go
test/e2e/dynamic_provisioning_test.go

/kind feature
feat: support encryptInTransit mountOption in nfs volume
Fixes #
```
feat: support encryptInTransit mountOption in nfs volume
```

feat: support encryptInTransit mountOption in nfs volume

---

go.mod
pkg/azurefile/azurefile_options.go
pkg/mounter/safe_mounter_host_process_windows.go
pkg/os/cim/smb.go
pkg/os/cim/wmi.go
pkg/os/filesystem/filesystem.go
pkg/os/smb/smb_cim.go

feat: Migrate PathValid and SMB API to use WMI and Win32 API

---

charts/index.yaml

/kind bug
fix: helm chart index on release-1.33
Fixes #
```
none
```

[release-1.33] chore: fix helm chart index on release-1.33

---

pkg/azurefile/azurefile.go

/kind cleanup
cleanup: decrease parsing volumeID log level
Fixes #
```
none
```

cleanup: decrease parsing volumeID log level

---

pkg/azurefile/azurefile.go
pkg/azurefile/controllerserver.go
pkg/azurefile/controllerserver_test.go
pkg/azurefile/nodeserver.go

/kind cleanup
cleanup: refine clientID parameter parsing
Fixes #
```
none
```

cleanup: refine clientID parameter parsing

---

pkg/azurefile/azurefile.go
pkg/azurefile/azurefile_interface.go
pkg/azurefile/azurefile_mgmt_client.go
pkg/azurefile/controllerserver.go
pkg/azurefile/controllerserver_test.go

…re v2
/kind feature
feat: support provisionedBandwidth, provisionedIops parameter for file share v2
https://learn.microsoft.com/en-us/azure/storage/files/understanding-billing#provisioned-v2-model
Fixes #
```
feat: support provisionedBandwidth, provisionedIops parameter for file share v2
```

feat: support provisionedBandwidth, provisionedIops parameter for file share v2

---

pkg/azurefile/azurefile.go
pkg/azurefile/azurefile_test.go

/kind cleanup
cleanup: refine kataNode label matching
Fixes #
```
none
```

cleanup: refine kataNode label matching

---

go.mod
go.sum
vendor/golang.org/x/oauth2/LICENSE
vendor/golang.org/x/oauth2/README.md
vendor/golang.org/x/oauth2/internal/doc.go
vendor/golang.org/x/oauth2/internal/oauth2.go
vendor/golang.org/x/oauth2/internal/token.go
vendor/golang.org/x/oauth2/internal/transport.go
vendor/golang.org/x/oauth2/oauth2.go
vendor/golang.org/x/oauth2/pkce.go
vendor/golang.org/x/oauth2/token.go
vendor/golang.org/x/oauth2/transport.go
vendor/modules.txt

/kind bug
fix: CVE-2025-22868
Fixes #
```
fix: CVE-2025-22868
```

[release-1.30] fix: CVE-2025-22868

---

pkg/azurefile/azurefile.go
pkg/azurefile/azurefile_test.go
pkg/azurefile/controllerserver.go
pkg/azurefile/controllerserver_test.go
pkg/azurefile/nodeserver.go
pkg/azurefile/nodeserver_test.go
pkg/azurefile/utils.go
pkg/azurefile/utils_test.go

/kind cleanup
chore: make runtimeClassHandler, confidentialContainerLabel configurable
cherrypick of https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/2679
Fixes #
```
none
```

[release-1.32] chore: make runtimeClassHandler, confidentialContainerLabel configurable

---

pkg/azurefile/controllerserver.go

/kind bug
fix: respect secretName during volume creation
Fixes #
```
none
```

fix: respect secretName during volume creation

---

hack/verify-helm-chart-files.sh

test: fix helm install
Fixes #
<details>
```
install helm ...
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
OK
Reading package lists...
Building dependency tree...
Reading state information...
apt-transport-https is already the newest version (2.6.1).
0 upgraded, 0 newly installed, 0 to remove and 9 not upgraded.
deb https://baltocdn.com/helm/stable/debian/ all main
Hit:1 http://deb.debian.org/debian bookworm InRelease
Hit:2 http://deb.debian.org/debian bookworm-updates InRelease
Hit:3 http://deb.debian.org/debian-security bookworm-security InRelease
Hit:4 …
```

test: fix helm install

---

pkg/azurefile/azurefile.go
pkg/azurefile/controllerserver.go
pkg/azurefile/utils.go
pkg/azurefile/utils_test.go
test/e2e/dynamic_provisioning_test.go

/kind bug
fix: set default IOPS and throughput in v2 file share creation
Fixes #
```
none
```

fix: set default IOPS and throughput in v2 file share creation

---

go.mod
test/sanity/sanity_test.go
test/utils/azure/azure_helpers.go

test: fix sanity test
Fixes #
```
none
```

test: fix sanity test

---

README.md
docs/managed-identity-mount.md

doc: mount with managed identity
Fixes #
```
none
```

doc: mount with managed identity
