kubernetes-sigs/azurefile-csi-driver

pkg/azurefile/azurefile_test.go

Fixes #1 
Added tests for `getFileShareInfo`, `getStorageAccount` under [azurefile.go](https://github.com/andyzhangx/azurefile-csi-driver/blob/master/pkg/azurefile/azurefile.go)

Add test for azurefile.go

---

Gopkg.lock
Makefile
pkg/azurefile/azurefile.go
pkg/azurefile/version.go
pkg/azurefileplugin/main.go

/kind feature
This commit adds version flag in azurefile plugin along with some metadata information like commit id and build date. Output of `azurefileplugin --version`:
```
$ ./_output/azurefileplugin --version
Build Date: "2019-03-28T17:26:19Z"
Compiler: gc
Driver Name: file.csi.azure.com
Driver Version: v0.2.0-alpha
Git Commit: b5400fb179d78cdb8c4562ceb184e05f6e2381c8
Go Version: go1.11.5
Platform: linux/amd64
```
The same information is now also printed in logs as well. Below is an example of this:
```
$ kubectl logs -f csi-azurefile-k6htj -n kube-system -c azurefile
I0328 17:30:58.727473       1 azurefile.go:65] 
DRIVER INFORMATION:
-------------------
Build …
```

enhance(version): Add version flag in azurefile plugin

---

pkg/azurefile/controllerserver.go

/kind bug
The unit used in CreateVolume should be GiB, not Byte.
Fixes #
```
fix the wrong unit in CreateVolume
```

fix the wrong unit in CreateVolume

---

Makefile
hack/run-e2e-test.sh

This commit adds `e2e-test` target for triggering e2e test
/kind feature
Fixes https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/48
```
enhance(MakeFile): adds `e2e-test` target in MakeFile
```

enhance(MakeFile): adds `e2e-test` target in MakeFile

---

OWNERS_ALIASES

I'm doing some org/repo-wide OWNERS file parsing, and this is an
invalid OWNERS_ALIASES file. It doesn't actually contain any aliases so
doesn't seem like there's much point in keeping it around. Our
verify-owners plugin should catch these in the future.

remove invalid OWNERS_ALIASES file

---

.travis.yml
Makefile
pkg/azurefile/azurefile.go
pkg/azurefile/azurefile_test.go
pkg/azurefile/controllerserver.go
test/sanity/run-test.sh
test/sanity/run-tests-all-clouds.sh

/kind feature
- implement DeleteSnapshot
- use `shareURL` to delete fileshare instead of `fileServiceClient`. Then we can use `x-ms-delete-snapshots=include` to delete all share snapshots with the share.
- enable `csi.ControllerServiceCapability_RPC_CREATE_DELETE_SNAPSHOT`
- change the way to run sanity test in CI
Fixes #18 
```
implement DeleteSnapshot
```

feat: implement DeleteSnapshot

---

go.mod
pkg/azurefile/nodeserver.go
test/sanity/run-test.sh
test/sanity/run-tests-all-clouds.sh

/kind bug
/kind flake
In order to test `EXPAND_VOLUME` controller capability, we need to update the version of CSI sanity test to v2.2.0. 
Ref: #121 
Here I fix some bugs to pass the sanity tests.
- According to the logic of sanity test `should work` in `Node Service`, we should delete the target directory in the end of `func NodeUnpublishVolume`.
- Since we enabled `csi.ControllerServiceCapability_RPC_CREATE_DELETE_SNAPSHOT`, we should check the snapshot if it exists when creating the volume. Currently, AzureFile does not support restore. Ref: https://github.com/kubernetes-sigs/azurefile-csi-driver/issues/18#issuecomment-529316027 . So I do not make the code of `creating volume from snapshot` stand-alone as a new …

chore: Update csi-sanity

---

pkg/azurefile/azurefile.go
pkg/azurefile/controllerserver.go

/kind feature
support VolumeExpansion in OFFLINE scenario
Fixes #43 
```
feat: support VolumeExpansion in OFFLINE scenario
```

feat: support VolumeExpansion in OFFLINE scenario

---

pkg/azurefile/azurefile.go
pkg/azurefile/controllerserver.go
pkg/azurefile/nodeserver.go
pkg/csi-common/driver.go

/kind feature
- Support VolumeExpansion in ONLINE scenario
- Since the expanding operation is same, stands alone the function `expandVolume()` 
Fixes #43 
```
support VolumeExpansion in ONLINE scenario
```

feat: support VolumeExpansion in ONLINE scenario

---

test/e2e/suite_test.go

>
> /kind bug
> /kind design
> /kind test
> /kind flake
This PR should enable testgrid to list all test cases we ran in https://testgrid.k8s.io/provider-azure-master#pr-azurefile-csi-driver-e2e.
/assign @andyzhangx  
Fixes #
```
None.
```

test: Run e2e test suite with JUnit reporter

---

test/e2e/README.md
test/e2e/driver/azurefile_driver.go
test/e2e/driver/driver.go
test/e2e/dynamic_provisioning_test.go
test/e2e/pre_provisioning_test.go
test/e2e/suite_test.go

>
> /kind bug
> /kind design
/kind test
> /kind flake
Azure files - add support to run the tests for in-tree
Document steps to run azure file e2e in-tree tests
Fixes #
Note: This PR is focussed on functionality and basic name changes. Upcoming PRs will convert the names of files, structs and functions to indicate this is now a generic tests.
```
```

Azure files - add support to run the tests for in-tree

---

test/e2e/manifest/linux-vmss.json
test/e2e/manifest/linux.json

>
> /kind bug
> /kind design
> /kind test
> /kind flake
Fixes https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/163#issuecomment-584159434
```
```

Use MSI-enabled cluster for e2e test

---

pkg/azurefile/nodeserver.go
test/utils/azurefile_log.sh

/kind bug
When azure file is throttled, the cifs mount would be hung, this PR adds timeout(10m) to fix this issue.
Fixes #167
about `wait.Poll` func:
```
Poll tries a condition func until it returns true, an error, or the timeout
```
https://github.com/kubernetes/apimachinery/blob/2373d029717c4d169463414a6127cd1d0d12680e/pkg/util/wait/wait.go#L397-L409
```
fix: mount timeout issue
```

fix: mount timeout issue

---

charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
deploy/csi-azurefile-node.yaml
pkg/azurefile/azurefile.go
pkg/azurefile/controllerserver.go
pkg/azurefile/nodeserver.go

/kind feature
This PR provides initial support of vhd disk mount on azure file share. 
There are two mainly two parts:
1.	Provision storage(create an azure file share and create an empty vhd in that file share)
2.	Mount storage(cifs mount file share and mount vhd as a block device)
This PR only supports static provisioning(user provides vhd file in azure file) by following config(with two new parameters `diskName`, `fstype` added in azure file storage class):
```
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
name: file.csi.azure.com
provisioner: file.csi.azure.com
parameters:
storageAccount: andypremium
resourceGroup: andy-dev
shareName: test
diskName: test.vhd
fstype: ext4
reclaimPolicy: Delete …
```

feat: provides initial support for vhd disk mount on azure file

---

pkg/azurefile/azurefile.go
pkg/azurefile/controllerserver.go
pkg/azurefile/nodeserver.go
pkg/azurefileplugin/Dockerfile
test/e2e/dynamic_provisioning_test.go

/kind bug
This PR would fix following issue(only appears in e2e test):
```
16:52:17.604694       1 controllerserver.go:129] begin to create vhd file(d6907ac4-5fca-11ea-b40e-000d3a0fbba7.vhd) size(10737418240) on share(pvc-559ddcc8-fcfd-41a4-8dc8-41bf3235e72d) on account() type(Premium_LRS) rg() location()
16:52:17.715770       1 azure_file.go:71] file share(pvc-559ddcc8-fcfd-41a4-8dc8-41bf3235e72d) under account(fc3ed76b6256c43ea871fa6) already exists
16:52:17.715795       1 azure_storage.go:52] created share pvc-559ddcc8-fcfd-41a4-8dc8-41bf3235e72d in account fc3ed76b6256c43ea871fa6
16:52:17.715806       1 controllerserver.go:120] create file share pvc-559ddcc8-fcfd-41a4-8dc8-41bf3235e72d on storage account …
```

fix: create vhd pipline timeout issue

---

test/e2e/dynamic_provisioning_test.go

>
> /kind bug
> /kind design
> /kind test
> /kind flake
https://testgrid.k8s.io/provider-azure-upstream#k8s-e2e-azure-file-1-15, https://testgrid.k8s.io/provider-azure-upstream#k8s-e2e-azure-file-1-16 and https://testgrid.k8s.io/provider-azure-upstream#k8s-e2e-azure-file-1-17 have been failing due to the 
addition of `fsType` parameter.
Fixes #
```
```

test: remove fsType parameter for one test case

---

pkg/azurefile/azurefile.go
pkg/azurefile/controllerserver.go

/kind bug
This PR add retry in create file share, try to fix following issue:
```
E0311 07:59:56.382150       1 utils.go:116] GRPC error: failed to create file share(pvc-13d2ecf9-aed4-4dfc-8e5b-821015b4f87a) on account() type(Premium_LRS) rg() location() size(100), error: could not get storage key for storage account : could not get storage key for storage account f243c9b68a4454fe19ebf41: Retriable: true, RetryAfter: 0001-01-01 00:00:00 +0000 UTC, HTTPStatusCode: 409, RawError: storage.AccountsClient#ListKeys: Failure sending request: StatusCode=409 -- Original Error: autorest/azure: Service returned an error. Status=<nil> Code="StorageAccountIsNotProvisioned" Message="The storage account provisioning state must be …
```

fix: add retry in create file share

---

README.md
deploy/example/disk/README.md
deploy/example/disk/statefulset-stress.yaml
pkg/azurefile/controllerserver.go

/kind bug
set vhd name as file share name
Sometimes create vhd disk retuened failure while vhd disk was created successfully, in such condition, azure file share is already occupied by the original vhd disk file and new vhd disk creation would fail:
```
I0312 02:49:06.599846       1 azure_storageaccount.go:106] found a matching account fb849da22ea8841d2865b11 type Premium_LRS location southeastasia
I0312 02:49:06.644905       1 azure_file.go:71] file share(pvc-3a29cb90-6370-4650-a313-313129787bc5) under account(fb849da22ea8841d2865b11) already exists
I0312 02:49:06.644922       1 azure_storage.go:52] created share pvc-3a29cb90-6370-4650-a313-313129787bc5 in account fb849da22ea8841d2865b11
I0312 02:49:06.644931       1 …
```

fix: set vhd name as fileshare name

---

pkg/azurefile/azurefile.go
pkg/azurefile/controllerserver.go

/kind bug
fix: throttling issue when creating 20 file shares in one storage account by parallel
Fixes #
```
fix: throttling issue when creating file share
```

fix: throttling issue when creating file share

---

charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
charts/latest/azurefile-csi-driver/values.yaml
charts/v0.2.0/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
charts/v0.2.0/azurefile-csi-driver/templates/csi-azurefile-node.yaml
charts/v0.2.0/azurefile-csi-driver/values.yaml
charts/v0.3.0/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
charts/v0.3.0/azurefile-csi-driver/templates/csi-azurefile-node.yaml
charts/v0.3.0/azurefile-csi-driver/values.yaml
charts/v0.4.0/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
charts/v0.4.0/azurefile-csi-driver/templates/csi-azurefile-node.yaml
charts/v0.4.0/azurefile-csi-driver/values.yaml
charts/v0.5.0/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
charts/v0.5.0/azurefile-csi-driver/templates/csi-azurefile-node.yaml
charts/v0.5.0/azurefile-csi-driver/values.yaml
deploy/csi-azurefile-controller.yaml
deploy/csi-azurefile-node.yaml
deploy/v0.2.0/csi-azurefile-controller.yaml
deploy/v0.2.0/csi-azurefile-node.yaml
deploy/v0.3.0/csi-azurefile-controller.yaml
deploy/v0.3.0/csi-azurefile-node.yaml
deploy/v0.4.0/csi-azurefile-controller.yaml
deploy/v0.4.0/csi-azurefile-node.yaml
deploy/v0.5.0/csi-azurefile-controller.yaml
deploy/v0.5.0/csi-azurefile-node.yaml

/kind bug
fix: change `imagePullPolicy` from `Always` to `IfNotPresent`([default value](https://kubernetes.io/docs/concepts/containers/images/#updating-images)), this PR could save around 1min for start up CSI driver deamonset pod on new VMSS node on AKS (with autoscaler enabled)
- `imagePullPolicy: Always` 
```
Events:
Type    Reason     Age    From                                        Message
----    ------     ----   ----                                        -------
Normal  Scheduled  2m27s  default-scheduler                           Successfully assigned kube-system/csi-azurefile-node-b98cg to aks-agentpool-00887928-vmss000001
Normal  Pulling    2m24s  kubelet, aks-agentpool-00887928-vmss000001  Pulling image …
```

fix: change imagePullPolicy to IfNotPresent

---

charts/latest/azurefile-csi-driver/templates/rbac-csi-azurefile-controller.yaml
deploy/rbac-csi-azurefile-controller.yaml

fix yamllint error
/kind feature
feat: support read cloud config from secret
This PR is to support Setting Azure cloud provider from Kubernetes secrets:
Since `v1.15.0`, Azure cloud provider supports reading the cloud config from Kubernetes secrets. The secret is a serialized version of `azure.json` file with key cloud-config. The secret should be put in `kube-system` namespace and its name should be `azure-cloud-provider`.
details:
https://github.com/kubernetes-sigs/cloud-provider-azure/blob/master/docs/cloud-provider-config.md#setting-azure-cloud-provider-from-kubernetes-secrets
Fixes #223
cc @feiskyer 
```
feat: support read cloud …
```

feat: support read cloud config from secret

---

Makefile
charts/README.md
charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
charts/latest/azurefile-csi-driver/values.yaml

>
> /kind bug
> /kind design
> /kind test
> /kind flake
We should be able to deploy both Linux and Windows version of csi-azurefile-node via helm chart to clusters containing both Windows and Linux nodes
Fixes #
```
```

chore: add linux.enabled parameter to helm chart

---

hack/verify-golint.sh

/kind flake 
Currently the go get for golangci-lint is failing with:
```
$ go get github.com/golangci/golangci-lint/cmd/golangci-lint
go/src/github.com/golangci/golangci-lint/pkg/golinters/golint.go:21:14: l.LintPkg undefined (type *"github.com/golangci/lint-1".Linter has no field or method LintPkg)
go/src/github.com/golangci/golangci-lint/pkg/golinters/gomnd.go:13:6: cannot use magic_numbers.Analyzer (type *"github.com/tommy-muehle/go-mnd/vendor/golang.org/x/tools/go/analysis".Analyzer) as type *"golang.org/x/tools/go/analysis".Analyzer in array or slice literal
```
The README.md of golangci-lint recommends to do not use go get for installation - https://github.com/golangci/golangci-lint#go.
This PR also pins the …

Do not install golangci-lint with 'go get'

---

test/e2e/testsuites/testsuites.go

/kind test
fix windows e2e test failure, this is just a workaround since `mcr.microsoft.com/dotnet/framework/samples:aspnetapp` is 1.9GB, too large
Fixes #
```
none
```

test: fix windows e2e test failure

---

pkg/azurefile/utils_test.go

/kind bug
remove unnecessary SharedInformerFactory in unit tests.
Fixes #
```
```

fix: remove unnecessary SharedInformerFactory in unit tests

---

charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
charts/v0.4.0/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
charts/v0.5.0/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
charts/v0.6.0/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
deploy/csi-azurefile-controller.yaml
deploy/v0.4.0/csi-azurefile-controller.yaml
deploy/v0.5.0/csi-azurefile-controller.yaml
deploy/v0.6.0/csi-azurefile-controller.yaml

/kind cleanup
`--provisioner` and `--connection-timeout` flags are deprecated and have no effect since v1.1.0 of csi-provisioner. Ref https://github.com/kubernetes-csi/external-provisioner/blob/v1.6.0/CHANGELOG-1.1.md
Fixes #
```
NONE
```

Remove deprecated csi-provisioner args

---

Makefile
pkg/azurefileplugin/Dockerfile
pkg/azurefileplugin/Windows.Dockerfile

* Use debian-base:v2.1.0
* Build linux binary in container when running make container
* Build both linux/windows container images using buildx instead of acr build tasks.
/kind feature
Changes the base image to debian-base:v2.1.0 which is more in line with upstream work. Also builds the linux binary in a builder container and then copies it to the main container. This workflow is more idiomatic. This also changes the workflow for building the windows container to use buildx instead of relying on acr.
Fixes #
```
```

chore(dockerfile/makefile): Update build process

---

README.md
charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
charts/latest/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
deploy/csi-azurefile-controller.yaml
deploy/csi-azurefile-node-windows.yaml
deploy/csi-azurefile-node.yaml
pkg/azurefile/azure.go
pkg/azurefile/azure_test.go

/kind feature
feat: use `azure-cred-file` configmap in `kube-system` namespace to specify azure-cred-file path
> To specify a different cloud provider config file, create `azure-cred-file` configmap before driver installation, e.g. for OpenShift, it's `/etc/kubernetes/cloud.conf`
> ```console
> kubectl create configmap azure-cred-file --from-literal=path="/etc/kubernetes/cloud.conf" --from-literal=path-windows="C:\\k\\cloud.conf" -n kube-system
> ```
Fixes #282
```
feat: use `azure-cred-file` configmap in `kube-system` namespace to specify azure-cred-file path
```

feat: use `azure-cred-file` configmap in `kube-system` namespace to specify azure-cred-file path

---

pkg/azurefile/nodeserver.go

This commit removes redundant check for
target path in nodeserver.
>
> /kind design
> /kind test
> /kind flake
/kind bug
Removes redundant check for target path
Fixes #286
```
fix: Removes redundant check for target path in nodeserver
```

fix: Remove redundant check for target path

---

pkg/azurefile/nodeserver.go
pkg/azurefile/nodeserver_test.go
test/sanity/run-test.sh

/kind feature
Implement NodeGetVolumestats feature.
Because there is no /dev/disk/azure file in Prow environment, disable the NodeGetVolumestats related negative sanity test `should fail when volume does not exist on the specified path`.
Fixes #103
```
Implement NodeGetVolumestats feature
```

feat: Implement NodeGetVolumestats feature

---

pkg/azurefile/azurefile.go
pkg/azurefile/azurefile_test.go
pkg/azurefile/controllerserver.go
pkg/azurefile/controllerserver_test.go
test/e2e/testsuites/testsuites.go

/kind feature
/kind bug
- switch to use management sdk
- handle ShareBeingDeleted error 
- handle the problem that PV is stuck at terminating after PVC is deleted during e2e tests
Fixes #188 #311 #119 
In `func ControllerExpandVolume()`, we could not get the file share now. So the current quota could not be printed. Later we should add the func Get() in k/k.
```
switch to use management sdk
```

fix: switch to use management sdk

---

pkg/azurefile/azurefile.go
pkg/azurefile/azurefile_test.go
pkg/azurefileplugin/main.go
pkg/csi-common/server.go
pkg/csi-common/server_test.go
pkg/csi-common/utils.go
test/e2e/suite_test.go

>
> /kind bug
> /kind design
> /kind flake
/kind test
Fixes #
```
test: Add tests for csicommon/server
```

test: Add tests for csicommon/server

---

deploy/example/nfs/README.md
pkg/azurefile/nodeserver.go

/kind bug
fix: disable tcp in nfs mount, due to following mount failure:
```
Warning  FailedMount             4s (x9 over 2m52s)   kubelet, k8s-agentpool-25062338-vmss000000  MountVolume.MountDevice failed for volume "pvc-a5aa59f6-161c-494c-b2cc-5f2945f7bbba" : rpc error: code = Internal desc = volume(andy-1185#andynfstest#pvc-a5aa59f6-161c-494c-b2cc-5f2945f7bbba#) mount "andynfstest.file.core.windows.net:/andynfstest/pvc-a5aa59f6-161c-494c-b2cc-5f2945f7bbba" on "/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-a5aa59f6-161c-494c-b2cc-5f2945f7bbba/globalmount" failed with mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t nfs -o vers=4,minorversion=1,proto=tcp,sec=sys …
```

fix: remove "proto=tcp" in nfs mount

---

.github/workflows/go.yml
.travis.yml
pkg/azurefile/fake_mounter.go
pkg/azurefile/fake_mounter_test.go
pkg/azurefile/nodeserver_test.go

>
> /kind bug
> /kind design
> /kind flake
/kind test
Improves the unit tests for azurefile/nodeserver. Now, root privileges are not required to run the UTs.
This is achieved by creating a new file fake_mounter where the methods of FakeMounter are overridden
**Which issue(s) this PR fixes**:.
Fixes #
```
test: Improve nodeserver unit tests
ci: Remove root privileges to run unit test
```

test: Improve UTs for nodeserver

---

test/e2e/testsuites/testsuites.go

/kind bug
The e2e test is flaky due to the following reason.
```
Dynamic Provisioning should delete PV with reclaimPolicy "Delete" [kubernetes.io/azure-file] [file.csi.azure.com] [Windows]
/home/prow/go/src/sigs.k8s.io/azurefile-csi-driver/test/e2e/dynamic_provisioning_test.go:198
Unexpected error:
<*errors.StatusError | 0xc000640aa0>: {
ErrStatus: {
TypeMeta: {Kind: "", APIVersion: ""},
ListMeta: {
SelfLink: "",
ResourceVersion: "",
Continue: "",
RemainingItemCount: nil,
},
Status: "Failure",
Message: "persistentvolumes \"pvc-e3c79ec2-117c-4195-ae82-5b297078b06f\" not found",
Reason: "NotFound",
Details: {
Name: "pvc-e3c79ec2-117c-4195-ae82-5b297078b06f",
Group: "",
Kind: "persistentvolumes",
UID: "",
Causes: nil, …
```

fix: ignore the NotFound error when patching pv

---

charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
charts/latest/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
charts/latest/azurefile-csi-driver/templates/csi-snapshot-controller.yaml
deploy/csi-azurefile-controller.yaml
deploy/csi-azurefile-node-windows.yaml
deploy/csi-azurefile-node.yaml
deploy/csi-snapshot-controller.yaml

/kind flake
Set the reasonable CPU and Memory.
- Reduce limit of azurefile container CPU and Memory to one fifth.
- Reduce limit of sidecar containers  CPU and Memory to one tenth.
Fixes #
Use `kubectl top pod` command to get the usage data.
```
POD                                         NAME              CPU(cores)   MEMORY(bytes)   
csi-azurefile-controller-849f745f84-lwpc7   csi-provisioner   1m           11Mi            
csi-azurefile-controller-849f745f84-lwpc7   csi-attacher      1m           10Mi            
csi-azurefile-controller-849f745f84-lwpc7   csi-resizer       1m           9Mi …
```

chore: reduce limit of CPU and Memory

---

Makefile
test/e2e/suite_test.go

>
> /kind bug
/kind cleanup
> /kind design
> /kind test
> /kind flake
Currently working on incorporating e2e tests in an internal pipeline and it'd be nice to have an option to run e2e tests on a cluster that already has azurefile-csi-driver install.
/assign @andyzhangx  
Fixes #
```
none
```

ci: add options to skip installing / uninstalling azurefile-csi-driver during e2e test

---

deploy/example/storageclass-azurefile-secret.yaml
pkg/azurefile/azurefile.go
pkg/azurefile/azurefile_client.go
pkg/azurefile/azurefile_test.go
pkg/azurefile/controllerserver.go

/kind feature
feat: bring your own account key
In some scenarios, user's cluster does not have permission to a storage account(in some case, the storage account is in another subscription), we already provide static provisioning for that scenario. While that's not enough, user still wants to only bring own storage account key and driver could provide storage class support(dynamic provisioning).
CSI driver already supports specifying secret in every CSI methods, and current file share operations are all based on management API, so here is the solution, when user specifying secret in below CSI methods, CSI driver should switch to use storage account key way(example code is …

feat: bring your own account key for dynamic provisioning

---

charts/latest/azurefile-csi-driver/templates/_helpers.tpl
charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
charts/latest/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
charts/latest/azurefile-csi-driver/templates/csi-snapshot-controller.yaml
charts/latest/azurefile-csi-driver/values.yaml

/kind feature
Allow to specify a secret in Helm chart used to provide credentials for Docker repositories (when they are private).
Fixes #371 

Add value in Helm chart for secret used to pull Docker images

---

charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
deploy/csi-azurefile-controller.yaml
deploy/example/nfs/README.md

/kind bug
fix: set timeout(30s) for csi-provisioner
By default it's 15s which may cause timeout when create a new storage account and file share 
Fixes #
- error logs
```
Name:          persistent-storage-statefulset-azurefile-0
Namespace:     default
StorageClass:  azurefile-csi
Status:        Bound
Volume:        pvc-ec5b7089-97f5-4d1b-bde2-73ebbb45683b
Labels:        app=nginx
Annotations:   pv.kubernetes.io/bind-completed: yes
pv.kubernetes.io/bound-by-controller: yes
volume.beta.kubernetes.io/storage-class: azurefile-csi
volume.beta.kubernetes.io/storage-provisioner: file.csi.azure.com
Finalizers: …
```

fix: set timeout(30s) for csi-provisioner

---

pkg/azurefile/azure_test.go
pkg/azurefile/azurefile_test.go
pkg/azurefile/nodeserver_test.go
test/utils/testutil/testutil.go

Signed-off-by: Mayank Shah <mayankshah1614@gmail.com>
/kind test
fix unit tests' file path compatibility and error message assertion across Windows and Linux platforms
Fixes #
```
none
```

tests: fix unit tests' file path compatibility and error message assertion across Windows and Linux platforms

---

pkg/azurefile/azurefile.go
pkg/azurefile/controllerserver.go

/kind bug
fix: account list throttling issue in CreateVolume
Fixes #432
After the fix, I found it’s throttled in creating file share on 128th PVCs, we use management API(through SRP) to create file share by default, so it looks like using bring your own storage account feature is the only way to create 1000 PVCs in parallel now. bring your own storage account feature uses account key to create file share, it works well in creating 1000 PVCs in parallel, so in that scenario, let’s ask customer to use bring own storage account key way.
W0919 00:26:51.776624       1 controllerserver.go:207] …

fix: account list throttling issue in CreateVolume

---

charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
deploy/csi-azurefile-controller.yaml
deploy/csi-azurefile-node.yaml
pkg/azurefileplugin/Dockerfile
pkg/azurefileplugin/dev.Dockerfile

Reverts kubernetes-sigs/azurefile-csi-driver#439
Original PR did not improve the security, that PR is just for bypass security scanning, while would introduce various permission setting issue.

Revert "fix: create nonroot user in Dockerfile"

---

charts/latest/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
deploy/csi-azurefile-node-windows.yaml
deploy/csi-azurefile-node.yaml

/kind bug
fix: not schedule driver pod on virtual node
original error:
```
csi-azurefile-controller-58ffc59848-pjqb6    6/6     Running            9          12d    10.240.0.115   aks-agentpool-20968559-vmss000003   <none>           <none>
csi-azurefile-node-cvzr8                     3/3     Running            0          13d    10.240.0.115   aks-agentpool-20968559-vmss000003   <none>           <none>
csi-azurefile-node-g9x24                     3/3     Running            0          13d    10.240.0.4     aks-agentpool-20968559-vmss000002   <none>           <none>
csi-azurefile-node-hkn59                     0/3     ProviderFailed     0          12d    <none>         virtual-node-aci-linux              <none> …
```

fix: not schedule driver pod on virtual node

---

pkg/azurefile/controllerserver.go
pkg/azurefile/controllerserver_test.go

/kind bug
Fix ControllerExpandVolume response.
Fixes https://github.com/kubernetes-sigs/azurefile-csi-driver/issues/477
```
Fix a bug where ControllerExpandVolume return incorrect CapacityBytes
```

Fix the controllerexpand response to bytes

---

pkg/azurefile/controllerserver.go
pkg/azurefile/controllerserver_test.go
test/integration/run-test.sh

/kind bug
This fixes an issue that when we call the CreateVolume with block volume capability, the controller service should validate that and return an error.
Fixes # https://github.com/kubernetes-sigs/azurefile-csi-driver/issues/482
```
FIX: Return error for creating raw block volume(not supported)
```
/cc @msau42 
/assign @andyzhangx

fix: return error for creating raw block volume(not supported)

---

pkg/azurefile/azurefile.go
pkg/azurefile/azurefile_test.go
pkg/azurefile/controllerserver.go
pkg/azurefile/controllerserver_test.go
pkg/azurefile/nodeserver.go
pkg/azurefile/nodeserver_test.go

/kind feature
feat: support arbitrary volume id
In previous design, if volume id format is not in `rg#accountname#filesharename#`, secrets must be provided, such scenario only works for SMB protocol, does not work for NFS protocol since NFS does not needs account key. This PR remove this restriction as long as user provides those fields in parameters:
```yaml
csi:
driver: file.csi.azure.com
readOnly: false
volumeHandle: unique-volumeid  # make sure it's a unique id in the cluster
volumeAttributes:
resourceGroup: EXISTING_RESOURCE_GROUP_NAME  # optional, only set this when storage account is not in the same resource group as agent node
storageAccount: EXISTING_STORAGE_ACCOUNT_NAME
shareName: EXISTING_FILE_SHARE_NAME  # …
```

feat: support arbitrary volume id

---

charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
charts/latest/azurefile-csi-driver/values.yaml
deploy/csi-azurefile-controller.yaml

/kind feature
chore: upgrade resizer to v1.1.0
Fixes #
```
--handle-volume-inuse-error <true/false>: Enable or disable volume-in-use error handling in external-resizer. Defaults to true and resize-controller will watch for all pods in all namespaces to check if PVC being expanded is in-use by a pod or not before retrying volume expansion if CSI driver throws volume-in-use error. Setting this to false will cause external-resizer to ignore volume-in-use error and resize-controller will retry volume expansion even if volume is already in use by a pod and CSI driver does not support expansion of in-use volumes. If CSI driver being used …
```

chore: upgrade resizer to v1.1.0

---

pkg/azurefile/azurefile.go
pkg/azurefile/nodeserver.go
pkg/azurefile/nodeserver_test.go
pkg/azurefile/volume_lock.go

/kind bug
we don't correctly handle concurrent processing of NodeUnstage call if a previous NodeStage was in-progress and same thing applies to NodeUnpublish call too.
The specs says, if an operation is in-progress for the volume then SP should return error code "10 ABORTED".
Fixes #253
```
none
```
```
none
```

fix: Handle concurrent operation of NodeUnstage with NodeStage and NodeUnpublish with NodePublish

---

.github/workflows/darwin.yaml
.github/workflows/linux.yaml
charts/latest/azurefile-csi-driver/templates/csi-azurefile-controller.yaml
charts/latest/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml
charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml
charts/latest/azurefile-csi-driver/templates/csi-snapshot-controller.yaml
deploy/csi-azurefile-controller.yaml
deploy/csi-azurefile-node-windows.yaml
deploy/csi-azurefile-node.yaml
deploy/csi-snapshot-controller.yaml
hack/verify-examples.sh
pkg/csi-common/controllerserver-default.go
pkg/csi-common/identityserver-default.go
pkg/csi-common/nodeserver-default.go
pkg/csi-common/utils.go
pkg/csi-common/utils_test.go

/kind bug
fix: reduce driver logs
- don't print following method logs by default
following 3 method logs constitute 99.8% logs of all driver logs, this PR set the log level of following 3 methods as `10`, and it would not show in driver logs by default(<= `5` will show in driver logs)
```
/csi.v1.Identity/Probe
/csi.v1.Node/NodeGetCapabilities
/csi.v1.Node/NodeGetVolumeStats
```
- set log level of csi side car contains as 2
This could reduce `17,280` logs every day of csi-provisioner, csi-resizer, etc which has lease election, following logs would show every 5s:
```
I0119 12:57:02.073355       1 leaderelection.go:282] successfully renewed lease kube-system/blob-csi-azure-com
I0119 12:57:07.081182       1 …
```

fix: reduce driver logs

---

pkg/azurefile/controllerserver.go

/kind bug
A PV that fails to be created when a storage account reaches capacity will not get provisioned until space is freed.  The volume name needs to be removed from the volMap cache so that it can be placed in a different storage account.
Fixes #
```
none
```

Bugfix for volume being forced to one account

---

pkg/azurefile/azurefile.go
pkg/azurefile/controllerserver.go
pkg/azurefile/controllerserver_test.go
pkg/azurefile/utils.go
pkg/azurefile/utils_test.go
test/e2e/pre_provisioning_test.go
test/e2e/testsuites/dynamically_provisioned_inline_volume.go
test/e2e/testsuites/specs.go
test/e2e/testsuites/testsuites.go

/kind cleanup
chore: refactor SetAzureCredentials func
Fixes #
```
none
```

chore: refactor SetAzureCredentials func

---

pkg/azurefile/azure.go
pkg/azurefile/azure_test.go
pkg/azurefile/controllerserver.go
pkg/azurefile/controllerserver_test.go

/kind cleanup
chore: refine updateSubnetServiceEndpoints
Fixes #
```
none
```

chore: refine updateSubnetServiceEndpoints

---

Makefile
pkg/azurefileplugin/Dockerfile

Signed-off-by: Sertac Ozercan <sozercan@gmail.com>
/kind cleanup
Update base image to debian bullseye which should fix the installation issue with nfs-common
Fixes #
```console
k8s.gcr.io/build-image/debian-base                         bullseye-v1.0.0    316d9421ac48   7 days ago      62.7MB
k8s.gcr.io/build-image/debian-base-arm64                   buster-v1.6.0      88e0bf68d41c   4 months ago    60.1MB
k8s.gcr.io/build-image/debian-base-amd64                   buster-v1.6.0      a064b44e3aa7   4 months ago    60.8MB
k8s.gcr.io/build-image/debian-base                         buster-v1.6.0      a064b44e3aa7   4 months ago    60.8MB …
```

update base image to bullseye

---

deploy/example/storageclass-azurefile-csi.yaml
pkg/azurefile/nodeserver.go
test/external-e2e/run.sh
test/external-e2e/testdriver-smb.yaml

/kind test
test: enable smb fsGroup external test
Fixes #
- disabled following 4 fsGroup tests:
```
Summarizing 4 Failures:
[Fail] External Storage [Driver: test.csi.azure.com] [Testpattern: Dynamic PV (default fs)] fsgroupchangepolicy [Measurement] (OnRootMismatch)[LinuxOnly], pod created with an initial fsgroup, volume contents ownership changed in first pod, new pod with same fsgroup skips ownership changes to the volume contents 
/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/utils/utils.go:717
[Fail] External Storage [Driver: test.csi.azure.com] [Testpattern: Dynamic PV (default …
```

test: enable smb fsGroup external test

---

pkg/azurefile/azure_common_windows.go
pkg/mounter/safe_mounter_v1beta_windows.go
pkg/mounter/safe_mounter_windows.go

/kind cleanup
chore: refine ProxyMounter interface
Fixes #
```
none
```

chore: refine ProxyMounter interface

---

Makefile
pkg/azurefileplugin/Dockerfile
pkg/azurefileplugin/dev.Dockerfile

/kind bug
fix: libssl1.1 vulnerability
Fixes #
```console
2021-09-21T12:37:57.259Z        INFO    Detecting Debian vulnerabilities...
2021-09-21T12:37:57.277Z        INFO    Trivy skips scanning programming language libraries because no supported file was detected
mcr.microsoft.com/oss/kubernetes-csi/azurefile-csi:v1.6.0 (debian 11.0)
=======================================================================
Total: 2 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 1, CRITICAL: 1)
+-----------+------------------+----------+-------------------+------------------+--------------------------------------+
|  LIBRARY  | VULNERABILITY ID | SEVERITY | …
```

fix: libssl1.1 vulnerability

---

pkg/azurefileplugin/Dockerfile

/kind bug
fix: CVE-2021-3996 in image build
Fixes #
```
Total: 2 (UNKNOWN: 2, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 0)
+----------+------------------+----------+-------------------+------------------+--------------------------------------+
| LIBRARY  | VULNERABILITY ID | SEVERITY | INSTALLED VERSION |  FIXED VERSION   |                TITLE                 |
+----------+------------------+----------+-------------------+------------------+--------------------------------------+
| bsdutils | CVE-2021-3995    | UNKNOWN  | 2.36.1-8          | 2.36.1-8+deb11u1 | -->avd.aquasec.com/nvd/cve-2021-3995 |
+          +------------------+ …
```

fix: CVE-2021-3996 in image build

---

pkg/azurefile/nodeserver.go
pkg/azurefile/nodeserver_test.go

/kind bug
NodePublishVolume need to be idempotent. Currently NodePublishVolume will mount a volume to the same mountpoint repeatedly when it's called with the same parameters multiply time. This may happen when CO encounter some failures. Such as, when NodePublishVolume is called but timeout, CO will call it with same parameters again.
This issue mainly due to `IsLikelyNotMountPoint` can't handle bind mount. See [IsLikelyNotMountPoint doc](https://pkg.go.dev/k8s.io/utils/mount#Mounter.IsLikelyNotMountPoint). So, list all the mount points to confirm the mountpoint exists or not.
Fixes #
```
fix: NodePublishVolume …
```

fix: NodePublishVolume idempotent issue

---

pkg/azurefile/nodeserver.go
pkg/azurefile/nodeserver_test.go

/kind bug
fix: gid conflict issue between sc and fsGroup setting
Fixes #
<details>
I have a case, where after cluster upgraded to aks 1.22 cx seeing his deployments struck in creating with below issuekubelet MountVolume.MountDevice failed for volume "pvc-bf7e2615-62da-45ac-98a2-ad4a00978fa5" : rpc error: code = InvalidArgument desc = gid(0) in storageClass and pod fsgroup(2000) are not equalWarning FailedMount 29m (x26 over 4h57m) kubelet Unable to attach or mount volumes: unmounted volumes=[log-volume], unattached volumes=[kube-api-access-gj4w6 log-volume config-volume secrets-sell-inline]: timed out waiting for the condition
These …

fix: gid conflict issue between sc and fsGroup setting

---

pkg/azurefile/controllerserver.go
pkg/azurefile/controllerserver_test.go

/kind cleanup
`"driver only supports mount access type volume capability"` message is user facing and users don't really know what a `"mount access type volume capability"` is. They requested a block volume. Rephrase the message to be more clear.
Before:
`
E1118 03:05:11.172891       1 controller.go:956] error syncing claim "76757277-3dc9-4403-bed8-e170b5f48e46": failed to provision volume with StorageClass "azurefile-csi": rpc error: code = InvalidArgument desc = CreateVolume Volume capabilities not valid: driver only supports mount access type volume capability
`
After:
`
E1118 03:05:11.172891       1 controller.go:956] error syncing claim "76757277-3dc9-4403-bed8-e170b5f48e46": failed to provision volume with …

Rephrase block volume error

---

pkg/azurefile/azurefile.go
pkg/azurefile/controllerserver.go

/kind bug
fix: default namespace issue
default namespace should be set if secretNamespace is empty, this PR fixed the following failure:
<details>
```
I0405 12:34:33.357877    7156 utils.go:76] GRPC call: /csi.v1.Node/NodeStageVolume
I0405 12:34:33.357877    7156 utils.go:77] GRPC request: {"staging_target_path":"\\var\\lib\\kubelet\\plugins\\kubernetes.io\\csi\\pv\\azurefile-8081-file.csi.azure.com-preprovsioned-pv-q76d7\\globalmount","volume_capability":{"AccessType":{"Mount":{}},"access_mode":{"mode":7}},"volume_id":"capz-bag4b6#fea767f0f8abe4a5ca1e3a0#pre-provisioned-readonly##pre-provisioned-readonly"}
I0405 12:34:33.365081    7156 azurefile.go:605] could not get account(fea767f0f8abe4a5ca1e3a0) key from …
```

fix: default namespace issue

---

pkg/azurefile/azurefile.go
pkg/azurefile/controllerserver.go

/kind cleanup
chore: refine metrics naming
Fixes #
<details>
```
"Observed Request Latency" latency_seconds=0.156082089 request="azurefile_csi_driver_controller_create_volume" resource_group="kubetest-b0nxmhvx" subscription_id="0e46bd28-a80f-4d3a-8200-d9eb8d80cb2e" source="file.csi.azure.com" volumeid="kubetest-b0nxmhvx#fa63d62dbd07047a9a41210#pre-provisioned-existing-credentials##pvc-9ac5e93f-3cc1-47eb-b7af-30a9f26729a0#azurefile-5466" result_code="succeeded"
"Observed Request Latency" latency_seconds=0.164151136 request="azurefile_csi_driver_controller_delete_volume" resource_group="kubetest-b0nxmhvx" …
```

chore: refine metrics naming

---

test/external-e2e/testdriver-nfs.yaml

/kind test
test: enable fsGroup external test for nfs
Fixes #
```
none
```

test: enable fsGroup external test for nfs

---

pkg/azurefile/azurefile.go
pkg/azurefile/azurefile_test.go
pkg/azurefile/controllerserver.go
pkg/azurefile/controllerserver_test.go
pkg/azurefileplugin/main.go

/kind bug
/kind regression
Currently when users configure Azure file storage class with fstype param any non-admin users will get permission denied errors.
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
name: mystorageclass
provisioner: file.csi.azure.com
parameters:
fstype: ext4
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
```
When trying to access the volume on a pod:
```
Can not read/write into mounted volume due to "permission denied Error"
ERROR: cannot create regular file '/mnt/storage/hello': Permission denied
```
Fixes #1012 
```
users can now …
```

add new option to allow VHD feature opt-out

---

pkg/azurefile/azurefile.go
pkg/azurefile/controllerserver.go
pkg/azurefile/fake_mounter.go
pkg/csi-common/server_test.go
pkg/mounter/safe_mounter_v1beta_windows.go
pkg/mounter/safe_mounter_windows.go

/kind test
fix TestLogGRPC ut failure
Fixes #
this PR tries to fix the following issue:
```
==================
WARNING: DATA RACE
Write at 0x000001d620e0 by goroutine 25:
flag.newBoolValue()
/Users/runner/hostedtoolcache/go/1.19.0/x64/src/flag/flag.go:128 +0x208
flag.(*FlagSet).BoolVar()
/Users/runner/hostedtoolcache/go/1.19.0/x64/src/flag/flag.go:715 +0x214
k8s.io/klog/v2.InitFlags()
/Users/runner/work/azuredisk-csi-driver/azuredisk-csi-driver/vendor/k8s.io/klog/v2/klog.go:429 +0x1e6
sigs.k8s.io/azuredisk-csi-driver/pkg/csi-common.TestLogGRPC()
/Users/runner/work/azuredisk-csi-driver/azuredisk-csi-driver/pkg/csi-common/utils_test.go: …
```

test: fix TestLogGRPC ut failure

---

pkg/azurefile/azurefile.go
pkg/azurefile/azurefile_client.go
pkg/azurefile/azurefile_client_test.go
pkg/azurefile/controllerserver.go

/kind bug
As the description in the issue https://github.com/kubernetes-sigs/azurefile-csi-driver/issues/1083, here we reuse the context from external-provisioner to cancel the context when timeout. Then the volume won't be locked in driver.
Fixes #1083 
```
fix: cancel the context when timeout of deleting file share
```

fix: cancel the context when timeout of deleting file share

---

pkg/azurefile/azurefile.go
pkg/azurefile/azurefile_test.go
pkg/azurefile/controllerserver.go

/kind bug
fix: getSubnetResourceID issue when subnetName is specified
Fixes #
```
fix: getSubnetResourceID issue when subnetName is specified
```

fix: getSubnetResourceID issue when subnetName is specified

---

docs/driver-parameters.md

As the user is required to specify a value for `volumeHandle` it is nice to have instructions on how to come up with a good value.

docs: add a section on volumeHandle to the PV Static Provision documentation

---

pkg/azurefile/azure_common_linux.go
test/e2e/dynamic_provisioning_test.go
test/e2e/testsuites/dynamically_provisioned_restart_driver_tester.go
test/e2e/testsuites/dynamically_provisioned_volume_unmount_tester.go
test/e2e/testsuites/specs.go
test/e2e/testsuites/testsuites.go

/kind cleanup
cleanup: remove redundant unmount volume code since it's already handled by mount-utils (fixed by https://github.com/kubernetes/kubernetes/pull/106906)
<details>
- smb volume unmount logs when volume is deleted in the beginning
```
I1228 11:12:45.307558       1 utils.go:76] GRPC call: /csi.v1.Node/NodeUnpublishVolume
I1228 11:12:45.307578       1 utils.go:77] GRPC request: {"target_path":"/var/lib/kubelet/pods/da9f818f-913b-4b4a-9366-84340d66c7b2/volumes/kubernetes.io~csi/pvc-4337cd9a-a158-4ffe-834d-227d0079527d/mount","volume_id":"mc_andy-aks1252_andy-aks1252_eastus#f4d4861fa0e0b462d8ff3e8#pvc-4337cd9a-a158-4ffe-834d-227d0079527d###default"}
I1228 11:12:45.307671       1 nodeserver.go:132] …
```

cleanup: remove redundant unmount volume code since it's already handled by mount-utils

---

deploy/example/storageclass-azurefile-existing-share.yaml

Adding subscriptionID parameter for use case when Azure Files storage account and cluster worker nodes are in different subscriptions (optional)
N/A
- [ x] uses [conventional commit messages](https://www.conventionalcommits.org/)
- [x ] includes documentation
Please note there are no unit tests here as this is a simple manifest example update (documentation).
```
none
```

docs: update storage class definition for optional cross-subscription config

---

pkg/azurefile/azurefile.go
pkg/azurefile/nodeserver.go
pkg/azurefileplugin/main.go

/kind feature
feat: append help link when there is mount error
example error output:
```
mount //f6036fda6458647d0a93152.file.core.windows.net/pvc-0fb82cac-c7ef-4a3b-919f-e38df1b8161d on /var/lib/kubelet/plugins/kubernetes.io/csi/file.csi.azure.com/dd0682c0f2d9d6d85b5bbad86a5014e8d7bc54b19144c454cbde25cb309724c5/globalmount failed with mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t cifs -o file_mode=0777,dir_mode=0777,actimeo=30,mfsymlinks,<masked> // xxx.file.core.windows.net/pvc-0fb82cac-c7ef-4a3b-919f-e38df1b8161d /var/lib/kubelet/plugins/kubernetes.io/csi/file.csi.azure.com/dd0682c0f2d9d6d85b5bbad86a5014e8d7bc54b19144c454cbde25cb309724c5/globalmount
Output: mount error(2): No such file or …
```

feat: append help link when there is mount error

---

go.mod
vendor/modules.txt

/kind cleanup
Pin k8s.io/dynamic-resource-allocation to v0.26.0. This is intended to fix the following error:
```
$ go list -mod readonly -m all
go: k8s.io/dynamic-resource-allocation@v0.0.0: invalid version: unknown revision v0.0.0
```
Fixes #
```
none
```

Pin k8s.io/dynamic-resource-allocation to v0.26.0

---

.github/workflows/static.yaml
go.mod
pkg/azurefile/nodeserver.go
pkg/os/smb/smb.go

tes: fix golint action failure
Fixes #
```
none
```

tes: fix golint action failure

---

pkg/azurefileplugin/Dockerfile

/kind bug
fix: debian image CVEs
Fixes #
<details>
```
mcr.microsoft.com/oss/kubernetes-csi/azurefile-csi:v1.24.0 (debian 11.5)
Total: 12 (UNKNOWN: 0, LOW: 0, MEDIUM: 4, HIGH: 7, CRITICAL: 1)
âââââââââââââââ¬âââââââââââââââââ¬âââââââââââ¬ââââââââââââââââââââ¬âââââââââââââââââââ¬âââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââ
â   Library   â Vulnerability  â Severity â Installed Version â  Fixed Version   â                            Title                             â
âââââââââââââââ¼âââââââââââââââââ¼âââââââââââ¼ââââââââââââââââââââ¼âââââââââââââââââââ¼âââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââ¤ …
```

[release-1.24] fix: debian image CVEs

---

pkg/azurefile/azurefile.go
pkg/azurefile/azurefile_test.go
pkg/azurefile/nodeserver.go
pkg/azurefileplugin/main.go

/kind bug
fix: append nosharesock mount option on Linux node by default
`nosharesock` mount option should be the default mount option, it could avoid sharing same file share mount when there are multiple PVs pointing to the same file share.
Fixes #
```
fix: append nosharesock mount option on Linux node by default
```

fix: append nosharesock mount option on Linux node by default

---

pkg/azurefile/azurefile.go
pkg/azurefile/azurefile_test.go
pkg/azurefile/nodeserver.go
pkg/azurefileplugin/main.go

/kind bug
fix: append nosharesock mount option on Linux node by default
cherry pick of https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/1267
Fixes #
```
fix: append nosharesock mount option on Linux node by default
```

[release-1.24] fix: append nosharesock mount option on Linux node by default

---

pkg/azurefile/azurefile.go
pkg/azurefile/azurefile_test.go
pkg/azurefile/nodeserver.go
pkg/azurefileplugin/main.go

/kind bug
fix: append nosharesock mount option on Linux node by default
cherry pick of https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/1267
Fixes #
```
fix: append nosharesock mount option on Linux node by default
```

[release-1.26] fix: append nosharesock mount option on Linux node by default

---

Makefile
pkg/os/smb/smb.go
pkg/util/util.go

/kind cleanup
chore: add more logs for host process deployment
chore: enable host process deployment test
Fixes #
```
none
```

chore: enable host process deployment test

---

pkg/azurefile/controllerserver.go

/kind bug
fix: don't use account search cache in RandomMatchingAccount mode
this PR together with https://github.com/kubernetes-sigs/cloud-provider-azure/pull/4203, would fix the RandomMatchingAccount issue.
```
I0630 11:53:05.980948       1 controllerserver.go:501] begin to create file share(pvc-1b33dba8-3c37-41f1-9e47-ce7e1a9b3139) on account(f0001cbc9dd7d4637a9e443) type(Standard_LRS) subID() rg(mc_andy-aks126_andy-aks126_eastus2) location() size(100) protocol(SMB)
I0630 11:53:06.009768       1 azure_storageaccount.go:254] randomly pick one matching account, index: 1, matching accounts: [{andyaccount Standard_LRS eastus2} {f0001cbc9dd7d4637a9e443 Standard_LRS eastus2}]
I0630 11:53:06.009784       1 …
```

fix: don't use account search cache in RandomMatchingAccount mode

---

pkg/azurefile/azurefile.go
pkg/azurefile/controllerserver.go

/kind bug
fix: stop resize file share when account limit is exceeded
<details>
```
W0807 02:36:49.123547       1 azurefile.go:835] ResizeFileShare(pvc-cfc300e0-0045-401f-8f8c-757910acd8b4) on account(xxx) with new size(419) failed with error(failed to update quota on file share(pvc-cfc300e0-0045-401f-8f8c-757910acd8b4), err: storage.FileSharesClient#Update: Failure responding to request: StatusCode=429 -- Original Error: autorest/azure: Service returned an error. Status=429 Code="TooManyRequests" Message="The request is being throttled as the limit has been reached for operation type - Write_ObservationWindow_00:00:01. For more information, see - https://aka.ms/srpthrottlinglimits"), waiting for retrying
W0807 …
```

fix: stop resize file share when account limit is exceeded

---

docs/driver-parameters.md
go.mod
pkg/azurefile/azurefile.go
pkg/azurefile/azurefile_test.go
pkg/azurefile/controllerserver.go
pkg/azurefile/controllerserver_test.go
test/e2e/dynamic_provisioning_test.go

/kind feature
feat: add accountQuota parameter
Fixes #
```
feat: add accountQuota parameter
```

feat: add accountQuota parameter

---

docs/driver-parameters.md
go.mod
pkg/azurefile/azurefile.go
pkg/azurefile/azurefile_test.go
pkg/azurefile/controllerserver.go
pkg/azurefile/controllerserver_test.go

/kind feature
feat: add accountQuota parameter
cherrypick of https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/1362
Fixes #
```
feat: add accountQuota parameter
```

[release-1.26] feat: add accountQuota parameter

---

go.mod
pkg/azurefile/azure_common_darwin.go
pkg/azurefile/azure_common_linux.go
pkg/azurefile/azure_common_windows.go
pkg/azurefile/nodeserver.go
pkg/azurefile/nodeserver_test.go

/kind bug
fix: incorrect volume usage on Windows node with host process deployment
<details>
- get permission denied in non host process deployment
```
I0813 14:38:57.305188    7060 utils.go:76] GRPC call: /csi.v1.Node/NodeGetVolumeStats
I0813 14:38:57.305188    7060 utils.go:77] GRPC request: {"volume_id":"csi-c67aa8fb6faecd9e38978fab46a3b86d1de33a34c810ea2c7a1250431092c4ad","volume_path":"c:\\var\\lib\\kubelet\\pods\\3fa8e1e7-f4af-4609-8527-33f4e4395941\\volumes\\kubernetes.io~csi\\test-volume-1\\mount"}
E0813 14:38:57.374862    7060 utils.go:81] GRPC error: rpc error: code = Internal desc = failed to get free space on path c:\var\lib\kubelet\pods\3fa8e1e7-f4af-4609-8527-33f4e4395941\volumes\kubernetes.io~csi\test-volum …
```

fix: incorrect volume usage on Windows node with host process deployment

---

pkg/azurefileplugin/Dockerfile

/kind bug
fix: upgrade base image to alpine 3.18 to fix DNS issue
tricky thing is that nslookup works inside the driver with alpine 3.15 image, but cifs mount returns dns resolution error, return error msg:
```
Output: mount error: could not resolve address for xxx.file.core.windows.net: Unknown error
```
https://www.msn.com/en-us/news/technology/alpine-linux-318-fixes-dns-over-tcp-issue-now-ready-for-all-the-internets-problems/ar-AA1bfaqi#:~:text=For%20many%20years%2C%20and%20by%20design%2C%20Musl%20did,meaning%20that%20it%20also%20works%20in%20Alpine%203.18.
The latest update to the ultra-lightweight Alpine Linux distro, as widely used for hosting Docker containers, fixes an important issue.…
There are many relatively …

fix: upgrade base image to alpine 3.18 to fix DNS issue

---

pkg/azurefile/azurefile.go
pkg/azurefile/controllerserver.go
pkg/azurefileplugin/main.go

/kind bug
fix: delay removing skipMatchingTag when account is full
There is a rule that when storage account is full, the azure file driver would add a tag ("skip-matching": “”) to the storage account, and then driver would stop matching that account; when the file share in the storage account is deleted, the azure file driver would remove the tag from the storage account, this scenario works in most cases. But when the file share deletion and creation happen frequently, the storage account would reach quota limit frequently, that would also cause lots of throttling errors. This PR tries to delay removing skipMatchingTag when account is full to 30min.
Fixes #
**Special …

fix: delay removing skipMatchingTag when account is full

---

pkg/azurefileplugin/Dockerfile

/kind bug
fix: revert alpine base image change to fix DNS issue
revert of https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/1175
On some k8s clusters with customer vnet setting, cifs mount cannot resolve DNS while nslookup works well, and switch to debian-base image works.
- Root cause: 
cifs mount is using [getaddrinfo](https://github.com/piastry/cifs-utils/blob/316522036133d44ed02cd39ed2748e2b59c85b30/resolve_host.c#L48) invoked by [resolve_host](https://github.com/piastry/cifs-utils/blob/316522036133d44ed02cd39ed2748e2b59c85b30/mount.cifs.c#L1897) which finally depends on glibc implementation on debian based image, while on alpine image, it's using musl, getaddrinfo may not handle DNS well in lots of cases: …

fix: revert alpine base image change to fix DNS issue

---

docs/driver-parameters.md
pkg/azurefile/controllerserver.go

Reverts kubernetes-sigs/azurefile-csi-driver#1309
we are considering reverting this PR since without account search cache, there could be storage account api throttling issue when there are large number of azure file creation in parallel. So we still want to use account search which makes this RandomMatchingAccount feature not evenly distributed, and as long as user create many file shares, the file share num would be relatively distributed accross multiple storage accounts in the end, that's a limitation of this RandomMatchingAccount feature.

Revert "fix: don't use account search cache in RandomMatchingAccount mode"

---

pkg/azurefile/azurefile.go
pkg/azurefile/nodeserver.go
pkg/azurefileplugin/main.go

/kind bug
fix: add VolumeStats cache to avoid massive statfs calls
This PR adds a 10min cache for VolumeStats per volumeID, that could avoid massive statfs calls
Fixes #
```
fix: add VolumeStats cache to avoid massive statfs calls
```

fix: add VolumeStats cache to avoid massive statfs calls

---

pkg/azurefile/azurefile.go
pkg/azurefile/nodeserver.go
pkg/azurefileplugin/main.go

/kind bug
fix: add VolumeStats cache to avoid massive statfs calls
cherrypick of https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/1438
Fixes #
```
fix: add VolumeStats cache to avoid massive statfs calls
```

[releaes-1.27] fix: add VolumeStats cache to avoid massive statfs calls

---

pkg/azurefile/azurefile.go
pkg/azurefile/nodeserver.go
pkg/azurefileplugin/main.go

/kind bug
fix: add VolumeStats cache to avoid massive statfs calls
cherrypick of https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/1438
Fixes #
```
fix: add VolumeStats cache to avoid massive statfs calls
```

[release-1.26] fix: add VolumeStats cache to avoid massive statfs calls

---

pkg/azurefile/azurefile.go
pkg/azurefile/nodeserver.go
pkg/azurefileplugin/main.go

/kind cleanup
chore: provide a driver flag to print volume stats call with log level 2
Fixes #
```
none
```

chore: provide a driver flag to print volume stats call with log level 2

---

pkg/azurefile/controllerserver.go

/kind cleanup
fix: refine create volume metrics
Fixes #
```
fix: refine create volume metrics
```

fix: refine create volume metrics

---

deploy/example/azure.json
docs/csi-debug.md
pkg/azurefile/controllerserver.go
pkg/azurefile/controllerserver_test.go
test/e2e/driver/azurefile_driver.go

/kind bug
While using StorageClass with samba protocol without explicitly specifying strorage account type users get a misleading message and volume creation fails:
`Status=400 Code="InvalidHeaderValue" Message="The value for one of the HTTP headers is not in the correct format.`
This happens in a scenario when creating a volume with size < 100Gi and storage account name (premium type) was provided as a parameter in `StorageClass` while `skuName` was omitted. Premium requirement is that a fileshare must have at least 100Gi in size.
Driver can lookup storage account type via storage account client and use that instead of relying on the`skuName` parameter that users otherwise need to set manually. 
**Which issue(s) this PR …

fix: check storage account type if parameter is missing

---

deploy/example/e2e_usage.md

doc: refine inline volume example
Fixes #
```
none
```

doc: refine inline volume example

---

hack/verify-helm-chart.sh

test: fix verify-helm-chart failure
```
helm chart index verified.
Running helm lint
==> Linting /home/prow/go/src/sigs.k8s.io/blob-csi-driver/charts/latest/blob-csi-driver
[INFO] Chart.yaml: icon is recommended
1 chart(s) linted, 0 chart(s) failed
Comparing image version between helm chart and manifests in deploy folder
error: externally-managed-environment
× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
python3-xyz, where xyz is the package you are trying to
install.
If you wish to install a non-Debian-packaged Python package,
create a virtual environment using python3 -m venv path/to/venv.
Then use path/to/venv/bin/python and path/to/venv/bin/pip. …
```

test: fix verify-helm-chart failure

---

hack/verify-examples.sh
test/e2e/dynamic_provisioning_test.go
test/e2e/suite_test.go
test/utils/azurefile_log.sh

test: enable cloudprovider_azure metrics print
Fixes #
```
none
```

[release-1.26] test: enable cloudprovider_azure metrics print

---

pkg/azurefile/azure.go

/kind bug
fix: nfs volume creation failure due to Microsoft.Storage.Global Service endpoint enabled
- error msg
```
35s         Warning   ProvisioningFailed      persistentvolumeclaim/pvc-azurefile   failed to provision volume with StorageClass "azurefile-nfs": rpc error: code = Internal desc = update service endpoints failed with error: failed to update the subnet aks-subnet under vnet aks-vnet-32454943: &{false 400 0001-01-01 00:00:00 +0000 UTC {
"error": {
"code": "SubnetHasBothRegionalAndGlobalStorageServiceEndpointsTogether",
"message": "Subnet /subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Network/virtualNetworks/aks-vnet-32454943/subnets/aks-subnet has ServiceEndpoint entries for both …
```

fix: nfs volume creation failure due to Microsoft.Storage.Global Service endpoint enabled

---

.github/workflows/static.yaml
.golangci.yml
pkg/azurefile/azure_common_linux.go
pkg/azurefile/azurefile.go
pkg/azurefile/controllerserver.go
pkg/azurefile/controllerserver_test.go
pkg/azurefile/fake_mounter.go
pkg/azurefile/identityserver.go
pkg/azurefile/nodeserver.go
pkg/azurefile/utils.go
pkg/azurefile/utils_test.go
pkg/azurefileplugin/main.go
pkg/csi-common/server_test.go
pkg/mounter/safe_mounter_unix.go
pkg/os/filesystem/filesystem.go
pkg/util/util.go
pkg/util/util_test.go
test/e2e/driver/azurefile_driver.go
test/e2e/testsuites/dynamically_provisioned_inline_volume.go
test/e2e/testsuites/specs.go
test/utils/azure/azure_helpers.go

/kind test
test: upgrade golangci/golangci-lint-action to v1.54
Fixes #
```
none
```

test: upgrade golangci/golangci-lint-action to v1.54

---

test/external-e2e/run.sh
test/external-e2e/testdriver-nfs.yaml

test: fix external test failure
original external test is trying to expand premium file share with 6GB size, and failed with following error:
```
I1120 12:37:47.522673       1 utils.go:76] GRPC call: /csi.v1.Controller/ControllerExpandVolume
I1120 12:37:47.522688       1 utils.go:77] GRPC request: {"capacity_range":{"required_bytes":6442450944},"volume_capability":{"AccessType":{"Mount":{"mount_flags":["dir_mode=0777","file_mode=0777","mfsymlinks","cache=strict","nosharesock","actimeo=30"]}},"access_mode":{"mode":7}},"volume_id":"capz-yh200k#f6f8bd190baf14f198b41b5#pvc-af526e92-c040-4ab5-9b31-a4ba1ab60ef3###volume-expand-6158"}
I1120 12:37:47.522896       1 azurefile.go:550] got storage …
```

test: fix external test failure

---

pkg/azurefile/azurefile.go
pkg/azurefile/azurefile_test.go
pkg/azurefile/nodeserver.go
pkg/azurefileplugin/main.go

/kind feature
feat: append default nfs mount options
refer to https://learn.microsoft.com/en-us/azure/storage/files/storage-files-how-to-mount-nfs-shares?tabs=powershell#mount-options, `noresvport, actimeo=30` should be appended to nfs mount options by default.
Fixes #
```
feat: append default nfs mount options
```

feat: append default nfs mount options

---

pkg/azurefile/nodeserver.go
pkg/azurefile/nodeserver_test.go

/kind bug
fix: reduce mount lock to avoid volumeID collision issue
the volumeHandle(volumeID) could be duplicated in PV, and duplicated volumeHandle(volumeID) is already allowed in latest k8s version, this PR reduces mount lock to avoid volumeID collision issue, the lock only happen when volumeID + stagingPath is the same
Fixes #1620
```
fix: reduce mount lock to avoid volumeID collision issue
```

fix: reduce mount lock to avoid volumeID collision issue

---

pkg/azurefile/azurefile.go
pkg/azurefile/azurefile_options.go
pkg/azurefile/controllerserver.go

/kind test
test: add flag for azcopy use sas token by default
Fixes #
```
none
```

chore: add flag for azcopy use sas token by default

---

pkg/azurefile/azurefile.go
pkg/azurefile/azurefile_options.go
pkg/azurefile/azurefile_test.go

/kind bug
fix: increase volume cloning timeout and reduce time cost
```
I0119 16:02:28.249983       1 controllerserver.go:558] begin to create file share(pvc-2be8db95-bfdd-40ea-af4e-6bec11a63c42) on account(f3f8a72cba75146cea68300) type(Standard_LRS) subID() rg(capz-q1e8te) location() size(10) protocol(SMB)
I0119 16:02:28.406155       1 controllerserver.go:1265] generate sas token for account(f3f8a72cba75146cea68300)
I0119 16:02:28.422141       1 azurefile.go:1019] azcopy job status: NotFound, copy percent: %, error: <nil>
I0119 16:02:28.422176       1 azurefile.go:1023] begin to copy fileshare pvc-08990f2c-6be3-4927-99ac-9256deb73c1a to pvc-2be8db95-bfdd-40ea-af4e-6bec11a63c42
I0119 16:02:30.423114       1 …
```

fix: increase volume cloning timeout and reduce time cost

---

pkg/azurefile/azure.go

/kind bug
Enables azure-csi to be run with the option to provide a cloud-config in a secret, which is required via the current helm chart for non AKS clusters.
Current implementation is shadowing the variables, so even on successful loading the config from the secret, the configuration is lost (nil) and ignored by the rest of the code.
```
none
```

fix: ensure azure cloud config could be loaded from secret

---

test/e2e/dynamic_provisioning_test.go

test: remove one vhd e2e test
Fixes #
```
none
```

test: remove one vhd e2e test

---

pkg/azurefile/azurefile.go
pkg/azurefile/controllerserver.go
pkg/azurefile/controllerserver_test.go
pkg/azurefile/volume_lock.go
pkg/util/util.go
pkg/util/util_test.go

/kind bug
fix: fix azcopy exec timeout func, use `WaitForExecCompletion` func in `util.go` waits for the exec function to complete or times out
Fixes #
```
none
```

fix: fix azcopy exec timeout func

---

pkg/azurefileplugin/Dockerfile
test/sanity/run-test.sh

/kind feature
feat: upgrade azcopy version to 10.23.0 for volume clone feature
cherrypick of https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/1756
Fixes #
```
none
```

[release-1.29] feat: upgrade azcopy version to 10.23.0 for volume clone feature

---

pkg/azurefile/azure.go
pkg/azurefile/azure_test.go

/kind bug
The same fix as https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/2233
Fixes #
```
fix: workload identity did not work
```

fix: workload identity did not work

---

pkg/azurefile/azure_common_linux.go
pkg/mounter/safe_mounter_host_process_windows.go

/kind cleanup
cleanup: refine extensiveMountCheck usage in unmount
Fixes #
```
none
```

cleanup: refine extensiveMountCheck usage in unmount

---

pkg/os/smb/smb.go

/kind bug
fix: trim slash in RemoveSmbGlobalMapping
```
I0419 05:10:41.566746    5668 safe_mounter_host_process_windows.go:145] remote server path: UNC\f95c76592b2ac4bcb957ad4.file.core.windows.net\pre-provisioned-multiple-pods\, local path: c:\var\lib\kubelet\plugins\kubernetes.io\csi\file.csi.azure.com\ff618e8b87f48350191c3ebae8902d9c38e17ee1b1913422f168f2865355330c\globalmount
I0419 05:10:41.567453    5668 smb.go:110] checking file ff618e8b87f48350191c3ebae8902d9c38e17ee1b1913422f168f2865355330c
I0419 05:10:41.567529    5668 smb.go:114] skip current mount path c:\var\lib\kubelet\plugins\kubernetes.io\csi\file.csi.azure.com\ff618e8b87f48350191c3ebae8902d9c38e17ee1b1913422f168f2865355330c\globalmount
I0419 …
```

fix: trim slash in RemoveSmbGlobalMapping

---

pkg/azurefile/azure_common_darwin.go
pkg/azurefile/azure_common_linux.go
pkg/azurefile/azure_common_windows.go
pkg/azurefile/azurefile.go
pkg/azurefile/nodeserver.go
pkg/azurefileplugin/main.go
pkg/mounter/safe_mounter_host_process_windows.go
pkg/mounter/safe_mounter_v1beta_windows.go
pkg/os/smb/smb.go
pkg/os/smb/smb_test.go

/kind bug
fix: remove SMBGlobalMapping on Windows node during volume unmount
cherrypick of https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/1846
Fixes #1830
```
fix: remove SMBGlobalMapping on Windows node
```

[release-1.28] fix: remove SMBGlobalMapping on Windows node

---

pkg/os/smb/smb.go

/kind bug
fix: trim slash in RemoveSmbGlobalMapping
```
I0419 05:10:41.566746    5668 safe_mounter_host_process_windows.go:145] remote server path: UNC\f95c76592b2ac4bcb957ad4.file.core.windows.net\pre-provisioned-multiple-pods\, local path: c:\var\lib\kubelet\plugins\kubernetes.io\csi\file.csi.azure.com\ff618e8b87f48350191c3ebae8902d9c38e17ee1b1913422f168f2865355330c\globalmount
I0419 05:10:41.567453    5668 smb.go:110] checking file ff618e8b87f48350191c3ebae8902d9c38e17ee1b1913422f168f2865355330c
I0419 05:10:41.567529    5668 smb.go:114] skip current mount path c:\var\lib\kubelet\plugins\kubernetes.io\csi\file.csi.azure.com\ff618e8b87f48350191c3ebae8902d9c38e17ee1b1913422f168f2865355330c\globalmount
I0419 …
```

[release-1.30] fix: trim slash in RemoveSmbGlobalMapping

---

pkg/azurefile/azure_common_darwin.go
pkg/azurefile/azure_common_linux.go
pkg/azurefile/azure_common_windows.go
pkg/azurefile/azurefile.go
pkg/azurefile/nodeserver.go
pkg/azurefileplugin/main.go
pkg/mounter/safe_mounter_host_process_windows.go
pkg/mounter/safe_mounter_v1beta_windows.go
pkg/os/smb/smb.go
pkg/os/smb/smb_test.go

/kind bug
fix: remove SMBGlobalMapping on Windows node during volume unmount
cherrypick of https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/1846
Fixes #1830
```
fix: remove SMBGlobalMapping on Windows node
```

[release-1.29] fix: remove SMBGlobalMapping on Windows node

---

docs/workload-identity-static-pv-mount.md

chore: fix workload identity doc

---

pkg/os/smb/smb.go
pkg/util/util.go

/kind feature
fix: allow more cache hit in GetRemoteServerFromTarget on hpc deployment
Fixes #
```
fix: allow more cache hit in GetRemoteServerFromTarget on hpc deployment
```

fix: allow more cache hit in GetRemoteServerFromTarget on hpc deployment

---

pkg/azurefile/controllerserver.go

/kind bug
fix: incorrect status.creationTime value in snapshot creation with useDataPlaneAPI: “true”
issue: https://github.com/kubernetes-sigs/azurefile-csi-driver/issues/1957
Fixes #
test result:
```
$ k describe vs
WARNING: version difference between client (1.30) and server (1.28) exceeds the supported minor version skew of +/-1
Name:         azurefile-volume-snapshot
Namespace:    default
Labels:       <none>
Annotations:  <none>
API Version:  snapshot.storage.k8s.io/v1
Kind:         VolumeSnapshot
Metadata:
Creation Timestamp:  2024-07-08T07:21:45Z
Finalizers:
snapshot.storage.kubernetes.io/volumesnapshot-as-source-protection …
```

fix: incorrect status.creationTime value in snapshot creation with useDataPlaneAPI: “true”

---

pkg/azurefile/azurefile.go
pkg/azurefile/controllerserver.go
pkg/azurefile/utils.go
pkg/azurefile/utils_test.go
test/e2e/testsuites/dynamically_provisioned_tags_tester.go

/kind feature
feat: add tag value delimiter parameter and allow tag values containing commas and equal sign
referring to azuredisk csi driver issue https://github.com/kubernetes-sigs/azuredisk-csi-driver/issues/2323
Fixes #
```
none
```

feat: add tagValueDelimiter parameter

---

docs/driver-parameters.md
pkg/azurefile/azurefile.go
pkg/azurefile/controllerserver.go
pkg/azurefile/controllerserver_test.go

/kind feature
Allows to provision dynamic storage accounts with shared key access disabled.
referring to blob-csi-driver issue: https://github.com/kubernetes-sigs/blob-csi-driver/issues/1462
Fixes #
```
none
```

feat: add allowSharedKeyAccess parameter

---

deploy/example/windows/deployment.yaml
deploy/example/windows/statefulset.yaml
hack/verify-examples.sh

/kind test
test: change default windows tests to use ltsc2022 image
Fixes #
```
none
```

test: change default windows tests to use ltsc2022 image

---

pkg/azurefile/nodeserver.go
pkg/azurefile/utils.go
pkg/azurefile/utils_test.go
test/e2e/dynamic_provisioning_test.go
test/e2e/testsuites/specs.go
test/e2e/testsuites/testsuites.go

/kind bug
fix: respect ReadOnly AccessMode in volume mount
When user sets ReadOnlyMany or ReadOnlyOnce on the volume accessmode, the driver should append "ro" mount option during mount
Fixes #
```
fix: respect ReadOnly AccessMode in volume mount
```

fix: respect ReadOnly AccessMode in volume mount

---

pkg/azurefile/controllerserver.go

/kind bug
fix: only last subnet is set in account ACL created by driver
cherrypick of https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/2027
When `subnetName` is specified in storage class, currently only last subnet is set in account ACL created by driver, this PR fixed the issue.
Fixes #
```
fix: only last subnet is set in account ACL created by driver
```

[release-1.28] fix: only last subnet is set in account ACL created by driver

---

pkg/azurefile/azure.go
pkg/azurefile/azure_test.go
pkg/azurefile/azurefile.go
pkg/azurefile/controllerserver.go
pkg/azurefile/controllerserver_test.go

/kind bug
fix: nfs mount failure when there are multiple subnets in the cluster
When there are multiple node pools (with multiple subnets) in the cluster, this driver would only set the first node pool to storage account ACL, which makes nfs mount fails with "access denied" error when pods with nfs volume are scheduled to other node pool, this PR adds multiple subnets into the account ACL.
```
I0803 02:52:00.813091       1 utils.go:101] GRPC call: /csi.v1.Controller/CreateVolume
I0803 02:52:00.813116       1 utils.go:102] GRPC request: {"capacity_range":{"required_bytes":107374182400},"name":"pvc-290b8eb8-8d36-4566-81e7-054bba14160b","parameters":{"csi.storage.k8s.io/pv/name":"pvc-290b8eb8-8d36-4566-81e7-054bba14160b","cs …
```

fix: nfs mount failure when there are multiple subnets in the cluster

---

go.mod
go.sum
vendor/modules.txt
vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_storageaccount.go

/kind bug
fix: VirtualNetworkRule match issue during account search
related to https://github.com/kubernetes-sigs/cloud-provider-azure/pull/6741
original code logic does not check every VirtualNetworkResourceID in the account, thus the matching is incomplete, this PR fixes the issue.
Fixes #
```release-note
fix: VirtualNetworkRule match issue during account search
```
```docs
fix: VirtualNetworkRule match issue during account search
```

fix: VirtualNetworkRule match issue during account search

---

pkg/azurefileplugin/Dockerfile

/kind bug
Remove wget from image to close CVE-2024-38428. Edit: vulnerable binary is no longer present in intermediate layers.
Build Docker image in stages, resulting in a smaller image with fewer layers (size reduction 35 MB).
Fixes #
```
none
```

fix: CVE-2024-38428 remove wget to close vuln, reduce image size

---

pkg/azurefile/azurefile.go
pkg/azurefile/controllerserver.go
pkg/azurefile/controllerserver_test.go

/kind cleanup
[release-1.30] cleanup: refactor fallback to sas token on azcopy copy command
cherry-pick for https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/2099
Fixes #
```
none
```

[release-1.30] cleanup: refactor fallback to sas token on azcopy copy command

---

pkg/mounter/safe_mounter_host_process_windows.go
pkg/mounter/safe_mounter_unix_test.go
pkg/mounter/safe_mounter_windows.go
pkg/os/smb/smb.go
pkg/os/smb/smb_test.go

/kind cleanup
revert: GetRemoteServerFromTarget on Windows cache optimization
this PR is a revert of https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/1934 since finally we have replaced `(Get-Item -Path $Env:mount).Target` with golang API `os.Readlink`  in https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/2172, that would solve the performance issue
Fixes #
```
none
```

revert: GetRemoteServerFromTarget on Windows cache optimization

---

go.mod

/kind bug
Revert to go 1.22 windows filesystem behavior building with go 1.23 until use of Stat/Lstat/EvalSymlinks adjusts to go1.23 behavior
for more details, refer to https://github.com/kubernetes/kubernetes/issues/129080
Fixes #
```release-note
fix: revert to go1.22 windows filesystem stdlib behavior building with go 1.23
```
```docs
fix: revert to go1.22 windows filesystem stdlib behavior building with go 1.23
```

fix: revert to go1.22 windows filesystem stdlib behavior

---

pkg/azurefile/controllerserver.go
pkg/azurefile/utils.go
pkg/azurefile/utils_test.go

/kind feature
chore: append subsid in snapshot id, this could make snapshot copy across different subs work
<details>
```
- before the change
I1208 10:28:01.445822       1 utils.go:101] GRPC call: /csi.v1.Controller/CreateSnapshot
I1208 10:28:01.445904       1 utils.go:102] GRPC request: {"name":"snapshot-d5ba2ca6-a632-4de2-9da6-fed6fb7b8a66","source_volume_id":"capz-0srnt6#f5181a7da05654559a366ab#pvc-1f27c75b-5c53-47f5-b87a-30edfad0ce84###azurefile-7082"}
I1208 10:28:01.555096       1 controllerserver.go:1291] list snapshot of share(pvc-1f27c75b-5c53-47f5-b87a-30edfad0ce84) under account(f5181a7da05654559a366ab) rg(capz-0srnt6) subsID() with total number(1)
I1208 10:28:01.894431       1 controllerserver.go:940] created …
```

chore: append subsid in snapshot id

---

pkg/azurefile/controllerserver.go
pkg/azurefile/controllerserver_test.go

/kind bug
fix: wait for azcopy job running in snapshot restore and clone
- original behavior
```
I1130 09:00:23.572985       1 utils.go:102] GRPC request: {"capacity_range":{"required_bytes":1073741824000},"name":"pvc-9a891963-4d08-4642-860d-52b313a34599","parameters":{"csi.storage.k8s.io/pv/name":"pvc-9a891963-4d08-4642-860d-52b313a34599","csi.storage.k8s.io/pvc/name":"pvc-azurefilesrestore-100gb-33","csi.storage.k8s.io/pvc/namespace":"churntest","skuName":"Premium_ZRS","useDataPlaneAPI":"true"},"volume_capabilities":[{"AccessType":{"Mount":{"mount_flags":["mfsymlinks","actimeo=30","nosharesock"]}},"access_mode":{"mode":7}}],"volume_content_source":{"Type":{"Snapshot":{"snapshot_id":"MC_mayaggarea_mayankscrubber_eastasia …
```

fix: wait for azcopy job running in snapshot restore and clone

---

pkg/filewatcher/filewatcher.go
pkg/filewatcher/filewatcher_test.go

This pull request introduces several changes to the `pkg/filewatcher` package to improve the handling of file watching and add tests. The most important changes include the addition of a mockable exit function, the introduction of a reset function for testing purposes, and the creation of new tests for the file watcher functionality.
Changes to `pkg/filewatcher/filewatcher.go`:
* Added a mockable `exit` function to handle program termination, replacing direct calls to `os.Exit` with `exit` in the `checkForFileChanges` function. [[1]](diffhunk://#diff-5d8d60fa78da8b711b2e021fa0643a9e8d880a4ed6eca069019dd76d9a37677eR28-R39) [[2]](diffhunk://#diff-5d8d60fa78da8b711b2e021fa0643a9e8d880a4ed6eca069019dd76d9a37677eL67-R75)
* Introduced a `resetWatchCertificateFileOnce` function to reset the …

test: add UT for filewatcher

---

pkg/azurefileplugin/Dockerfile
test/sanity/run-test.sh

/kind cleanup
chore: fix azcopy download error
```
--2025-01-10 02:32:03--  https://aka.ms/downloadazcopy-v10-linux
Resolving aka.ms (aka.ms)... 23.210.242.211
Connecting to aka.ms (aka.ms)|23.210.242.211|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://azcopyvnext-awgzd8g7aagqhzhe.b02.azurefd.net/releases/release-10.27.1-20241113/azcopy_linux_amd64_10.27.1.tar.gz [following]
--2025-01-10 02:32:03--  https://azcopyvnext-awgzd8g7aagqhzhe.b02.azurefd.net/releases/release-10.27.1-20241113/azcopy_linux_amd64_10.27.1.tar.gz
Resolving azcopyvnext-awgzd8g7aagqhzhe.b02.azurefd.net (azcopyvnext-awgzd8g7aagqhzhe.b02.azurefd.net)... 13.107.246.41, 2620:1ec:bdf::41
Connecting to …
```

chore: fix azcopy download error

---

deploy/example/pv-azurefile-csi.yaml
deploy/example/storageclass-azurefile-csi.yaml
docs/install-csi-driver-master.md

Add comment for mount permission 
Fix installation guide
Fixes #
```
chore: add comment for mount permission and fix installation guide
```

doc: Update examples for mount permissions setting

---

pkg/azurefileplugin/Dockerfile
test/sanity/run-test.sh

/kind cleanup
chore: fix azcopy download error
cherrypick of https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/2335
```
--2025-01-10 02:32:03--  https://aka.ms/downloadazcopy-v10-linux
Resolving aka.ms (aka.ms)... 23.210.242.211
Connecting to aka.ms (aka.ms)|23.210.242.211|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://azcopyvnext-awgzd8g7aagqhzhe.b02.azurefd.net/releases/release-10.27.1-20241113/azcopy_linux_amd64_10.27.1.tar.gz [following]
--2025-01-10 02:32:03--  https://azcopyvnext-awgzd8g7aagqhzhe.b02.azurefd.net/releases/release-10.27.1-20241113/azcopy_linux_amd64_10.27.1.tar.gz
Resolving azcopyvnext-awgzd8g7aagqhzhe.b02.azurefd.net …
```

[release-1.30] chore: fix azcopy download error

---

pkg/csi-common/utils.go
pkg/csi-common/utils_test.go

This pull request focuses on improving error handling in the `pkg/csi-common/utils.go` file by replacing calls to `klog.Fatalf` with `klog.Errorf`, and updating the associated test cases accordingly. The most important changes include the removal of the `klogFatalf` function, the modification of error logging in the `ListenEndpoint` function, and the simplification of the `TestListenEndpoint` test cases.
Improvements to error handling:
* [`pkg/csi-common/utils.go`](diffhunk://#diff-0d556f293c81880b06d6591091b951a2114fa383010513710c843f1d1b6a3e7aL45-R48): Removed the `klogFatalf` function and replaced calls to it with `klog.Errorf` in the `ListenEndpoint` function to avoid terminating the program on errors. [[1]](diffhunk://#diff-0d556f293c81880b06d6591091b951a2114fa383010513710c843f1d1b6a3 …

test: refine UT for ListenEndpoint in utils.go

---

pkg/azurefile/azurefile.go
pkg/azurefile/controllerserver.go
pkg/util/util.go
pkg/util/util_test.go

/kind bug
fix: cleanup azcopy jobs after job complete
this could reduce .azopy/plans folder files
Fixes #2387
```
fix: cleanup azcopy jobs after job complete
```

fix: cleanup azcopy jobs after job complete

---

pkg/azurefile/azure.go

/kind bug
fix: disable UseInstanceMetadata in controller
This PR fixes the bug introduced in track2 adoption refactoring
Fixes #
```
fix: disable UseInstanceMetadata in controller
```

fix: disable UseInstanceMetadata in controller

---

go.mod
go.sum
vendor/modules.txt
vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/storage/azure_storageaccount.go

/kind bug
fix: account match algorithm when source account name is provided, this is used in volume clone and snapshot restore scenarios, related to fix: https://github.com/kubernetes-sigs/cloud-provider-azure/pull/8560
<details>
```
I0306 12:52:31.840777       1 utils.go:105] GRPC call: /csi.v1.Controller/CreateVolume
I0306 12:52:31.840801       1 utils.go:106] GRPC request: {"capacity_range":{"required_bytes":5368709120},"name":"pvc-23e65b01-80b4-4c71-8f42-1fe6fccbd64b","parameters":{"csi.storage.k8s.io/pv/name":"pvc-23e65b01-80b4-4c71-8f42-1fe6fccbd64b","csi.storage.k8s.io/pvc/name":"afspvc","csi.storage.k8s.io/pvc/namespace":"choudharypr-test-target","skuName":"Standard_LRS"},"volume_capabilities":[{"AccessType":{"Mount":{"mount_flags":["mfsymlinks","actimeo=30","nosharesock"]}},"acces …
```

fix: account match algorithm when source account name is provided

---

docs/driver-parameters.md

When a subnets/write permission is requested in Azure, there are subsequent Linked Access Checks performed by the Network Resource Provider in the event that the customer has configured an additional property (such as an NSG, or a route table) on the subnet. These permissions are currently missing from the permissions requirements documentation, so if a user attempts to use the driver to execute a subnets/write action with one of these additional properties present, it will fail with linked access error.
Fixes # N/A
As far as I'm aware this isn't covered by unit tests or upgrade tests, but feel free to point me in …

doc: add linked access permissions required for subnets/write doc

---

pkg/azurefile-proxy/init.sh

/kind bug
fix: aznfs package install failure on arm64 node
Fixes #
<details>
```
+ MIGRATE_K8S_REPO=false
+ KUBELET_PATH=/var/lib/kubelet
+ [ /var/lib/kubelet != /var/lib/kubelet ]
+ HOST_CMD=nsenter --mount=/proc/1/ns/mnt
+ nsenter --mount=/proc/1/ns/mnt cat /etc/os-release
+ grep ^ID=
+ tr -d "
+ cut -d= -f2
+ DISTRIBUTION=ubuntu
+ nsenter --mount=/proc/1/ns/mnt uname -m
+ ARCH=aarch64
+ echo Linux distribution: ubuntu, Arch: aarch64
+ [ ubuntu != azurelinux ]
+ [ ubuntu != ubuntu ]
+ . ./azurefile-proxy/install-proxy.sh
+ set -xe
+ [ false = true ]
+ [ true = true ]
+ [ ubuntu = ubuntu ]
+ AZNFS_VERSION=0.3.15
+ echo install aznfs …
```

fix: aznfs package install failure on arm64 node

---

pkg/azurefile/utils.go
pkg/azurefile/utils_test.go

/kind bug
If the volumeattributes.mountpermissions are set for an nfs volume, we check if the permissions on the mount targetPath are the same as the expected mountPermissions. When this check is made currently, the targetPath mode bits are masked to use only the permission bits.
We should do the same with the mountPermissions bits to ensure that there isn't an unnecessary mismatch.
After the comparison, if the mount permissions are different, this PR ensures that only mount permissions change with the chmod operation and the rest of the bits like gid remain as is. 
Fixes #2606
```
none
```

fix: only use the permission bits for chmod

---

pkg/azurefile/nodeserver.go
pkg/azurefile/nodeserver_test.go

/kind bug
fix: only unmount kata volume if it's kata node
Fixes #
```
fix: only unmount kata volume if it's kata node
```

fix: only unmount kata volume if it's kata node

---

pkg/azurefile/azurefile.go
pkg/azurefile/controllerserver.go
pkg/azurefile/controllerserver_test.go
test/e2e/dynamic_provisioning_test.go

/kind feature
feat: support nfs volume clone and snapshot restore
Fixes #
<details>
```
I0706 15:15:32.397069       1 utils.go:105] GRPC call: /csi.v1.Controller/CreateVolume
I0706 15:15:32.397092       1 utils.go:106] GRPC request: {"capacity_range":{"required_bytes":107374182400},"name":"pvc-0d58dc6a-84b9-4bcc-b4aa-4cc3ff2543bd","parameters":{"csi.storage.k8s.io/pv/name":"pvc-0d58dc6a-84b9-4bcc-b4aa-4cc3ff2543bd","csi.storage.k8s.io/pvc/name":"pvc-azurefile-snapshot-restored2","csi.storage.k8s.io/pvc/namespace":"default","protocol":"nfs","resourceGroup":"andy-dev","storageAccount":"andynfs"},"volume_capabilities":[{"AccessType":{"Mo …
```

feat: support nfs volume clone and snapshot restore
